const ACTIONS = [
  {id:'QUICK_ATTACK',label:'โจมตีเร็ว',cost:12,mp:0,power:70,posture:8,tempo:7,commit:45,kind:'attack',startup:15,recovery:14,accuracy:0.92,range:'CLOSE'},
  {id:'HEAVY_ATTACK',label:'โจมตีหนัก',cost:24,mp:0,power:145,posture:20,tempo:11,commit:90,kind:'attack',startup:40,recovery:35,accuracy:0.76,range:'CLOSE'},
  {id:'GUARD_BREAK',label:'ทำลายการ์ด',cost:18,mp:0,power:35,posture:34,tempo:14,commit:70,kind:'attack',startup:28,recovery:24,accuracy:0.84,range:'CLOSE'},
  {id:'BLOCK',label:'ป้องกัน',cost:8,mp:0,power:0,posture:0,tempo:2,commit:35,kind:'defense',startup:8,recovery:8,accuracy:1,range:'ANY'},
  {id:'DODGE',label:'หลบ',cost:14,mp:0,power:0,posture:0,tempo:5,commit:55,kind:'defense',startup:10,recovery:16,accuracy:1,range:'ANY'},
  {id:'PARRY',label:'ปัดป้อง',cost:16,mp:0,power:0,posture:0,tempo:9,commit:75,kind:'defense',startup:7,recovery:22,accuracy:1,range:'CLOSE'},
  {id:'FEINT',label:'หลอกโจมตี',cost:9,mp:0,power:0,posture:4,tempo:10,commit:30,kind:'setup',startup:12,recovery:10,accuracy:1,range:'CLOSE'},
  {id:'RECOVER',label:'ฟื้นกำลัง',cost:-24,mp:-10,power:0,posture:-12,tempo:-4,commit:20,kind:'recover',startup:24,recovery:12,accuracy:1,range:'ANY'}
];

const INTENTS={TEST:'ทดสอบเชิง',DAMAGE:'สร้างความเสียหาย',BREAK:'ทำลายสมดุล',BAIT:'ล่อให้ตอบสนอง',CONTROL:'คุมจังหวะ',RECOVER:'ฟื้นทรัพยากร',FINISH:'ปิดการต่อสู้',SURVIVE:'เอาตัวรอด'};
const $=id=>document.getElementById(id), clamp=(v,min,max)=>Math.max(min,Math.min(max,v)), fmt=n=>Math.round(n), pct=n=>`${fmt(clamp(n,0,1)*100)}%`;
const actionById=id=>ACTIONS.find(a=>a.id===id), actionLabel=id=>actionById(id)?.label||id;
let seedBase=Number(new URLSearchParams(location.search).get('seed'))||424242, rngState=seedBase>>>0;
function rand(){rngState=(rngState+0x6D2B79F5)>>>0;let t=rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}
function blankCounts(){return Object.fromEntries(ACTIONS.map(a=>[a.id,1]))}
function fighter(name,side,cfg){return{name,side,maxHP:cfg.hp,hp:cfg.hp,maxMP:cfg.mp,mp:cfg.mp,maxStamina:100,stamina:100,maxPosture:100,posture:100,atk:cfg.atk,def:cfg.def,mag:cfg.mag,mdef:cfg.mdef,spd:cfg.spd,accuracy:cfg.accuracy,evasion:cfg.evasion,critChance:cfg.critChance,critDamage:cfg.critDamage,distance:1,rangeState:'CLOSE',mobility:cfg.mobility,reach:cfg.reach,morale:70,confidence:60,focus:72,stress:18,currentAction:null,previousAction:null,startup:0,recovery:0,cooldown:0,intent:'TEST',commitment:0,infoCertainty:55,tempo:0,causal:0,planStability:100,memory:{total:0,counts:blankCounts(),lowHP:blankCounts(),lowStamina:blankCounts(),lowPosture:blankCounts(),afterAttack:blankCounts()},belief:null,prediction:null,derived:null,lastCandidates:[],reason:''}}
let A,B,turn=0,running=true,timer=null,speed=1,finished=false,history=[],metrics={nodes:0,predHits:0,predTotal:0,repeats:0,actions:0};
function reset(){rngState=seedBase>>>0;turn=0;finished=false;history=[];metrics={nodes:0,predHits:0,predTotal:0,repeats:0,actions:0};A=fighter('อัศวิน','a',{hp:1000,mp:80,atk:108,def:112,mag:55,mdef:88,spd:92,accuracy:0.84,evasion:0.11,critChance:0.12,critDamage:1.55,mobility:72,reach:1});B=fighter('ซามูไร','b',{hp:900,mp:60,atk:116,def:96,mag:42,mdef:78,spd:108,accuracy:0.87,evasion:0.16,critChance:0.16,critDamage:1.62,mobility:84,reach:1});log(`เริ่มการต่อสู้แบบกำหนดผลซ้ำได้ — Seed ${seedBase}`);render();schedule()}
function observe(observer,enemy){const uncertainty=Math.max(3,18-observer.focus*0.12),noise=()=>(rand()*2-1)*uncertainty;return{hp:clamp(enemy.hp+noise()*2,0,enemy.maxHP),stamina:clamp(enemy.stamina+noise(),0,100),posture:clamp(enemy.posture+noise(),0,100),distance:enemy.distance,previousAction:enemy.previousAction,confidence:clamp(observer.focus*0.006+observer.memory.total*0.02,0.5,0.94)}}
function selectMemorySlice(self,obs,enemy){if(obs.hp<0.3*enemy.maxHP)return self.memory.lowHP;if(obs.stamina<35)return self.memory.lowStamina;if(obs.posture<35)return self.memory.lowPosture;if(self.previousAction&&self.previousAction.includes('ATTACK'))return self.memory.afterAttack;return self.memory.counts}
function buildBelief(self,enemy){const obs=observe(self,enemy),src=selectMemorySlice(self,obs,enemy),total=Object.values(src).reduce((a,b)=>a+b,0),distribution={};for(const a of ACTIONS)distribution[a.id]=src[a.id]/total;const top=Object.entries(distribution).sort((x,y)=>y[1]-x[1]).slice(0,3);self.belief={observed:obs,enemyStaminaEstimate:fmt(obs.stamina),enemyPostureEstimate:fmt(obs.posture),distribution,top,confidence:clamp(obs.confidence+self.memory.total*0.012,0.52,0.94)};self.infoCertainty=fmt(self.belief.confidence*100);return self.belief}
function threatOpportunity(self,enemy,belief){const hpRatio=self.hp/self.maxHP,enemyHp=belief.observed.hp/enemy.maxHP,p=belief.distribution;const burstThreat=clamp((p.HEAVY_ATTACK*.55+p.QUICK_ATTACK*.2+p.GUARD_BREAK*.25)*(1-hpRatio+.35),0,1),breakThreat=clamp((1-self.posture/100)*.55+p.GUARD_BREAK*.5,0,1),deathRisk=clamp((1-hpRatio)*.75+burstThreat*.5,0,1),breakOpp=clamp((1-belief.observed.posture/100)*.7+p.BLOCK*.35,0,1),killOpp=clamp((1-enemyHp)*.78+(self.stamina/100)*.12,0,1),interruptOpp=clamp(p.HEAVY_ATTACK*.65*(self.spd/enemy.spd),0,1),recoverOpp=clamp((1-self.stamina/100)*.75+(1-self.posture/100)*.25,0,1),survive1=clamp(1-deathRisk*.68-breakThreat*.18,.02,.99),survive2=clamp(survive1*survive1-burstThreat*.08,.01,.98);return{burstThreat,breakThreat,deathRisk,breakOpp,killOpp,interruptOpp,recoverOpp,survive1,survive2}}
function chooseIntent(self,enemy,d){if(d.deathRisk>.68)return'SURVIVE';if(self.stamina<28||d.recoverOpp>.58)return'RECOVER';if(d.killOpp>.72)return'FINISH';if(d.breakOpp>.62)return'BREAK';const p=self.belief.distribution;if(p.BLOCK+p.PARRY+p.DODGE>.48)return'BAIT';if(self.tempo<-14)return'CONTROL';return turn<4?'TEST':'DAMAGE'}
function feasible(action,self){if(action.cost>0&&self.stamina<action.cost)return false;if(action.mp>0&&self.mp<action.mp)return false;if(action.range==='CLOSE'&&self.rangeState!=='CLOSE')return false;return true}
function estimateUtility(action,self,enemy,belief,d){metrics.nodes++;const p=belief.distribution,hit=clamp(action.accuracy*self.accuracy-enemy.evasion-p.DODGE*.22-p.PARRY*.18,.06,.96),effectivePower=action.power*(self.atk/(self.atk+enemy.def*.72)),damage=effectivePower*hit,posture=action.posture*(1+p.BLOCK*.55),killValue=d.killOpp*(action.id==='HEAVY_ATTACK'?42:18),breakValue=d.breakOpp*(action.id==='GUARD_BREAK'?45:12),controlValue=action.tempo*1.25+(action.id==='PARRY'?d.burstThreat*30:0),infoGain=action.id==='FEINT'?22:(turn<5?8:3),causal=action.id==='GUARD_BREAK'?(100-belief.observed.posture)*.34+p.BLOCK*30:action.id==='FEINT'?(p.BLOCK+p.PARRY)*45:action.id==='QUICK_ATTACK'?p.RECOVER*24+d.interruptOpp*18:0,resourceGain=action.id==='RECOVER'?d.recoverOpp*62:0,defense=action.kind==='defense'?(d.deathRisk*45+d.breakThreat*28):0,predictability=self.previousAction===action.id?14:0,cost=Math.max(0,action.cost)*.45+action.recovery*.12,risk=(action.kind==='attack'?d.deathRisk*24:0)+(action.id==='HEAVY_ATTACK'?p.PARRY*34:0);let score=damage*.6+posture*.72+killValue+breakValue+controlValue+infoGain+causal+resourceGain+defense-cost-risk-predictability;if(self.intent==='RECOVER'&&action.id==='RECOVER')score+=48;if(self.intent==='FINISH'&&action.id==='HEAVY_ATTACK')score+=30;if(self.intent==='BREAK'&&action.id==='GUARD_BREAK')score+=36;if(self.intent==='BAIT'&&action.id==='FEINT')score+=40;if(self.intent==='SURVIVE'&&action.kind==='defense')score+=34;const aggression=clamp(.8+(self.confidence-self.stress)/200,.65,1.2);score*=action.kind==='attack'?aggression:1;return{score,damage,posture,causal,infoGain,deathRisk:d.deathRisk,survive:d.survive1}}
function decide(self,enemy){const belief=buildBelief(self,enemy),derived=threatOpportunity(self,enemy,belief);self.derived=derived;self.intent=chooseIntent(self,enemy,derived);const candidates=ACTIONS.filter(a=>feasible(a,self)).map(a=>({action:a,...estimateUtility(a,self,enemy,belief,derived)})).sort((x,y)=>y.score-x.score);self.lastCandidates=candidates;const pick=candidates[0]||{action:actionById('RECOVER'),score:0,causal:0};self.commitment=pick.action.commit;self.causal=fmt(pick.causal);self.currentAction=pick.action.id;self.startup=pick.action.startup;self.recovery=pick.action.recovery;const top=belief.top[0];self.prediction={action:top[0],confidence:belief.confidence,damageTaken:fmt(derived.burstThreat*120),postureRisk:pct(derived.breakThreat),survival:pct(derived.survive1)};self.reason=`เจตนา: ${INTENTS[self.intent]} | คาดว่า ${actionLabel(top[0])} ${fmt(top[1]*100)}% | รอดเทิร์นหน้า ${pct(derived.survive1)} | ${pick.causal>12?'สร้างเหตุ–ผลต่อเนื่อง':'คะแนนรวมดีที่สุด'}`;return pick.action}
function spend(f,a){if(a.id!=='RECOVER')f.stamina=clamp(f.stamina-a.cost,0,f.maxStamina);f.mp=clamp(f.mp-Math.max(0,a.mp),0,f.maxMP)}
function applyRecover(f){f.stamina=clamp(f.stamina+24,0,f.maxStamina);f.mp=clamp(f.mp+10,0,f.maxMP);f.posture=clamp(f.posture+12,0,f.maxPosture);f.tempo-=4}
function canInterrupt(attacker,defender,act,react){return act.kind==='attack'&&react.kind==='attack'&&act.startup+Math.max(0,100-attacker.spd)*.05<react.startup+Math.max(0,100-defender.spd)*.05-8}
function resolveOne(attacker,defender,act,react){if(act.id==='RECOVER'){applyRecover(attacker);return`${attacker.name} ฟื้นกำลังและสมดุล`}if(act.kind==='defense'){attacker.posture=clamp(attacker.posture+5,0,100);attacker.tempo+=1;return`${attacker.name} ใช้ ${act.label}`}if(act.id==='FEINT'){attacker.tempo+=10;attacker.causal=clamp(attacker.causal+12,0,100);if(['PARRY','BLOCK','DODGE'].includes(react.id)){defender.stamina=clamp(defender.stamina-6,0,100);defender.tempo-=7;attacker.tempo+=7;return`${attacker.name} หลอกจน ${defender.name} ตอบสนองด้วย ${react.label}`}return`${attacker.name} หลอกเพื่อเก็บข้อมูล`}if(canInterrupt(attacker,defender,act,react)){defender.posture=clamp(defender.posture-10,0,100);defender.tempo-=8;attacker.tempo+=8}if(react.id==='PARRY'&&rand()<(act.id==='HEAVY_ATTACK'?.48:.62)){attacker.posture=clamp(attacker.posture-18,0,100);attacker.tempo-=12;defender.tempo+=14;return`${defender.name} ปัดป้อง ${act.label} ของ ${attacker.name} สำเร็จ`}let hit=act.accuracy*attacker.accuracy-defender.evasion;if(react.id==='DODGE')hit-=act.id==='HEAVY_ATTACK'?.40:.26;if(react.id==='BLOCK')hit-=.05;hit=clamp(hit,.05,.96);if(rand()>hit){attacker.tempo-=5;defender.tempo+=6;return`${defender.name} หลีกเลี่ยง ${act.label} ของ ${attacker.name}`}let dmg=act.power*(attacker.atk/(attacker.atk+defender.def*.72)),po=act.posture,crit=rand()<attacker.critChance;if(crit)dmg*=attacker.critDamage;if(react.id==='BLOCK'){dmg*=.34;po*=1.45;defender.stamina=clamp(defender.stamina-7,0,100)}if(react.id==='DODGE')dmg*=.72;if(act.id==='GUARD_BREAK'&&react.id==='BLOCK'){po*=1.8;attacker.causal=clamp(attacker.causal+22,0,100)}defender.hp=clamp(defender.hp-dmg,0,defender.maxHP);defender.posture=clamp(defender.posture-po,0,100);attacker.tempo+=act.tempo;defender.tempo-=Math.max(2,act.tempo*.55);if(defender.posture===0){defender.tempo-=12;attacker.causal=clamp(attacker.causal+28,0,100)}return`${attacker.name} ใช้ ${act.label} สร้างความเสียหาย ${fmt(dmg)}${crit?' คริติคอล!':''}${defender.posture===0?' — สมดุลแตก':''}`}
function updateMemory(observer,enemy,enemyAction){const m=observer.memory;m.total++;m.counts[enemyAction.id]++;if(enemy.hp/enemy.maxHP<.3)m.lowHP[enemyAction.id]++;if(enemy.stamina<35)m.lowStamina[enemyAction.id]++;if(enemy.posture<35)m.lowPosture[enemyAction.id]++;if(observer.previousAction&&observer.previousAction.includes('ATTACK'))m.afterAttack[enemyAction.id]++;observer.confidence=clamp(55+m.total*2,55,92)}
function updatePredictionMetric(f,actual){if(!f.prediction)return;metrics.predTotal++;if(f.prediction.action===actual.id)metrics.predHits++}
function postTurnMental(f){const hpRatio=f.hp/f.maxHP;f.stress=clamp(18+(1-hpRatio)*48-Math.max(0,f.tempo)*.15,0,100);f.morale=clamp(55+f.tempo*.4+hpRatio*25,0,100);f.focus=clamp(72-f.stress*.18+f.confidence*.12,35,95);f.planStability=clamp(100-f.stress*.45-Math.abs(f.tempo)*.12,15,100)}
function step(){if(finished)return;turn++;const aAct=decide(A,B),bAct=decide(B,A);updatePredictionMetric(A,bAct);updatePredictionMetric(B,aAct);metrics.actions+=2;if(A.previousAction===aAct.id)metrics.repeats++;if(B.previousAction===bAct.id)metrics.repeats++;spend(A,aAct);spend(B,bAct);const aFirst=(A.spd-aAct.startup)>=(B.spd-bAct.startup),first=aFirst?[A,B,aAct,bAct]:[B,A,bAct,aAct],second=aFirst?[B,A,bAct,aAct]:[A,B,aAct,bAct],l1=resolveOne(...first);let l2='';if(second[0].hp>0&&second[1].hp>0)l2=resolveOne(...second);updateMemory(A,B,bAct);updateMemory(B,A,aAct);A.previousAction=aAct.id;B.previousAction=bAct.id;A.currentAction=null;B.currentAction=null;A.stamina=clamp(A.stamina+4,0,100);B.stamina=clamp(B.stamina+4,0,100);A.posture=clamp(A.posture+2,0,100);B.posture=clamp(B.posture+2,0,100);postTurnMental(A);postTurnMental(B);const tx={turn,a:aAct.id,b:bAct.id,aHP:fmt(A.hp),bHP:fmt(B.hp),aST:fmt(A.stamina),bST:fmt(B.stamina),rng:rngState};history.push(tx);log(`T${turn} | ${A.name}:${aAct.label} vs ${B.name}:${bAct.label} | ${l1}${l2?` · ${l2}`:''}`);if(A.hp<=0||B.hp<=0||turn>=120){finished=true;running=false;const winner=A.hp===B.hp?'เสมอ':A.hp>B.hp?A.name:B.name;$('result').textContent=`${winner} — ${turn} เทิร์น — Seed ${seedBase}`;log(`ปิดธุรกรรมสุดท้าย | ผู้ชนะ=${winner} | replay-hash=${history.map(x=>`${x.a[0]}${x.b[0]}${x.aHP}${x.bHP}`).join('-')}`)}render()}
function predictionText(f){if(!f.belief)return'กำลังเก็บข้อมูลพฤติกรรม…';return f.belief.top.map(([id,p])=>`${actionLabel(id)} ${fmt(p*100)}%`).join(' · ')+` | ความแน่นอน ${f.infoCertainty}%`}
function candidatesHTML(f){if(!f.lastCandidates.length)return'<div class="muted">รอการตัดสินใจครั้งแรก…</div>';const rows=f.lastCandidates.slice(0,5).map((c,i)=>`<div class="candidate ${i===0?'chosen':''}"><span>${i===0?'▶ ':''}${c.action.label}</span><b>${fmt(c.score)}</b></div>`).join('');return rows+`<div class="muted reason">${f.reason}</div>`}
function derivedHTML(f){if(!f.derived)return'<div class="muted">ยังไม่มีข้อมูล</div>';const d=f.derived;return`<div class="miniGrid"><div>ความเสี่ยงตาย<b>${pct(d.deathRisk)}</b></div><div>เสี่ยงสมดุลแตก<b>${pct(d.breakThreat)}</b></div><div>โอกาสปิดเกม<b>${pct(d.killOpp)}</b></div><div>โอกาสทำลายสมดุล<b>${pct(d.breakOpp)}</b></div><div>รอด 1 เทิร์น<b>${pct(d.survive1)}</b></div><div>รอด 2 เทิร์น<b>${pct(d.survive2)}</b></div></div>`}
function setBar(id,value,max=100){$(id).style.width=`${clamp(value/max*100,0,100)}%`}
function renderF(f){$(f.side+'HP').textContent=fmt(f.hp);$(f.side+'MP').textContent=fmt(f.mp);$(f.side+'ST').textContent=fmt(f.stamina);$(f.side+'PO').textContent=fmt(f.posture);setBar(f.side+'HPBar',f.hp,f.maxHP);setBar(f.side+'MPBar',f.mp,f.maxMP);setBar(f.side+'STBar',f.stamina);setBar(f.side+'POBar',f.posture);$(f.side+'Tempo').textContent=fmt(f.tempo);$(f.side+'Conf').textContent=fmt(f.confidence);$(f.side+'Intent').textContent=INTENTS[f.intent];$(f.side+'Predict').textContent=predictionText(f);$(f.side+'Candidates').innerHTML=candidatesHTML(f);$(f.side+'Derived').innerHTML=derivedHTML(f);$(f.side+'Mental').textContent=`ขวัญ ${fmt(f.morale)} · โฟกัส ${fmt(f.focus)} · เครียด ${fmt(f.stress)} · เสถียรภาพแผน ${fmt(f.planStability)}`}
function render(){renderF(A);renderF(B);$('turn').textContent=`เทิร์น ${turn}`;const focus=(A.lastCandidates[0]?.score??0)>=(B.lastCandidates[0]?.score??0)?A:B;$('sigIntent').textContent=INTENTS[focus.intent];$('sigCommit').textContent=`${focus.commitment}%`;$('sigInfo').textContent=`${focus.infoCertainty}%`;$('sigTempo').textContent=fmt(A.tempo-B.tempo);$('sigCausal').textContent=fmt(focus.causal);$('phase').textContent=finished?'การดวลจบแล้ว — ผลลัพธ์กำหนดซ้ำได้':'โลกจริง → สังเกต → ความเชื่อ → คาดการณ์ → ประเมินภัย/โอกาส → Utility → Commit → Resolve → เรียนรู้';$('pause').textContent=running?'⏸ หยุด':'▶ เล่นต่อ';$('speed').textContent=`▶ ${speed}×`;$('metricNodes').textContent=metrics.nodes;$('metricPred').textContent=metrics.predTotal?pct(metrics.predHits/metrics.predTotal):'0%';$('metricRepeat').textContent=metrics.actions?pct(metrics.repeats/metrics.actions):'0%';$('metricDepth').textContent='1 + Reaction'}
function log(text){const e=document.createElement('div');e.className='entry';e.textContent=text;$('log').prepend(e)}
function schedule(){clearInterval(timer);timer=setInterval(()=>{if(running&&!finished)step()},1000/speed)}
$('pause').addEventListener('click',()=>{running=!running;render()});$('step').addEventListener('click',()=>{running=false;step();render()});$('speed').addEventListener('click',()=>{speed=speed===1?2:speed===2?4:1;schedule();render()});$('reset').addEventListener('click',()=>{running=true;$('log').innerHTML='';$('result').textContent='';reset()});reset();
