import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let rngState=424242>>>0;
function rand(){rngState=(rngState+0x6D2B79F5)>>>0;let t=rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}

const SKILLS={
 quick:{name:'Quick Slash',label:'ฟันเร็ว',kind:'physical',power:62,accuracy:.95,mp:0,st:10,posture:8,anim:'slash'},
 heavy:{name:'Heavy Slash',label:'ฟันหนัก',kind:'physical',power:112,accuracy:.82,mp:0,st:22,posture:18,anim:'heavy'},
 break:{name:'Guard Break',label:'ทำลายการ์ด',kind:'physical',power:42,accuracy:.9,mp:0,st:18,posture:30,anim:'heavy'},
 flame:{name:'Flame Edge',label:'คมดาบเพลิง',kind:'magic',power:94,accuracy:.9,mp:14,st:5,posture:6,anim:'magic'},
 focus:{name:'Focus',label:'ตั้งสมาธิ',kind:'buff',power:0,accuracy:1,mp:8,st:0,posture:0,anim:'buff'}
};

function actor(name,side,cfg){return{
 name,side,maxHP:cfg.hp,hp:cfg.hp,maxMP:cfg.mp,mp:cfg.mp,maxStamina:100,stamina:100,maxPosture:100,posture:100,
 atk:cfg.atk,def:cfg.def,mag:cfg.mag,mdef:cfg.mdef,spd:cfg.spd,accuracy:cfg.accuracy,evasion:cfg.evasion,crit:.12,critDmg:1.55,
 guarding:false,focusBuff:0,status:'READY',model:null,homeX:side==='p'?-2.6:2.6,homeZ:0
};}

let P=actor('อัศวินแห่งรุ่งอรุณ','p',{hp:980,mp:60,atk:108,def:104,mag:72,mdef:86,spd:92,accuracy:.92,evasion:.08});
let E=actor('ซามูไรเงา','e',{hp:900,mp:50,atk:112,def:92,mag:68,mdef:82,spd:104,accuracy:.9,evasion:.12});
let phase='PLAYER_COMMAND',busy=false,turn=1,selectedCommand=null,queue=[];

const scene=new THREE.Scene();scene.background=new THREE.Color(0x2b1c12);scene.fog=new THREE.FogExp2(0x6f4c2e,.017);
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;$('viewport').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-10,10,7,-7,.1,100);camera.position.set(11,12,11);camera.lookAt(0,0,0);scene.add(camera);
scene.add(new THREE.HemisphereLight(0xffe0b0,0x342218,2.0));const sun=new THREE.DirectionalLight(0xffdfae,3.8);sun.position.set(-7,14,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(sun);const fill=new THREE.DirectionalLight(0xb8c8ff,.7);fill.position.set(8,7,-8);scene.add(fill);

const MAT={sand:new THREE.MeshStandardMaterial({color:0x8e704b,roughness:.95}),stone:new THREE.MeshStandardMaterial({color:0x6a5846,roughness:.92}),stone2:new THREE.MeshStandardMaterial({color:0x44362c,roughness:.96}),blue:new THREE.MeshStandardMaterial({color:0x285c91,roughness:.7}),red:new THREE.MeshStandardMaterial({color:0x8a2b20,roughness:.72}),steel:new THREE.MeshStandardMaterial({color:0xa4a8ad,metalness:.72,roughness:.35}),dark:new THREE.MeshStandardMaterial({color:0x1e1916,roughness:.9}),skin:new THREE.MeshStandardMaterial({color:0xc08b65,roughness:.82})};
function addMesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o;}
function buildArena(){addMesh(new THREE.CylinderGeometry(6.7,6.7,.4,64),MAT.stone2,0,-.25,0);addMesh(new THREE.CylinderGeometry(6.0,6.0,.2,64),MAT.sand,0,0,0);for(let i=0;i<36;i++){const a=i/36*Math.PI*2,r=6.7,h=1.6+(i%6===0?.25:0);const b=addMesh(new THREE.BoxGeometry(.92,h,.7),i%2?MAT.stone:MAT.stone2,Math.cos(a)*r,h/2-.05,Math.sin(a)*r);b.rotation.y=-a+Math.PI/2;}for(let t=0;t<2;t++){for(let i=0;i<42;i++){const a=i/42*Math.PI*2,r=7.35+t*.68;const s=addMesh(new THREE.BoxGeometry(.9,.38,.78),t?MAT.stone2:MAT.stone,Math.cos(a)*r,.35+t*.45,Math.sin(a)*r);s.rotation.y=-a+Math.PI/2;}}for(const x of [-3.8,3.8]){addMesh(new THREE.CylinderGeometry(.35,.48,2.0,12),MAT.stone,x,1.0,-2.8);addMesh(new THREE.CylinderGeometry(.35,.48,2.0,12),MAT.stone,x,1.0,2.8);}}
buildArena();

function fighterModel(actor){const g=new THREE.Group();const body=actor.side==='p'?MAT.blue:MAT.red;const torso=new THREE.Mesh(new THREE.CylinderGeometry(.28,.36,.82,8),body);torso.position.y=1.0;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.2,12,10),MAT.skin);head.position.y=1.58;g.add(head);const helmet=new THREE.Mesh(new THREE.ConeGeometry(.24,.28,8),MAT.steel);helmet.position.y=1.8;g.add(helmet);for(const x of [-.14,.14]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.09,.1,.62,7),MAT.dark);leg.position.set(x,.34,0);g.add(leg);}const swordArm=new THREE.Group();const arm=new THREE.Mesh(new THREE.CylinderGeometry(.075,.09,.6,7),MAT.steel);arm.position.y=-.27;swordArm.add(arm);const sword=new THREE.Mesh(new THREE.BoxGeometry(.055,.86,.035),MAT.steel);sword.position.set(0,-.78,0);swordArm.add(sword);swordArm.position.set(actor.side==='p'?.34:-.34,1.3,0);swordArm.rotation.z=actor.side==='p'?-1:1;g.add(swordArm);g.userData={swordArm,baseSwordRot:swordArm.rotation.z};g.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true;}});scene.add(g);return g;}
P.model=fighterModel(P);E.model=fighterModel(E);P.model.position.set(P.homeX,0,P.homeZ);E.model.position.set(E.homeX,0,E.homeZ);

function log(text){const d=document.createElement('div');d.className='entry';d.textContent=text;$('log').prepend(d);}
function pct(v,max){return `${clamp(v/max*100,0,100)}%`;}
function renderHUD(){for(const [a,prefix] of [[P,'p'],[E,'e']]){$(prefix+'HP').textContent=`${Math.round(a.hp)}/${a.maxHP}`;$(prefix+'MP').textContent=`${Math.round(a.mp)}/${a.maxMP}`;$(prefix+'ST').textContent=`${Math.round(a.stamina)}/100`;$(prefix+'PO').textContent=`${Math.round(a.posture)}/100`;$(prefix+'HPBar').style.width=pct(a.hp,a.maxHP);$(prefix+'MPBar').style.width=pct(a.mp,a.maxMP);$(prefix+'STBar').style.width=pct(a.stamina,100);$(prefix+'POBar').style.width=pct(a.posture,100);} $('playerState').textContent=P.guarding?'กำลังป้องกัน':P.status;$('enemyState').textContent=E.guarding?'กำลังป้องกัน':E.status;$('turnBadge').textContent=phase==='PLAYER_COMMAND'?`เทิร์น ${turn} · เลือกคำสั่ง`:`เทิร์น ${turn} · กำลังดำเนินการ`;document.querySelectorAll('.commands button').forEach(b=>b.disabled=busy||phase!=='PLAYER_COMMAND');}

function optionsFor(cmd){if(cmd==='attack')return[{label:'ฟันเร็ว',desc:'แม่นและเร็ว',action:{type:'skill',skill:'quick'}},{label:'ฟันหนัก',desc:'แรงแต่เสี่ยง',action:{type:'skill',skill:'heavy'}},{label:'ทำลายการ์ด',desc:'ลด Posture สูง',action:{type:'skill',skill:'break'}}];if(cmd==='skill')return[{label:'คมดาบเพลิง',desc:'MP 14 · เวทกายภาพ',action:{type:'skill',skill:'flame'}},{label:'ตั้งสมาธิ',desc:'MP 8 · เพิ่มความแม่น',action:{type:'skill',skill:'focus'}}];if(cmd==='guard')return[{label:'Guard',desc:'ลดดาเมจและฟื้น Posture',action:{type:'guard'}}];if(cmd==='item')return[{label:'Potion',desc:'ฟื้น HP 180',action:{type:'item',item:'potion'}}];if(cmd==='tactic')return[{label:'ตั้งรับ',desc:'Guard + ฟื้น Stamina',action:{type:'tactic',mode:'defensive'}},{label:'เร่งจังหวะ',desc:'ใช้ Stamina แลก Tempo',action:{type:'tactic',mode:'aggressive'}}];return[{label:'รอจังหวะ',desc:'ฟื้น Stamina และ MP เล็กน้อย',action:{type:'wait'}}];}
function showSub(cmd){selectedCommand=cmd;document.querySelectorAll('.commands button').forEach(b=>b.classList.toggle('active',b.dataset.cmd===cmd));$('subCommands').innerHTML='';for(const o of optionsFor(cmd)){const b=document.createElement('button');b.innerHTML=`${o.label}<small>${o.desc}</small>`;b.onclick=()=>commitPlayer(o.action);$('subCommands').appendChild(b);}}
document.querySelectorAll('.commands button').forEach(b=>b.onclick=()=>showSub(b.dataset.cmd));

function enemyChoice(){if(E.hp/E.maxHP<.3&&rand()<.35)return{type:'guard'};if(E.stamina<20)return{type:'wait'};const r=rand();if(r<.2)return{type:'skill',skill:'break'};if(r<.45)return{type:'skill',skill:'quick'};if(r<.7)return{type:'skill',skill:'heavy'};if(r<.86&&E.mp>=14)return{type:'skill',skill:'flame'};return{type:'guard'};}
function actionSpeed(actor,act){let base=actor.spd;if(act.type==='guard')base+=25;if(act.type==='wait')base+=12;if(act.type==='skill'){const s=SKILLS[act.skill];if(act.skill==='quick')base+=15;if(act.skill==='heavy')base-=12;if(s.kind==='magic')base-=5;}return base;}
function commitPlayer(action){if(busy||phase!=='PLAYER_COMMAND')return;busy=true;phase='RESOLVE';const enemy=enemyChoice();queue=[{actor:P,target:E,action,initiative:actionSpeed(P,action)+rand()*8},{actor:E,target:P,action:enemy,initiative:actionSpeed(E,enemy)+rand()*8}].sort((a,b)=>b.initiative-a.initiative);renderHUD();$('subCommands').innerHTML='';resolveQueue();}

function resolveSkill(attacker,defender,key){const s=SKILLS[key];if(attacker.mp<s.mp||attacker.stamina<s.st){log(`${attacker.name} ทรัพยากรไม่พอ จึงเสียจังหวะ`);return{hit:false,damage:0};}attacker.mp-=s.mp;attacker.stamina-=s.st;if(s.kind==='buff'){attacker.focusBuff=2;log(`${attacker.name} ตั้งสมาธิ ความแม่นยำเพิ่มขึ้น`);return{hit:true,damage:0,buff:true};}const hitChance=clamp(s.accuracy+attacker.accuracy-.9-defender.evasion+(attacker.focusBuff>0?.08:0),.15,.99);if(rand()>hitChance){log(`${attacker.name} ใช้ ${s.label} แต่พลาด`);return{hit:false,damage:0};}const attackStat=s.kind==='magic'?attacker.mag:attacker.atk;const defenseStat=s.kind==='magic'?defender.mdef:defender.def;let damage=s.power*(attackStat/(attackStat+defenseStat*.75));let crit=false;if(rand()<attacker.crit){damage*=attacker.critDmg;crit=true;}if(defender.guarding){damage*=.42;defender.posture=clamp(defender.posture-s.posture*1.45,0,100);}else defender.posture=clamp(defender.posture-s.posture,0,100);defender.hp=clamp(defender.hp-damage,0,defender.maxHP);log(`${attacker.name} ${s.label} → ${Math.round(damage)} ดาเมจ${crit?' CRIT!':''}`);return{hit:true,damage,crit,anim:s.anim};}
function applyAction(attacker,defender,act){attacker.guarding=false;if(act.type==='guard'){attacker.guarding=true;attacker.posture=clamp(attacker.posture+16,0,100);attacker.stamina=clamp(attacker.stamina+8,0,100);log(`${attacker.name} ตั้งการ์ด`);return{type:'guard'};}if(act.type==='wait'){attacker.stamina=clamp(attacker.stamina+24,0,100);attacker.mp=clamp(attacker.mp+5,0,attacker.maxMP);log(`${attacker.name} รอจังหวะและฟื้นทรัพยากร`);return{type:'wait'};}if(act.type==='item'){attacker.hp=clamp(attacker.hp+180,0,attacker.maxHP);log(`${attacker.name} ใช้ Potion ฟื้น 180 HP`);return{type:'item'};}if(act.type==='tactic'){if(act.mode==='defensive'){attacker.guarding=true;attacker.stamina=clamp(attacker.stamina+12,0,100);log(`${attacker.name} เข้าสู่ท่าตั้งรับ`);}else{attacker.stamina=clamp(attacker.stamina-10,0,100);attacker.focusBuff=1;log(`${attacker.name} เร่งจังหวะการต่อสู้`);}return{type:'tactic'};}const r=resolveSkill(attacker,defender,act.skill);return{type:'skill',skill:act.skill,...r};}

function tween(duration,update){return new Promise(resolve=>{const start=performance.now();function step(t){const p=clamp((t-start)/duration,0,1);update(p);if(p<1)requestAnimationFrame(step);else resolve();}requestAnimationFrame(step);});}
async function present(attacker,defender,act,result){const model=attacker.model,target=defender.model;const home=model.position.clone();const dir=new THREE.Vector3().subVectors(target.position,model.position);dir.y=0;dir.normalize();const attackPos=target.position.clone().addScaledVector(dir,-1.5);if(act.type==='skill'){await tween(260,p=>model.position.lerpVectors(home,attackPos,p));const arm=model.userData.swordArm;baseFacing();if(SKILLS[act.skill].anim==='magic'){const glow=new THREE.PointLight(0xff7a32,6,4);glow.position.copy(model.position).add(new THREE.Vector3(0,1.2,0));scene.add(glow);await tween(240,p=>{arm.rotation.z=model.userData.baseSwordRot+(attacker.side==='p'?1:-1)*Math.sin(p*Math.PI)*1.5;glow.intensity=6*(1-p);});scene.remove(glow);}else{await tween(220,p=>arm.rotation.z=model.userData.baseSwordRot+(attacker.side==='p'?1:-1)*Math.sin(p*Math.PI)*1.65);}if(result.hit){const base=target.position.clone();await tween(150,p=>{target.position.x=base.x+Math.sin(p*Math.PI)*dir.x*.22;target.position.z=base.z+Math.sin(p*Math.PI)*dir.z*.22;});}await tween(260,p=>model.position.lerpVectors(attackPos,home,p));arm.rotation.z=model.userData.baseSwordRot;}else if(act.type==='guard'){await tween(220,p=>model.userData.swordArm.rotation.z=model.userData.baseSwordRot+(attacker.side==='p'?1:-1)*p*.5);}else await tween(180,()=>{});function baseFacing(){model.rotation.y=Math.atan2(defender.model.position.x-model.position.x,defender.model.position.z-model.position.z);}}

async function resolveQueue(){for(const entry of queue){if(P.hp<=0||E.hp<=0)break;const {actor,target,action}=entry;actor.status='ACTION';target.status='WAIT';renderHUD();const result=applyAction(actor,target,action);await present(actor,target,action,result);if(actor.focusBuff>0)actor.focusBuff--;renderHUD();await tween(180,()=>{});}endTurn();}
function endTurn(){P.stamina=clamp(P.stamina+7,0,100);E.stamina=clamp(E.stamina+7,0,100);P.mp=clamp(P.mp+2,0,P.maxMP);E.mp=clamp(E.mp+2,0,E.maxMP);P.status='READY';E.status='READY';if(P.hp<=0||E.hp<=0){phase='END';busy=true;$('result').textContent=P.hp>E.hp?'ชัยชนะ!':'พ่ายแพ้';$('turnBadge').textContent='การต่อสู้จบแล้ว';renderHUD();return;}turn++;phase='PLAYER_COMMAND';busy=false;selectedCommand=null;document.querySelectorAll('.commands button').forEach(b=>b.classList.remove('active'));renderHUD();}

function faceEachOther(){P.model.rotation.y=Math.atan2(E.model.position.x-P.model.position.x,E.model.position.z-P.model.position.z);E.model.rotation.y=Math.atan2(P.model.position.x-E.model.position.x,P.model.position.z-E.model.position.z);}faceEachOther();
function resize(){const el=$('viewport'),w=el.clientWidth,h=Math.max(360,Math.min(650,w*.62));renderer.setSize(w,h,false);const aspect=w/h,fr=10.8;camera.left=-fr*aspect/2;camera.right=fr*aspect/2;camera.top=fr/2;camera.bottom=-fr/2;camera.updateProjectionMatrix();}
new ResizeObserver(resize).observe($('viewport'));resize();
function frame(t){P.model.position.y=Math.sin(t*.004)*.018;E.model.position.y=Math.sin(t*.004+1.4)*.018;faceEachOther();renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
showSub('attack');renderHUD();log('เริ่มการต่อสู้ JRPG แบบ Turn-Based');