import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';

const $=id=>document.getElementById(id), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let rngState=424242>>>0;
function rand(){rngState=(rngState+0x6D2B79F5)>>>0;let t=rngState;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;}

const ARENA_R=9, MOVE_BUDGET=4.4, STEP=.5, DUEL_MIN=1.15, ZOC_RANGE=1.9, MAX_JUMP=1.35;
const SKILLS={
 quick:{label:'ฟันเร็ว',kind:'physical',power:62,accuracy:.95,mp:0,st:10,posture:8,range:1.75,anim:'slash'},
 heavy:{label:'ฟันหนัก',kind:'physical',power:112,accuracy:.82,mp:0,st:22,posture:18,range:2.05,anim:'heavy'},
 break:{label:'ทำลายการ์ด',kind:'physical',power:42,accuracy:.90,mp:0,st:18,posture:30,range:1.65,anim:'heavy'},
 flame:{label:'คมดาบเพลิง',kind:'magic',power:94,accuracy:.90,mp:14,st:5,posture:6,range:3.8,anim:'magic'},
 focus:{label:'ตั้งสมาธิ',kind:'buff',power:0,accuracy:1,mp:8,st:0,posture:0,range:99,anim:'buff'}
};
const PLATFORMS=[
 {x:-2.7,z:2.8,r:2.0,h:.9,name:'แท่นวิหารเหนือ'},
 {x:3.0,z:-2.7,r:1.85,h:1.2,name:'แท่นหินใต้'}
];
const MUD=[{x:-4.4,z:-3.2,r:1.65},{x:4.7,z:3.4,r:1.5}];
const OBSTACLES=[
 {x:-1.1,z:-3.8,r:.72,name:'เสาหัก'}, {x:1.45,z:3.85,r:.72,name:'เสาหัก'},
 {x:-5.6,z:1.8,r:.8,name:'กองหิน'}, {x:5.6,z:-1.6,r:.8,name:'กองหิน'}
];

function actor(name,side,cfg){const start=side==='p'?-5.3:5.3;return{name,side,maxHP:cfg.hp,hp:cfg.hp,maxMP:cfg.mp,mp:cfg.mp,stamina:100,posture:100,atk:cfg.atk,def:cfg.def,mag:cfg.mag,mdef:cfg.mdef,spd:cfg.spd,accuracy:cfg.accuracy,evasion:cfg.evasion,crit:.12,critDmg:1.55,guarding:false,focusBuff:0,status:'READY',x:start,z:0,moveLeft:MOVE_BUDGET,model:null,reactionReady:true};}
let P=actor('อัศวินแห่งรุ่งอรุณ','p',{hp:980,mp:60,atk:108,def:104,mag:72,mdef:86,spd:92,accuracy:.92,evasion:.08});
let E=actor('ซามูไรเงา','e',{hp:900,mp:50,atk:112,def:92,mag:68,mdef:82,spd:104,accuracy:.9,evasion:.12});
let phase='PLAYER_COMMAND',busy=false,turn=1,moveMode=false,queue=[];

const scene=new THREE.Scene();scene.background=new THREE.Color(0x8da3a0);scene.fog=new THREE.FogExp2(0x879994,.0105);
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;$('viewport').appendChild(renderer.domElement);
const camera=new THREE.OrthographicCamera(-14,14,9,-9,.1,120);camera.position.set(17,19,17);camera.lookAt(0,0,0);scene.add(camera);
scene.add(new THREE.HemisphereLight(0xddeecb,0x334232,2.25));const sun=new THREE.DirectionalLight(0xffe6bc,3.7);sun.position.set(-10,18,11);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-16;sun.shadow.camera.right=16;sun.shadow.camera.top=16;sun.shadow.camera.bottom=-16;scene.add(sun);const fill=new THREE.DirectionalLight(0x9cbfff,.65);fill.position.set(10,8,-10);scene.add(fill);
const MAT={grass:new THREE.MeshStandardMaterial({color:0x526c45,roughness:1}),grass2:new THREE.MeshStandardMaterial({color:0x3f5738,roughness:1}),mud:new THREE.MeshStandardMaterial({color:0x5a4935,roughness:1}),stone:new THREE.MeshStandardMaterial({color:0x73766c,roughness:.94}),stone2:new THREE.MeshStandardMaterial({color:0x50554f,roughness:.96}),rune:new THREE.MeshBasicMaterial({color:0x68d7d0,transparent:true,opacity:.64,side:THREE.DoubleSide}),dark:new THREE.MeshStandardMaterial({color:0x1e1916,roughness:.9}),blue:new THREE.MeshStandardMaterial({color:0x285c91}),red:new THREE.MeshStandardMaterial({color:0x8a2b20}),steel:new THREE.MeshStandardMaterial({color:0xa4a8ad,metalness:.72,roughness:.35}),skin:new THREE.MeshStandardMaterial({color:0xc08b65})};
function addMesh(g,m,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o;}
const walkSurfaces=[];
function buildArena(){
 addMesh(new THREE.CylinderGeometry(10.6,10.6,.55,72),MAT.stone2,0,-.42,0);addMesh(new THREE.CylinderGeometry(9.65,9.65,.28,72),MAT.grass2,0,-.10,0);addMesh(new THREE.CylinderGeometry(8.95,8.95,.16,72),MAT.grass,0,.02,0);
 for(let i=-6;i<=6;i++){const s=addMesh(new THREE.BoxGeometry(1.05,.035,.72),i%2?MAT.stone:MAT.stone2,i*1.12,.13,0);s.rotation.y=(i%3-1)*.035;}for(let i=-5;i<=5;i++){const s=addMesh(new THREE.BoxGeometry(.72,.035,1.02),i%2?MAT.stone2:MAT.stone,0,.132,i*1.15);s.rotation.y=(i%3-1)*.04;}
 for(const m of MUD)addMesh(new THREE.CylinderGeometry(m.r,m.r,.035,40),MAT.mud,m.x,.145,m.z);
 for(const p of PLATFORMS){addMesh(new THREE.CylinderGeometry(p.r,p.r,.42+p.h,48),MAT.stone2,p.x,(p.h-.22)/2,p.z);addMesh(new THREE.CylinderGeometry(p.r-.12,p.r-.12,.13,48),MAT.grass,p.x,p.h+.07,p.z);const surf=new THREE.Mesh(new THREE.CircleGeometry(p.r-.08,48),new THREE.MeshBasicMaterial({transparent:true,opacity:0,side:THREE.DoubleSide}));surf.rotation.x=-Math.PI/2;surf.position.set(p.x,p.h+.15,p.z);scene.add(surf);walkSurfaces.push(surf);}
 for(const r of [1.15,1.9,2.45]){const ring=addMesh(new THREE.TorusGeometry(r,.035,8,96),MAT.rune,0,.17,0);ring.rotation.x=Math.PI/2;}
 for(const o of OBSTACLES){addMesh(new THREE.CylinderGeometry(o.r*.55,o.r*.7,1.55,9),MAT.stone,o.x,.78,o.z);addMesh(new THREE.CylinderGeometry(o.r*.75,o.r*.82,.22,9),MAT.stone2,o.x,.11,o.z);}
}
buildArena();
const ground=new THREE.Mesh(new THREE.CircleGeometry(ARENA_R,72),new THREE.MeshBasicMaterial({transparent:true,opacity:0,side:THREE.DoubleSide}));ground.rotation.x=-Math.PI/2;ground.position.y=.20;scene.add(ground);walkSurfaces.push(ground);
const edgeGuide=addMesh(new THREE.RingGeometry(ARENA_R-.07,ARENA_R,96),new THREE.MeshBasicMaterial({color:0xd9efb4,transparent:true,opacity:.18,side:THREE.DoubleSide}),0,.19,0);edgeGuide.rotation.x=-Math.PI/2;
const moveRing=addMesh(new THREE.RingGeometry(MOVE_BUDGET-.045,MOVE_BUDGET,72),new THREE.MeshBasicMaterial({color:0x6fd9ff,transparent:true,opacity:.32,side:THREE.DoubleSide}),0,.22,0);moveRing.rotation.x=-Math.PI/2;moveRing.visible=false;

function heightAt(x,z){for(const p of PLATFORMS)if(Math.hypot(x-p.x,z-p.z)<=p.r-.08)return p.h;return 0;}
function terrainAt(x,z){for(const m of MUD)if(Math.hypot(x-m.x,z-m.z)<=m.r)return{name:'โคลน',cost:1.55};if(Math.abs(z)<.62||Math.abs(x)<.58)return{name:'ทางหิน',cost:.82};if(Math.hypot(x,z)<2.5)return{name:'วงเวท',cost:1.08};for(const p of PLATFORMS)if(Math.hypot(x-p.x,z-p.z)<=p.r)return{name:p.name,cost:1.12};return{name:'หญ้า',cost:1};}
function blockedPoint(x,z,other){if(Math.hypot(x,z)>ARENA_R)return true;if(other&&Math.hypot(x-other.x,z-other.z)<DUEL_MIN)return true;return OBSTACLES.some(o=>Math.hypot(x-o.x,z-o.z)<o.r+.35);}
function pathBlocked(x0,z0,x1,z1,other){for(let i=1;i<=18;i++){const t=i/18,x=x0+(x1-x0)*t,z=z0+(z1-z0)*t;if(blockedPoint(x,z,other))return true;}return false;}
function moveCost(x0,z0,x1,z1){const d=Math.hypot(x1-x0,z1-z0);if(d<.001)return{cost:0,kind:'walk',dh:0};let terrain=0;for(let i=1;i<=12;i++){const t=i/12;terrain+=terrainAt(x0+(x1-x0)*t,z0+(z1-z0)*t).cost;}terrain/=12;const dh=heightAt(x1,z1)-heightAt(x0,z0);if(Math.abs(dh)>MAX_JUMP)return{cost:Infinity,kind:'blocked-height',dh};const jump=Math.abs(dh)>.34;return{cost:d*terrain+(dh>0?dh*.85:Math.abs(dh)*.28)+(jump?(dh>0?.7:.28):0),kind:jump?(dh>0?'jump':'drop'):'walk',dh};}
function reachableTarget(a,x,z,limit){let lo=0,hi=1,best={x:a.x,z:a.z};const other=a===P?E:P;for(let k=0;k<18;k++){const t=(lo+hi)/2,tx=a.x+(x-a.x)*t,tz=a.z+(z-a.z)*t,c=moveCost(a.x,a.z,tx,tz);if(!pathBlocked(a.x,a.z,tx,tz,other)&&c.cost<=limit){lo=t;best={x:tx,z:tz};}else hi=t;}return best;}
function crossesLeavingZOC(x0,z0,x1,z1,opp){let inside=Math.hypot(x0-opp.x,z0-opp.z)<=ZOC_RANGE,ever=inside;for(let i=1;i<=12;i++){const t=i/12,d=Math.hypot(x0+(x1-x0)*t-opp.x,z0+(z1-z0)*t-opp.z),now=d<=ZOC_RANGE;if(now)ever=true;if(ever&&!now&&i>1)return true;inside=now;}return false;}
function opportunityAttack(attacker,defender){if(!attacker.reactionReady||attacker.hp<=0||defender.hp<=0)return;attacker.reactionReady=false;const hit=rand()<clamp(.82+attacker.accuracy-.9-defender.evasion,.35,.96);if(!hit){log(`⚠ ${attacker.name} โจมตีสวนขณะ ${defender.name} ถอนตัว แต่พลาด`);return;}let dmg=46*(attacker.atk/(attacker.atk+defender.def*.7));if(attacker.guarding)dmg*=.85;defender.hp=clamp(defender.hp-dmg,0,defender.maxHP);defender.posture=clamp(defender.posture-10,0,100);log(`⚠ Attack of Opportunity: ${attacker.name} → ${Math.round(dmg)} ดาเมจ`);}

function fighterModel(a){const g=new THREE.Group(),body=a.side==='p'?MAT.blue:MAT.red;const torso=new THREE.Mesh(new THREE.CylinderGeometry(.28,.36,.82,8),body);torso.position.y=1;g.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.2,12,10),MAT.skin);head.position.y=1.58;g.add(head);const helmet=new THREE.Mesh(new THREE.ConeGeometry(.24,.28,8),MAT.steel);helmet.position.y=1.8;g.add(helmet);for(const x of [-.14,.14]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.09,.1,.62,7),MAT.dark);leg.position.set(x,.34,0);g.add(leg);}const swordArm=new THREE.Group();const arm=new THREE.Mesh(new THREE.CylinderGeometry(.075,.09,.6,7),MAT.steel);arm.position.y=-.27;swordArm.add(arm);const sword=new THREE.Mesh(new THREE.BoxGeometry(.055,.86,.035),MAT.steel);sword.position.set(0,-.78,0);swordArm.add(sword);swordArm.position.set(a.side==='p'?.34:-.34,1.3,0);swordArm.rotation.z=a.side==='p'?-1:1;g.add(swordArm);const select=new THREE.Mesh(new THREE.RingGeometry(.43,.48,32),new THREE.MeshBasicMaterial({color:a.side==='p'?0x49bfff:0xff5a50,side:THREE.DoubleSide}));select.rotation.x=-Math.PI/2;select.position.y=.025;g.add(select);const zoc=new THREE.Mesh(new THREE.RingGeometry(ZOC_RANGE-.035,ZOC_RANGE,64),new THREE.MeshBasicMaterial({color:a.side==='p'?0x61c9ff:0xff7168,transparent:true,opacity:.28,side:THREE.DoubleSide}));zoc.rotation.x=-Math.PI/2;zoc.position.y=.03;zoc.visible=false;g.add(zoc);g.userData={swordArm,base:swordArm.rotation.z,zoc};g.traverse(c=>{if(c.isMesh)c.castShadow=c.receiveShadow=true});scene.add(g);return g;}
P.model=fighterModel(P);E.model=fighterModel(E);
function syncActor(a){a.model.position.set(a.x,.20+heightAt(a.x,a.z),a.z);const other=a===P?E:P;a.model.rotation.y=Math.atan2(other.x-a.x,other.z-a.z);}
syncActor(P);syncActor(E);
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}

function moveActor(a,x,z,limit=a.moveLeft){const other=a===P?E:P;if(pathBlocked(a.x,a.z,x,z,other)){log(`${a.name}: เส้นทางถูกสิ่งกีดขวาง`);return 0;}const target=reachableTarget(a,x,z,limit),c=moveCost(a.x,a.z,target.x,target.z);if(!Number.isFinite(c.cost)||c.cost<=.001)return 0;const leaveZOC=crossesLeavingZOC(a.x,a.z,target.x,target.z,other);a.x=target.x;a.z=target.z;a.moveLeft=clamp(a.moveLeft-c.cost,0,MOVE_BUDGET);if(c.kind==='jump')log(`${a.name} กระโดดขึ้นพื้นที่สูง (+${c.dh.toFixed(1)}m)`);if(c.kind==='drop')log(`${a.name} กระโดดลง (${c.dh.toFixed(1)}m)`);if(leaveZOC)opportunityAttack(other,a);syncActor(a);return c.cost;}
function stepPlayer(dx,dz){if(!moveMode||busy||phase!=='PLAYER_COMMAND')return;const len=Math.hypot(dx,dz)||1;if(P.moveLeft<=.02)return;moveActor(P,P.x+dx/len*STEP,P.z+dz/len*STEP,Math.min(P.moveLeft,STEP*1.8));updateMoveUI();renderHUD();}

function log(t){const d=document.createElement('div');d.className='entry';d.textContent=t;$('log').prepend(d);}
function pct(v,max){return `${clamp(v/max*100,0,100)}%`;}
function renderHUD(){for(const[a,p]of[[P,'p'],[E,'e']]){$(p+'HP').textContent=`${Math.round(a.hp)}/${a.maxHP}`;$(p+'MP').textContent=`${Math.round(a.mp)}/${a.maxMP}`;$(p+'ST').textContent=`${Math.round(a.stamina)}/100`;$(p+'PO').textContent=`${Math.round(a.posture)}/100`;$(p+'HPBar').style.width=pct(a.hp,a.maxHP);$(p+'MPBar').style.width=pct(a.mp,a.maxMP);$(p+'STBar').style.width=pct(a.stamina,100);$(p+'POBar').style.width=pct(a.posture,100)}const terr=terrainAt(P.x,P.z),h=heightAt(P.x,P.z);$('playerState').textContent=`${P.guarding?'กำลังป้องกัน':P.status} · Move ${P.moveLeft.toFixed(1)} · ${terr.name} · สูง ${h.toFixed(1)}m`;$('enemyState').textContent=`${E.guarding?'กำลังป้องกัน':E.status} · สูง ${heightAt(E.x,E.z).toFixed(1)}m`;$('turnBadge').textContent=phase==='PLAYER_COMMAND'?`เทิร์น ${turn} · ${moveMode?'เลือกตำแหน่ง':'เลือกคำสั่ง'}`:`เทิร์น ${turn} · กำลังดำเนินการ`;document.querySelectorAll('.commands button').forEach(b=>b.disabled=busy||phase!=='PLAYER_COMMAND');}

function injectMovementUI(){const commands=document.querySelector('.commands');const b=document.createElement('button');b.dataset.cmd='move';b.textContent='เคลื่อนที่';commands.prepend(b);b.onclick=()=>showSub('move');const panel=document.createElement('div');panel.id='movePanel';panel.className='panel';panel.style.marginTop='8px';panel.innerHTML='<b>การเคลื่อนที่เชิงยุทธวิธี</b><div class="muted" id="moveInfo" style="margin:4px 0 8px"></div><div style="display:grid;grid-template-columns:repeat(3,52px);gap:6px;justify-content:center"><span></span><button type="button" data-dir="0,-1">▲</button><span></span><button type="button" data-dir="-1,0">◀</button><button type="button" id="moveDone">✓</button><button type="button" data-dir="1,0">▶</button><span></span><button type="button" data-dir="0,1">▼</button><span></span></div><small class="muted">ทางหินถูกกว่า · โคลนแพงกว่า · ถอนตัวออกจากวงแดงเสี่ยง Attack of Opportunity</small>';document.querySelector('.commandWrap').after(panel);panel.querySelectorAll('button').forEach(x=>{x.style.minHeight='46px';x.style.borderRadius='10px';x.style.border='1px solid #806344';x.style.background='#332216';x.style.color='#fff';x.style.fontWeight='900'});panel.querySelectorAll('[data-dir]').forEach(x=>x.onclick=()=>{const[dx,dz]=x.dataset.dir.split(',').map(Number);stepPlayer(dx,dz)});$('moveDone').onclick=()=>setMoveMode(false);panel.style.display='none';}
function updateMoveUI(){const p=$('movePanel');if(!p)return;p.style.display=moveMode?'block':'none';const terr=terrainAt(P.x,P.z);$('moveInfo').textContent=`เหลือ ${P.moveLeft.toFixed(1)} MP · ${terr.name} x${terr.cost.toFixed(2)} · ระยะศัตรู ${dist(P,E).toFixed(1)}m`;moveRing.visible=moveMode;moveRing.position.set(P.x,.23+heightAt(P.x,P.z),P.z);moveRing.scale.setScalar(Math.max(.05,P.moveLeft/MOVE_BUDGET));P.model.userData.zoc.visible=moveMode;E.model.userData.zoc.visible=moveMode;}
function setMoveMode(v){moveMode=v&&!busy&&phase==='PLAYER_COMMAND'&&P.moveLeft>.01;updateMoveUI();renderHUD();}

function optionsFor(cmd){if(cmd==='move')return[{label:'เข้าสู่โหมดเคลื่อนที่',desc:'แตะพื้นหรือใช้ปุ่มทิศทาง · Terrain / Height / ZoC มีผล',action:{type:'move'}}];if(cmd==='attack')return[{label:'ฟันเร็ว',desc:'ระยะ 1.75m',action:{type:'skill',skill:'quick'}},{label:'ฟันหนัก',desc:'ระยะ 2.05m',action:{type:'skill',skill:'heavy'}},{label:'ทำลายการ์ด',desc:'ระยะ 1.65m',action:{type:'skill',skill:'break'}}];if(cmd==='skill')return[{label:'คมดาบเพลิง',desc:'MP14 · ระยะ 3.8m',action:{type:'skill',skill:'flame'}},{label:'ตั้งสมาธิ',desc:'เพิ่มความแม่น',action:{type:'skill',skill:'focus'}}];if(cmd==='guard')return[{label:'Guard',desc:'ลดดาเมจ + ฟื้น Posture',action:{type:'guard'}}];if(cmd==='item')return[{label:'Potion',desc:'ฟื้น HP 180',action:{type:'item'}}];if(cmd==='tactic')return[{label:'ตั้งรับ',desc:'Guard + ฟื้น Stamina',action:{type:'tactic',mode:'defensive'}}];return[{label:'รอจังหวะ',desc:'ฟื้นทรัพยากร',action:{type:'wait'}}];}
function showSub(cmd){document.querySelectorAll('.commands button').forEach(b=>b.classList.toggle('active',b.dataset.cmd===cmd));$('subCommands').innerHTML='';for(const o of optionsFor(cmd)){const b=document.createElement('button');b.innerHTML=`${o.label}<small>${o.desc}</small>`;b.onclick=()=>o.action.type==='move'?setMoveMode(true):commitPlayer(o.action);$('subCommands').appendChild(b);}}
document.querySelectorAll('.commands button').forEach(b=>b.onclick=()=>showSub(b.dataset.cmd));

const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();renderer.domElement.addEventListener('pointerdown',ev=>{if(!moveMode||busy)return;const r=renderer.domElement.getBoundingClientRect();pointer.x=(ev.clientX-r.left)/r.width*2-1;pointer.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(walkSurfaces,false)[0];if(hit){moveActor(P,hit.point.x,hit.point.z);updateMoveUI();renderHUD();}});

function enemyChoice(){if(E.hp/E.maxHP<.28&&rand()<.35)return{type:'guard'};const d=dist(E,P);if(d>3.4&&E.mp>=14)return{type:'skill',skill:'flame'};const r=rand();return r<.3?{type:'skill',skill:'break'}:r<.65?{type:'skill',skill:'quick'}:{type:'skill',skill:'heavy'};}
function actionSpeed(a,act){let s=a.spd;if(act.type==='guard')s+=25;if(act.type==='skill'&&act.skill==='quick')s+=15;if(act.type==='skill'&&act.skill==='heavy')s-=12;return s;}
function enemyRepositionFor(act){if(act.type!=='skill')return;const sk=SKILLS[act.skill];if(sk.kind==='buff'||dist(E,P)<=sk.range)return;let best=null;for(let i=0;i<20;i++){const a=i/20*Math.PI*2,r=Math.max(DUEL_MIN+.15,sk.range*.78),x=P.x+Math.cos(a)*r,z=P.z+Math.sin(a)*r;if(blockedPoint(x,z,P)||pathBlocked(E.x,E.z,x,z,P))continue;const c=moveCost(E.x,E.z,x,z);if(c.cost>Math.min(E.moveLeft,3.1))continue;const score=heightAt(x,z)*1.4-c.cost*.18-(crossesLeavingZOC(E.x,E.z,x,z,P)?.8:0);if(!best||score>best.score)best={x,z,score};}if(best)moveActor(E,best.x,best.z,Math.min(E.moveLeft,3.1));}
function commitPlayer(action){if(busy||phase!=='PLAYER_COMMAND')return;setMoveMode(false);if(action.type==='skill'){const s=SKILLS[action.skill];if(s.kind!=='buff'&&dist(P,E)>s.range){log(`อยู่นอกระยะ ${s.label} (${dist(P,E).toFixed(1)}m > ${s.range}m)`);showSub(action.skill==='flame'?'skill':'attack');return;}}busy=true;phase='RESOLVE';const enemy=enemyChoice();enemyRepositionFor(enemy);queue=[{actor:P,target:E,action,initiative:actionSpeed(P,action)+rand()*8},{actor:E,target:P,action:enemy,initiative:actionSpeed(E,enemy)+rand()*8}].sort((a,b)=>b.initiative-a.initiative);renderHUD();$('subCommands').innerHTML='';resolveQueue();}

function resolveSkill(attacker,defender,key){const s=SKILLS[key];if(s.kind!=='buff'&&dist(attacker,defender)>s.range)return{hit:false,outOfRange:true};if(attacker.mp<s.mp||attacker.stamina<s.st)return{hit:false,noResource:true};attacker.mp-=s.mp;attacker.stamina-=s.st;if(s.kind==='buff'){attacker.focusBuff=2;return{hit:true,buff:true};}const hd=heightAt(attacker.x,attacker.z)-heightAt(defender.x,defender.z),high=hd>.4?1:hd<-.4?-1:0;const hitChance=clamp(s.accuracy+attacker.accuracy-.9-defender.evasion+(attacker.focusBuff>0?.08:0)+high*.055,.15,.99);if(rand()>hitChance)return{hit:false};const atk=s.kind==='magic'?attacker.mag:attacker.atk,def=s.kind==='magic'?defender.mdef:defender.def;let damage=s.power*(atk/(atk+def*.75));const flank=positionBonus(attacker,defender);damage*=flank.mult*(high>0?1.12:high<0?.93:1);let crit=false;if(rand()<attacker.crit){damage*=attacker.critDmg;crit=true;}if(defender.guarding)damage*=.42;defender.hp=clamp(defender.hp-damage,0,defender.maxHP);defender.posture=clamp(defender.posture-s.posture*(defender.guarding?1.45:1),0,100);return{hit:true,damage,crit,flank:flank.label,high,anim:s.anim};}
function positionBonus(a,d){const facing=new THREE.Vector2(a.x-d.x,a.z-d.z).normalize(),home=new THREE.Vector2(d.side==='p'?-1:1,0),dot=facing.dot(home);if(dot<-.45)return{mult:1.22,label:'BACK'};if(Math.abs(dot)<.35)return{mult:1.1,label:'SIDE'};return{mult:1,label:'FRONT'};}
function applyAction(a,d,act){a.guarding=false;if(act.type==='guard'){a.guarding=true;a.posture=clamp(a.posture+16,0,100);return{type:'guard'};}if(act.type==='wait'){a.stamina=clamp(a.stamina+24,0,100);a.mp=clamp(a.mp+5,0,a.maxMP);return{type:'wait'};}if(act.type==='item'){a.hp=clamp(a.hp+180,0,a.maxHP);return{type:'item'};}if(act.type==='tactic'){a.guarding=true;a.stamina=clamp(a.stamina+12,0,100);return{type:'tactic'};}return{type:'skill',skill:act.skill,...resolveSkill(a,d,act.skill)};}
function tween(ms,fn){return new Promise(res=>{const st=performance.now();function f(t){const p=clamp((t-st)/ms,0,1);fn(p);p<1?requestAnimationFrame(f):res();}requestAnimationFrame(f);});}
async function present(a,d,act,r){if(act.type!=='skill'||SKILLS[act.skill].kind==='buff'){await tween(220,p=>a.model.scale.setScalar(1+Math.sin(p*Math.PI)*.06));a.model.scale.setScalar(1);return;}const sk=SKILLS[act.skill],m=a.model,home=new THREE.Vector3(a.x,.20+heightAt(a.x,a.z),a.z),target=new THREE.Vector3(d.x,.20+heightAt(d.x,d.z),d.z),dir=target.clone().sub(home);dir.y=0;dir.normalize();const attackPos=target.clone().addScaledVector(dir,-Math.min(sk.range*.72,1.25));attackPos.y=home.y;await tween(220,p=>m.position.lerpVectors(home,attackPos,p));const arm=m.userData.swordArm,base=m.userData.base;await tween(sk.anim==='heavy'?320:210,p=>arm.rotation.z=base+(a.side==='p'?1:-1)*Math.sin(p*Math.PI)*1.8);if(r.hit&&!r.buff){d.model.scale.setScalar(.9);setTimeout(()=>d.model.scale.setScalar(1),110);}await tween(240,p=>m.position.lerpVectors(attackPos,home,p));arm.rotation.z=base;syncActor(a);}
async function resolveQueue(){for(const q of queue){if(q.actor.hp<=0||q.target.hp<=0)continue;const r=applyAction(q.actor,q.target,q.action);if(r.outOfRange)log(`${q.actor.name} โจมตีไม่ถึง`);else if(r.noResource)log(`${q.actor.name} ทรัพยากรไม่พอ`);else if(r.type==='skill'){const s=SKILLS[q.action.skill],pos=r.flank&&r.flank!=='FRONT'?` · ${r.flank}`:'',high=r.high>0?' · HIGH GROUND':r.high<0?' · LOW GROUND':'';log(`${q.actor.name} ใช้ ${s.label}${r.hit?` → ${Math.round(r.damage||0)}${pos}${high}${r.crit?' CRIT':''}`:' → MISS'}`);}else log(`${q.actor.name} ใช้ ${r.type}`);await present(q.actor,q.target,q.action,r);renderHUD();if(P.hp<=0||E.hp<=0)break;}if(P.hp<=0||E.hp<=0){busy=true;phase='END';$('result').textContent=`ผู้ชนะ: ${P.hp>E.hp?P.name:E.name}`;renderHUD();return;}turn++;P.moveLeft=MOVE_BUDGET;E.moveLeft=MOVE_BUDGET;P.reactionReady=E.reactionReady=true;P.stamina=clamp(P.stamina+7,0,100);E.stamina=clamp(E.stamina+7,0,100);busy=false;phase='PLAYER_COMMAND';renderHUD();updateMoveUI();}

injectMovementUI();renderHUD();updateMoveUI();log('Movement v3: Height · Terrain Cost · Obstacles · Jump/Drop · Zone of Control · Attack of Opportunity');
function resize(){const el=$('viewport'),w=el.clientWidth,h=Math.max(380,Math.min(700,w*.64));renderer.setSize(w,h,false);const aspect=w/h,f=16.5;camera.left=-f*aspect/2;camera.right=f*aspect/2;camera.top=f/2;camera.bottom=-f/2;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('viewport'));resize();
function frame(){syncActor(P);syncActor(E);renderer.render(scene,camera);requestAnimationFrame(frame);}requestAnimationFrame(frame);
