import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';
import {rollback} from '../../src/twa-history.js';
const $=id=>document.getElementById(id),SIZE=10,board=$('board'),ctx=board.getContext('2d'),cell=()=>board.width/SIZE;
const staticUnits=[
{id:0,name:'Vanguard',cls:'Vanguard',team:0,gx:1,gy:7,hp:130,atk:34,def:22,mov:4,range:1,skill:'Shield Bash'},
{id:1,name:'Assault',cls:'Assault',team:0,gx:2,gy:8,hp:100,atk:42,def:14,mov:5,range:1,skill:'Power Strike'},
{id:2,name:'Ranger',cls:'Ranger',team:0,gx:0,gy:8,hp:82,atk:38,def:10,mov:4,range:4,skill:'Precision Shot'},
{id:3,name:'Support',cls:'Support',team:0,gx:1,gy:9,hp:92,atk:24,def:14,mov:4,range:2,skill:'Field Heal'},
{id:4,name:'Raider A',cls:'Enemy',team:1,gx:7,gy:1,hp:90,atk:31,def:12,mov:4,range:1},{id:5,name:'Raider B',cls:'Enemy',team:1,gx:8,gy:2,hp:90,atk:31,def:12,mov:4,range:1},{id:6,name:'Raider C',cls:'Enemy',team:1,gx:6,gy:2,hp:90,atk:31,def:12,mov:4,range:1},{id:7,name:'Sniper A',cls:'Enemy Ranger',team:1,gx:8,gy:0,hp:72,atk:34,def:9,mov:3,range:4},{id:8,name:'Sniper B',cls:'Enemy Ranger',team:1,gx:9,gy:1,hp:72,atk:34,def:9,mov:3,range:4},{id:9,name:'Heavy',cls:'Enemy Heavy',team:1,gx:7,gy:0,hp:125,atk:44,def:20,mov:2,range:3},{id:10,name:'Command Core',cls:'Objective',team:1,gx:8,gy:4,hp:180,atk:0,def:18,mov:0,range:0,core:true}];
const baseTerrain=[['4,4','wall'],['4,5','wall'],['5,4','wall'],['5,5','wall'],['2,4','forest'],['2,5','forest'],['7,5','forest'],['8,5','forest'],['5,1','high'],['6,1','high'],['3,7','high'],['6,6','fire']];
const baseDestructibles=[{id:'barrel-a',x:5,y:6,type:'barrel',hp:1},{id:'barrel-b',x:7,y:3,type:'barrel',hp:1}];
let terrain,destructibles,world,units,turn,phase,selected,mode,chrono,timeline,statuses,turnState,actionFrames,playerLosses;
const gxToX=g=>-0.9+g*.2,gyToY=g=>-0.9+g*.2,xToG=x=>Math.round((x+.9)/.2),yToG=y=>Math.round((y+.9)/.2),tile=(x,y)=>terrain.get(`${x},${y}`)||'plain';
const alive=u=>world.active[u.id]&&world.hp[u.id]>0,ux=u=>xToG(world.x[u.id]),uy=u=>yToG(world.y[u.id]),dist=(a,b)=>Math.abs(ux(a)-ux(b))+Math.abs(uy(a)-uy(b));
const unitAt=(x,y)=>units.find(u=>alive(u)&&ux(u)===x&&uy(u)===y),destructibleAt=(x,y)=>destructibles.find(d=>d.hp>0&&d.x===x&&d.y===y);
const canStand=(x,y)=>x>=0&&y>=0&&x<SIZE&&y<SIZE&&tile(x,y)!=='wall'&&!unitAt(x,y)&&!destructibleAt(x,y);
const st=u=>statuses.get(u.id)||[],hasStatus=(u,t)=>st(u).some(s=>s.type===t&&s.turns>0),coverBonus=u=>tile(ux(u),uy(u))==='forest'?8:0,highBonus=u=>tile(ux(u),uy(u))==='high'?8:0,atkBonus=u=>st(u).filter(s=>s.type==='atk').reduce((n,s)=>n+s.amount,0),defBonus=u=>st(u).filter(s=>s.type==='def'||s.type==='guard').reduce((n,s)=>n+s.amount,0);
const stateFor=u=>turnState.get(u.id)||{moved:false,acted:false};function setState(u,p){turnState.set(u.id,{...stateFor(u),...p})}
function cloneStatuses(){return new Map([...statuses].map(([k,v])=>[k,v.map(x=>({...x}))]))}function cloneDest(){return destructibles.map(x=>({...x}))}
function captureFrame(label){return{label,deltaLen:world.deltaLog.length,turn,phase,chrono,selectedId:selected?.id??null,mode,turnState:new Map([...turnState].map(([k,v])=>[k,{...v}])),statuses:cloneStatuses(),timelineLen:timeline.length,playerLosses,terrain:new Map(terrain),destructibles:cloneDest()}}
function pushFrame(label){actionFrames.push(captureFrame(label));if(actionFrames.length>240)actionFrames.shift()}
function restoreFrame(f){turn=f.turn;phase=f.phase;mode=f.mode;turnState=new Map([...f.turnState].map(([k,v])=>[k,{...v}]));statuses=new Map([...f.statuses].map(([k,v])=>[k,v.map(x=>({...x}))]));timeline.length=f.timelineLen;playerLosses=f.playerLosses;terrain=new Map(f.terrain);destructibles=f.destructibles.map(x=>({...x}));selected=f.selectedId==null?null:units.find(u=>u.id===f.selectedId)||null}
function reset(){terrain=new Map(baseTerrain);destructibles=baseDestructibles.map(x=>({...x}));world=createWorld({seed:42,count:staticUnits.length,density:0,speed:0});units=staticUnits.map(u=>({...u}));for(const u of units){world.team[u.id]=u.team;world.x[u.id]=gxToX(u.gx);world.y[u.id]=gyToY(u.gy);world.vx[u.id]=world.vy[u.id]=0;world.hp[u.id]=u.hp;world.radius[u.id]=u.core?.045:.03;world.type[u.id]=u.team===0?1:2}turn=1;phase='PLAYER';selected=null;mode='move';chrono=3;timeline=[];statuses=new Map();turnState=new Map();actionFrames=[];playerLosses=0;units.forEach(u=>statuses.set(u.id,[]));record('MISSION','Operation Broken Shield: ทำลาย Command Core','ok');draw()}
function record(type,text,cls='',meta={}){timeline.push({type,text,cls,turn,phase,worldVersion:world.worldVersion,hash:stateHash(world),...meta});renderTimeline()}
function transaction(p,label,type='ACTION',meta={}){const r=resolveConflicts([p]),v=verify(world,r,{critical:false});if(!v.ok){record('BLOCKED',v.errors.join(', '),'enemy');return false}const c=commit(world,r,{verifierResult:v});record(type,label,phase==='PLAYER'?'player':'enemy',{commit:c.worldVersion,...meta});return true}
function addStatus(u,type,turns,amount=0,source=null){statuses.set(u.id,[...st(u).filter(s=>s.type!==type),{type,turns,amount,source}]);record('STATUS',`${u.name}: ${type.toUpperCase()} ${turns} เทิร์น`,'warn')}
function cleanDead(){for(const u of units)if(world.hp[u.id]<=0&&world.active[u.id]){world.hp[u.id]=0;world.active[u.id]=0;if(u.team===0)playerLosses++;record('DEFEAT',`${u.name} ถูกกำจัด`,'enemy')}}
function moveUnit(u,x,y,{consume=true,frame=true}={}){if(!alive(u)||u.core||hasStatus(u,'stun')||(consume&&stateFor(u).moved))return false;const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))return false;if(frame)pushFrame(`${u.name} move`);const s=snapshot(world),p=makeProposal({snapshot:s,systemId:'ironfront.move',source:`unit:${u.id}`,priority:240,writes:[{entity:u.id,field:'x',value:gxToX(x),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]},{entity:u.id,field:'y',value:gyToY(y),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]}],events:[{type:'move',entity:u.id,gx:x,gy:y}],meta:{authority:true}});const ok=transaction(p,`${u.name} เดินไป (${x},${y})`,'MOVE');if(ok&&consume){setState(u,{moved:true});selected=u;mode='attack';if(tile(x,y)==='fire')addStatus(u,'burn',2,8,'terrain')}return ok}
function damageValue(a,b,p=0,ignoreCover=false){return Math.max(1,a.atk+atkBonus(a)+p+highBonus(a)-b.def-defBonus(b)-(ignoreCover?0:coverBonus(b)))}
function hpProposal(t,d,systemId,source,event){const s=snapshot(world);return makeProposal({snapshot:s,systemId,source,priority:270,writes:[{entity:t.id,field:'hp',op:'add',value:d,expectedVersion:s.version[t.id],expectedGeneration:s.generation[t.id]}],events:[event],meta:{authority:true}})}
function explode(d){if(!d||d.hp<=0)return;d.hp=0;terrain.set(`${d.x},${d.y}`,'fire');record('EXPLOSION',`ถังระเบิด (${d.x},${d.y}) ระเบิด!`,'warn');const victims=units.filter(u=>alive(u)&&Math.abs(ux(u)-d.x)+Math.abs(uy(u)-d.y)<=1);if(victims.length){const s=snapshot(world),writes=victims.map(u=>({entity:u.id,field:'hp',op:'add',value:-28,expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]}));const p=makeProposal({snapshot:s,systemId:'ironfront.explosion',source:d.id,priority:300,writes,events:victims.map(u=>({type:'explosion',target:u.id,damage:28})),meta:{authority:true}});transaction(p,`Explosion damage ${victims.length} เป้าหมาย`,'EXPLOSION');victims.forEach(u=>addStatus(u,'burn',2,8,d.id));cleanDead()}}
function attackUnit(a,b,{consume=true,frame=true}={}){if(!alive(a)||!alive(b)||a.team===b.team||a.core||hasStatus(a,'stun')||(consume&&stateFor(a).acted)||dist(a,b)>a.range)return false;if(frame)pushFrame(`${a.name} attack`);const dmg=damageValue(a,b),ok=transaction(hpProposal(b,-dmg,'ironfront.attack',`unit:${a.id}`,{type:'attack',source:a.id,target:b.id,damage:dmg}),`${a.name} โจมตี ${b.name} -${dmg} HP`,'ATTACK');if(ok&&consume){setState(a,{acted:true});selected=null}if(ok)cleanDead();return ok}
function attackBarrel(a,d){if(!selected||stateFor(a).acted||Math.abs(ux(a)-d.x)+Math.abs(uy(a)-d.y)>a.range)return false;pushFrame(`${a.name} barrel`);setState(a,{acted:true});selected=null;record('ATTACK',`${a.name} ยิงถังระเบิด`,'player');explode(d);return true}
function useSkill(a,b){if(!alive(a)||a.core||hasStatus(a,'stun')||stateFor(a).acted||!b)return false;pushFrame(`${a.name} skill`);let p,label,after=null;if(a.cls==='Support'){if(b.team!==a.team||dist(a,b)>2){actionFrames.pop();return false}const heal=Math.min(32,b.hp-world.hp[b.id]);if(heal<=0){actionFrames.pop();return false}p=hpProposal(b,heal,'ironfront.skill.heal',`unit:${a.id}`,{type:'heal',source:a.id,target:b.id,amount:heal});label=`${a.name} Field Heal → ${b.name} +${heal}`;after=()=>addStatus(b,'def',1,6,a.id)}else{if(b.team===a.team){actionFrames.pop();return false}const ranger=a.cls==='Ranger',range=ranger?5:a.range;if(dist(a,b)>range){actionFrames.pop();return false}const bonus=a.cls==='Vanguard'?14:a.cls==='Assault'?24:18,dmg=damageValue(a,b,bonus,ranger);p=hpProposal(b,-dmg,'ironfront.skill.attack',`unit:${a.id}`,{type:'skill',skill:a.skill,source:a.id,target:b.id,damage:dmg});label=`${a.name} ${a.skill} → ${b.name} -${dmg}`;if(a.cls==='Vanguard')after=()=>addStatus(b,'stun',1,0,a.id);if(a.cls==='Assault')after=()=>addStatus(b,'burn',2,8,a.id)}const ok=transaction(p,label,'SKILL',{skill:a.skill});if(ok){setState(a,{acted:true});selected=null;after?.();cleanDead()}else actionFrames.pop();return ok}
function guardSelected(){if(!selected||stateFor(selected).acted||hasStatus(selected,'stun'))return;pushFrame(`${selected.name} guard`);addStatus(selected,'guard',1,10,selected.id);setState(selected,{acted:true});record('GUARD',`${selected.name} ตั้งรับ +10 DEF`,'player');selected=null;draw()}
function aiScore(a,b){const d=damageValue(a,b);return d+(world.hp[b.id]<=d?120:0)+(tile(ux(a),uy(a))==='high'?10:0)}function bestMove(u,t){let best=null,score=-1e9;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))continue;const td=Math.abs(x-ux(t))+Math.abs(y-uy(t));let s=-td*10+(tile(x,y)==='forest'?16:0)+(tile(x,y)==='high'?20:0)-(tile(x,y)==='fire'?30:0)+(td<=u.range?30:0);if(s>score){score=s;best=[x,y]}}return best}
function processEnvironment(){pushFrame('environment');const s=snapshot(world),burn=units.filter(u=>alive(u)&&st(u).some(x=>x.type==='burn'));if(burn.length){const writes=burn.map(u=>{const x=st(u).find(s=>s.type==='burn');return{entity:u.id,field:'hp',op:'add',value:-x.amount,expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]}}),p=makeProposal({snapshot:s,systemId:'ironfront.environment',source:'environment',priority:280,writes,events:[],meta:{authority:true}});transaction(p,`Burn damage ${burn.length} เป้าหมาย`,'ENV')}else record('ENV','Environment Phase','ok');for(const u of units)statuses.set(u.id,st(u).map(x=>({...x,turns:x.turns-1})).filter(x=>x.turns>0));cleanDead()}
function enemyPhase(){phase='ENEMY';selected=null;turnState=new Map();draw();setTimeout(()=>{for(const u of units.filter(x=>alive(x)&&x.team===1&&!x.core)){if(hasStatus(u,'stun')){record('STUN',`${u.name} ถูก Stun`,'warn');continue}let ts=units.filter(x=>alive(x)&&x.team===0).sort((a,b)=>aiScore(u,b)-aiScore(u,a)||a.id-b.id),t=ts[0];if(!t)break;if(dist(u,t)>u.range){const m=bestMove(u,t);if(m)moveUnit(u,m[0],m[1],{consume:true,frame:true})}ts=units.filter(x=>alive(x)&&x.team===0&&dist(u,x)<=u.range).sort((a,b)=>aiScore(u,b)-aiScore(u,a)||