import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';
import {rollback} from '../../src/twa-history.js';

const $=id=>document.getElementById(id),SIZE=10,board=$('board'),ctx=board.getContext('2d'),cell=()=>board.width/SIZE;
const staticUnits=[
{id:0,name:'Vanguard',cls:'Vanguard',team:0,gx:1,gy:7,hp:130,atk:34,def:22,mov:4,range:1,skill:'Shield Bash'},
{id:1,name:'Assault',cls:'Assault',team:0,gx:2,gy:8,hp:100,atk:42,def:14,mov:5,range:1,skill:'Power Strike'},
{id:2,name:'Ranger',cls:'Ranger',team:0,gx:0,gy:8,hp:82,atk:38,def:10,mov:4,range:4,skill:'Precision Shot'},
{id:3,name:'Support',cls:'Support',team:0,gx:1,gy:9,hp:92,atk:24,def:14,mov:4,range:2,skill:'Field Heal'},
{id:4,name:'Raider A',cls:'Enemy',team:1,gx:7,gy:1,hp:90,atk:31,def:12,mov:4,range:1},
{id:5,name:'Raider B',cls:'Enemy',team:1,gx:8,gy:2,hp:90,atk:31,def:12,mov:4,range:1},
{id:6,name:'Raider C',cls:'Enemy',team:1,gx:6,gy:2,hp:90,atk:31,def:12,mov:4,range:1},
{id:7,name:'Sniper A',cls:'Enemy Ranger',team:1,gx:8,gy:0,hp:72,atk:34,def:9,mov:3,range:4},
{id:8,name:'Sniper B',cls:'Enemy Ranger',team:1,gx:9,gy:1,hp:72,atk:34,def:9,mov:3,range:4},
{id:9,name:'Heavy',cls:'Enemy Heavy',team:1,gx:7,gy:0,hp:125,atk:44,def:20,mov:2,range:3}
];
const terrain=new Map([
['4,4','wall'],['4,5','wall'],['5,4','wall'],
['2,4','forest'],['2,5','forest'],['7,5','forest'],['8,5','forest'],
['5,1','high'],['6,1','high'],['3,7','high']
]);
let world,units,turn,phase,selected,mode,acted,chrono,timeline;
const gxToX=g=>-0.9+g*0.2,gyToY=g=>-0.9+g*0.2,xToG=x=>Math.round((x+0.9)/0.2),yToG=y=>Math.round((y+0.9)/0.2);
const tile=(x,y)=>terrain.get(`${x},${y}`)||'plain';
const alive=u=>world.active[u.id]&&world.hp[u.id]>0;
const ux=u=>xToG(world.x[u.id]),uy=u=>yToG(world.y[u.id]);
const dist=(a,b)=>Math.abs(ux(a)-ux(b))+Math.abs(uy(a)-uy(b));
const unitAt=(x,y)=>units.find(u=>alive(u)&&ux(u)===x&&uy(u)===y);
const canStand=(x,y)=>x>=0&&y>=0&&x<SIZE&&y<SIZE&&tile(x,y)!=='wall'&&!unitAt(x,y);
const coverBonus=u=>tile(ux(u),uy(u))==='forest'?8:0;
const highBonus=u=>tile(ux(u),uy(u))==='high'?8:0;
function reset(){world=createWorld({seed:42,count:staticUnits.length,density:0,speed:0});units=staticUnits.map(u=>({...u}));for(const u of units){world.team[u.id]=u.team;world.x[u.id]=gxToX(u.gx);world.y[u.id]=gyToY(u.gy);world.vx[u.id]=0;world.vy[u.id]=0;world.hp[u.id]=u.hp;world.radius[u.id]=.03;world.type[u.id]=u.team===0?1:2}turn=1;phase='PLAYER';selected=null;mode='move';acted=new Set();chrono=3;timeline=[];log('Mission เริ่ม: กำจัดศัตรูทั้งหมด','ok');draw()}
function transaction(p,label,meta={}){const resolved=resolveConflicts([p]),check=verify(world,resolved,{critical:false});if(!check.ok){log(`BLOCKED: ${check.errors.join(', ')}`,'enemy');return false}const rec=commit(world,resolved,{verifierResult:check});timeline.push({turn,phase,label,hash:stateHash(world),worldVersion:rec.worldVersion,...meta});log(label,phase==='PLAYER'?'player':'enemy');return true}
function moveUnit(u,x,y,consume=true){if(!alive(u)||(consume&&acted.has(u.id)))return false;const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))return false;const s=snapshot(world),p=makeProposal({snapshot:s,systemId:'ironfront.move',source:`unit:${u.id}`,priority:240,writes:[{entity:u.id,field:'x',value:gxToX(x),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]},{entity:u.id,field:'y',value:gyToY(y),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]}],events:[{type:'move',entity:u.id,gx:x,gy:y}],meta:{authority:true}});const ok=transaction(p,`${u.name} เดินไป (${x},${y})`);if(ok&&consume){acted.add(u.id);selected=null}return ok}
function damageValue(a,b,power=0){return Math.max(1,a.atk+power+highBonus(a)-b.def-coverBonus(b))}
function hpWrite(target,delta,systemId,source,event){const s=snapshot(world);return makeProposal({snapshot:s,systemId,source,priority:270,writes:[{entity:target.id,field:'hp',op:'add',value:delta,expectedVersion:s.version[target.id],expectedGeneration:s.generation[target.id]}],events:[event],meta:{authority:true}})}
function attackUnit(a,b,consume=true){if(!alive(a)||!alive(b)||a.team===b.team||(consume&&acted.has(a.id))||dist(a,b)>a.range)return false;const dmg=damageValue(a,b),p=hpWrite(b,-dmg,'ironfront.attack',`unit:${a.id}`,{type:'attack',source:a.id,target:b.id,damage:dmg});const ok=transaction(p,`${a.name} โจมตี ${b.name} -${dmg} HP`);if(ok&&consume){acted.add(a.id);selected=null}if(ok&&world.hp[b.id]<=0)log(`${b.name} ถูกกำจัด`,'enemy');return ok}
function useSkill(a,b){if(!alive(a)||acted.has(a.id)||!b)return false;let p,label;if(a.cls==='Support'){if(b.team!==a.team||dist(a,b)>2)return false;const heal=Math.min(32,b.hp-world.hp[b.id]);if(heal<=0)return false;p=hpWrite(b,heal,'ironfront.skill.heal',`unit:${a.id}`,{type:'heal',source:a.id,target:b.id,amount:heal});label=`${a.name} ใช้ Field Heal → ${b.name} +${heal} HP`}
else{if(b.team===a.team)return false;const bonus=a.cls==='Vanguard'?14:a.cls==='Assault'?24:18;const range=a.cls==='Ranger'?5:a.range;if(dist(a,b)>range)return false;const dmg=damageValue(a,b,bonus),name=a.skill;p=hpWrite(b,-dmg,'ironfront.skill.attack',`unit:${a.id}`,{type:'skill',skill:name,source:a.id,target:b.id,damage:dmg});label=`${a.name} ใช้ ${name} ใส่ ${b.name} -${dmg} HP`}
const ok=transaction(p,label);if(ok){acted.add(a.id);selected=null;if(b.team!==a.team&&world.hp[b.id]<=0)log(`${b.name} ถูกกำจัด`,'enemy')}return ok}
function aiScoreAttack(a,b){const dmg=damageValue(a,b);return dmg+(world.hp[b.id]<=dmg?120:0)+(tile(ux(a),uy(a))==='high'?10:0)-(tile(ux(b),uy(b))==='forest'?6:0)}
function bestMove(u,target){let best=null,score=-Infinity;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))continue;const toTarget=Math.abs(x-ux(target))+Math.abs(y-uy(target));let s=-toTarget*10;if(tile(x,y)==='forest')s+=16;if(tile(x,y)==='high')s+=20;if(toTarget<=u.range)s+=30;if(s>score){score=s;best=[x,y]}}return best}
function enemyPhase(){phase='ENEMY';acted.clear();selected=null;draw();setTimeout(()=>{for(const u of units.filter(x=>alive(x)&&x.team===1)){let targets=units.filter(x=>alive(x)&&x.team===0);if(!targets.length)break;targets.sort((a,b)=>aiScoreAttack(u,b)-aiScoreAttack(u,a)||dist(u,a)-dist(u,b)||a.id-b.id);let t=targets[0];if(dist(u,t)<=u.range){attackUnit(u,t,true);continue}const m=bestMove(u,t);if(m)moveUnit(u,m[0],m[1],false);targets=units.filter(x=>alive(x)&&x.team===0&&dist(u,x)<=u.range).sort((a,b)=>aiScoreAttack(u,b)-aiScoreAttack(u,a)||a.id-b.id);if(targets[0])attackUnit(u,targets[0],true);else acted.add(u.id)}if(checkEnd())return;phase='PLAYER';turn++;acted.clear();selected=null;mode='move';log(`Turn ${turn} — Player Phase`,'ok');draw()},220)}
function checkEnd(){const p=units.some(u=>alive(u)&&u.team===0),e=units.some(u=>alive(u)&&u.team===1);if(!e){phase='VICTORY';log('MISSION COMPLETE — ชนะ!','ok');draw();return true}if(!p){phase='DEFEAT';log('MISSION FAILED — ทีมถูกกำจัด','enemy');draw();return true}return false}
function rewindOne(){if(chrono<=0||world.deltaLog.length===0)return;const r=rollback(world,1);if(!r.length)return;chrono--;selected=null;acted.clear();timeline.pop();log('⏪ Rewind 1 Action','ok');draw()}
function canvasPos(ev){const r=board.getBoundingClientRect();return[Math.floor((ev.clientX-r.left)*board.width/r.width/cell()),Math.floor((ev.clientY-r.top)*board.height/r.height/cell())]}
function handleBoard(ev){if(phase!=='PLAYER')return;const [x,y]=canvasPos(ev),u=unitAt(x,y);if(selected){if(mode==='attack'&&u&&u.team!==selected.team){attackUnit(selected,u);checkEnd();draw();return}if(mode==='skill'&&u){useSkill(selected,u);checkEnd();draw();return}if(mode==='move'&&!u){moveUnit(selected,x,y);draw();return}}if(u&&u.team===0&&!acted.has(u.id)){selected=u;mode='move';draw()}}
function log(text,cls=''){timeline.push({displayOnly:true,text,cls});renderTimeline()}
function renderTimeline(){const list=timeline.filter(x=>x.displayOnly).slice(-20).reverse();$('timeline').innerHTML=list.map(x=>`<div class="entry ${x.cls}">${x.text}</div>`).join('')}
function renderUnitCard(){if(!selected){$('unitCard').innerHTML='ยังไม่ได้เลือก';return}const hp=Math.max(0,world.hp[selected.id]),pct=Math.max(0,Math.min(100,hp/selected.hp*100)),t=tile(ux(selected),uy(selected));$('unitCard').innerHTML=`<b>${selected.name}</b><div class="muted">${selected.cls} • ATK ${selected.atk} • DEF ${selected.def} • MOV ${selected.mov} • RANGE ${selected.range}</div><div>HP ${Math.round(hp)} / ${selected.hp}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div style="margin-top:6px">Skill: <b>${selected.skill||'—'}</b></div><div class="muted">Terrain: ${t}${t==='forest'?' • Cover +8 DEF':t==='high'?' • High Ground +8 ATK':''}</div><div class="muted">โหมด: ${mode.toUpperCase()}</div>`}
function draw(){const cs=cell();ctx.clearRect(0,0,board.width,board.height);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const t=tile(x,y);ctx.fillStyle=t==='wall'?'#28394c':t==='forest'?'#395f46':t==='high'?'#6b5633':((x+y)%2?'#102338':'#0d1e31');ctx.fillRect(x*cs,y*cs,cs,cs);ctx.strokeStyle='#294863';ctx.strokeRect(x*cs,y*cs,cs,cs);if(t==='forest'){ctx.fillStyle='#8ccf78';ctx.font=`${cs*.24}px system-ui`;ctx.textAlign='center';ctx.fillText('♣',x*cs+cs/2,y*cs+cs*.62)}if(t==='high'){ctx.fillStyle='#e0b96b';ctx.font=`${cs*.22}px system-ui`;ctx.textAlign='center';ctx.fillText('▲',x*cs+cs/2,y*cs+cs*.62)}}
if(selected&&phase==='PLAYER'){const sx=ux(selected),sy=uy(selected),range=mode==='skill'?(selected.cls==='Ranger'?5:selected.cls==='Support'?2:selected.range):selected.range;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(x-sx)+Math.abs(y-sy);if(mode==='move'&&d>0&&d<=selected.mov&&canStand(x,y)){ctx.fillStyle='#2c9d6b55';ctx.fillRect(x*cs,y*cs,cs,cs)}if((mode==='attack'||mode==='skill')&&d>0&&d<=range){ctx.fillStyle=mode==='skill'?'#8a5cf055':'#d34b4b55';ctx.fillRect(x*cs,y*cs,cs,cs)}}}
for(const u of units){if(!alive(u))continue;const x=ux(u),y=uy(u),cx=x*cs+cs/2,cy=y*cs+cs/2;ctx.beginPath();ctx.arc(cx,cy,cs*.27,0,Math.PI*2);ctx.fillStyle=u.team===0?'#54c7ff':'#ff6b6b';ctx.fill();if(selected?.id===u.id){ctx.lineWidth=6;ctx.strokeStyle='#ffd166';ctx.stroke()}ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(16,cs*.18)}px system-ui`;ctx.textAlign='center';ctx.fillText(u.id,cx,cy+6);const hp=Math.max(0,world.hp[u.id])/u.hp;ctx.fillStyle='#1a2e3f';ctx.fillRect(x*cs+cs*.12,y*cs+cs*.78,cs*.76,7);ctx.fillStyle=u.team===0?'#5ce2a2':'#ff9a76';ctx.fillRect(x*cs+cs*.12,y*cs+cs*.78,cs*.76*hp,7)}
const pa=units.filter(u=>alive(u)&&u.team===0).length,ea=units.filter(u=>alive(u)&&u.team===1).length;$('turn').textContent=turn;$('phase').textContent=phase;$('chrono').textContent=chrono;$('alive').textContent=`${pa} / ${ea}`;$('objective').textContent=ea;$('hint').textContent=phase==='PLAYER'?(selected?`${selected.name}: ${mode==='move'?'แตะช่องสีเขียวเพื่อเดิน':mode==='attack'?'แตะศัตรูในพื้นที่สีแดง':'แตะเป้าหมายในพื้นที่สีม่วง'}`:'แตะยูนิตสีน้ำเงินเพื่อเลือก'):`${phase} กำลังทำงาน`;renderUnitCard();renderTimeline()}
board.addEventListener('pointerdown',handleBoard,{passive:true});
$('move').onclick=()=>{if(selected){mode='move';draw()}};$('attack').onclick=()=>{if(selected){mode='attack';draw()}};$('skill').onclick=()=>{if(selected){mode='skill';draw()}};$('end').onclick=()=>{if(phase==='PLAYER')enemyPhase()};$('rewind').onclick=rewindOne;$('reset').onclick=reset;$('clear').onclick=()=>{selected=null;draw()};
reset();