import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';
import {rollback} from '../../src/twa-history.js';

const $=id=>document.getElementById(id),SIZE=10,board=$('board'),ctx=board.getContext('2d'),cell=()=>board.width/SIZE;
const staticUnits=[
{id:0,name:'Vanguard',cls:'Vanguard',team:0,gx:1,gy:7,hp:130,atk:34,def:22,mov:4,range:1,skill:'Shield Bash'},
{id:1,name:'Assault',cls:'Assault',team:0,gx:2,gy:8,hp:100,atk:42,def:14,mov:5,range:1,skill:'Power Strike'},
{id:2,name:'Ranger',cls:'Ranger',team:0,gx:0,gy:8,hp:82,atk:38,def:10,mov:4,range:4,skill:'Precision Shot'},
{id:3,name:'Support',cls:'Support',team:0,gx:1,gy:9,hp:92,atk:24,def:14,mov:4,range:2,skill:'Field Heal'},
{id:4,name:'Raider A',cls:'Enemy',team:1,gx:7,gy:1,hp:90,atk:31,def:12,mov:4,range:1},
{id:5,name:'Raider B',cls:'Enemy',team:1,gx:8,gy:2,hp:90,atk:31,def:12,mov:4,range:1},
{id:6,name:'Raider C',cls:'Enemy',team:1,gx:6,gy:2,hp:90,atk:31,def:12,mov:4,range:1},
{id:7,name:'Sniper A',cls:'Enemy Ranger',team:1,gx:8,gy:0,hp:72,atk:34,def:9,mov:3,range:4},
{id:8,name:'Sniper B',cls:'Enemy Ranger',team:1,gx:9,gy:1,hp:72,atk:34,def:9,mov:3,range:4},
{id:9,name:'Heavy',cls:'Enemy Heavy',team:1,gx:7,gy:0,hp:125,atk:44,def:20,mov:2,range:3},
{id:10,name:'Command Core',cls:'Objective',team:1,gx:8,gy:4,hp:180,atk:0,def:18,mov:0,range:0,core:true}
];
const terrain=new Map([
['4,4','wall'],['4,5','wall'],['5,4','wall'],['5,5','wall'],
['2,4','forest'],['2,5','forest'],['7,5','forest'],['8,5','forest'],
['5,1','high'],['6,1','high'],['3,7','high'],['6,6','fire']
]);
let world,units,turn,phase,selected,mode,chrono,timeline,statuses,turnState,actionFrames,playerLosses;
const gxToX=g=>-0.9+g*0.2,gyToY=g=>-0.9+g*0.2,xToG=x=>Math.round((x+0.9)/0.2),yToG=y=>Math.round((y+0.9)/0.2);
const tile=(x,y)=>terrain.get(`${x},${y}`)||'plain';
const alive=u=>world.active[u.id]&&world.hp[u.id]>0;
const ux=u=>xToG(world.x[u.id]),uy=u=>yToG(world.y[u.id]);
const dist=(a,b)=>Math.abs(ux(a)-ux(b))+Math.abs(uy(a)-uy(b));
const unitAt=(x,y)=>units.find(u=>alive(u)&&ux(u)===x&&uy(u)===y);
const canStand=(x,y)=>x>=0&&y>=0&&x<SIZE&&y<SIZE&&tile(x,y)!=='wall'&&!unitAt(x,y);
const st=u=>statuses.get(u.id)||[];
const hasStatus=(u,type)=>st(u).some(s=>s.type===type&&s.turns>0);
const coverBonus=u=>tile(ux(u),uy(u))==='forest'?8:0;
const highBonus=u=>tile(ux(u),uy(u))==='high'?8:0;
const atkBonus=u=>st(u).filter(s=>s.type==='atk').reduce((n,s)=>n+s.amount,0);
const defBonus=u=>st(u).filter(s=>s.type==='def'||s.type==='guard').reduce((n,s)=>n+s.amount,0);
const stateFor=u=>turnState.get(u.id)||{moved:false,acted:false};
function setState(u,patch){turnState.set(u.id,{...stateFor(u),...patch})}
function cloneStatuses(){return new Map([...statuses].map(([k,v])=>[k,v.map(x=>({...x}))]))}
function captureFrame(label){return {label,deltaLen:world.deltaLog.length,turn,phase,chrono,selectedId:selected?.id??null,mode,turnState:new Map([...turnState].map(([k,v])=>[k,{...v}])),statuses:cloneStatuses(),timelineLen:timeline.length,playerLosses}}
function pushFrame(label){actionFrames.push(captureFrame(label));if(actionFrames.length>200)actionFrames.shift()}
function restoreFrame(f){turn=f.turn;phase=f.phase;mode=f.mode;chrono=f.chrono;turnState=new Map([...f.turnState].map(([k,v])=>[k,{...v}]));statuses=new Map([...f.statuses].map(([k,v])=>[k,v.map(x=>({...x}))]));timeline.length=f.timelineLen;playerLosses=f.playerLosses;selected=f.selectedId==null?null:units.find(u=>u.id===f.selectedId)||null}
function reset(){
  world=createWorld({seed:42,count:staticUnits.length,density:0,speed:0});units=staticUnits.map(u=>({...u}));
  for(const u of units){world.team[u.id]=u.team;world.x[u.id]=gxToX(u.gx);world.y[u.id]=gyToY(u.gy);world.vx[u.id]=0;world.vy[u.id]=0;world.hp[u.id]=u.hp;world.radius[u.id]=u.core?.045:.03;world.type[u.id]=u.team===0?1:2}
  turn=1;phase='PLAYER';selected=null;mode='move';chrono=3;timeline=[];statuses=new Map();turnState=new Map();actionFrames=[];playerLosses=0;
  units.forEach(u=>statuses.set(u.id,[]));record('MISSION','Operation Broken Shield เริ่มต้น','ok');draw();
}
function record(type,text,cls='',meta={}){timeline.push({type,text,cls,turn,phase,worldVersion:world.worldVersion,hash:stateHash(world),...meta});renderTimeline()}
function transaction(p,label,type='ACTION',meta={}){const resolved=resolveConflicts([p]),check=verify(world,resolved,{critical:false});if(!check.ok){record('BLOCKED',check.errors.join(', '),'enemy');return false}const rec=commit(world,resolved,{verifierResult:check});record(type,label,phase==='PLAYER'?'player':'enemy',{commit:rec.worldVersion,...meta});return true}
function addStatus(target,type,turns,amount=0,source=null){const list=st(target).filter(s=>s.type!==type);list.push({type,turns,amount,source});statuses.set(target.id,list);record('STATUS',`${target.name} ได้รับ ${type.toUpperCase()} ${turns} เทิร์น`,'warn')}
function cleanDead(){for(const u of units){if(world.hp[u.id]<=0&&world.active[u.id]){world.hp[u.id]=0;world.active[u.id]=0;if(u.team===0)playerLosses++;record('DEFEAT',`${u.name} ถูกกำจัด`,'enemy')}}}
function moveUnit(u,x,y,{consume=true,frame=true}={}){if(!alive(u)||u.core||hasStatus(u,'stun'))return false;const us=stateFor(u);if(consume&&us.moved)return false;const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))return false;if(frame)pushFrame(`${u.name} move`);const s=snapshot(world),p=makeProposal({snapshot:s,systemId:'ironfront.move',source:`unit:${u.id}`,priority:240,writes:[{entity:u.id,field:'x',value:gxToX(x),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]},{entity:u.id,field:'y',value:gyToY(y),expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]}],events:[{type:'move',entity:u.id,gx:x,gy:y}],meta:{authority:true,game:'iron-front'}});const ok=transaction(p,`${u.name} เดินไป (${x},${y})`,'MOVE');if(ok&&consume){setState(u,{moved:true});selected=u;mode='attack';if(tile(x,y)==='fire')addStatus(u,'burn',2,8,'terrain')}return ok}
function damageValue(a,b,power=0,ignoreCover=false){return Math.max(1,a.atk+atkBonus(a)+power+highBonus(a)-b.def-defBonus(b)-(ignoreCover?0:coverBonus(b)))}
function hpProposal(target,delta,systemId,source,event){const s=snapshot(world);return makeProposal({snapshot:s,systemId,source,priority:270,writes:[{entity:target.id,field:'hp',op:'add',value:delta,expectedVersion:s.version[target.id],expectedGeneration:s.generation[target.id]}],events:[event],meta:{authority:true,game:'iron-front'}})}
function attackUnit(a,b,{consume=true,frame=true}={}){if(!alive(a)||!alive(b)||a.team===b.team||a.core||hasStatus(a,'stun'))return false;const us=stateFor(a);if(consume&&us.acted||dist(a,b)>a.range)return false;if(frame)pushFrame(`${a.name} attack`);const dmg=damageValue(a,b),p=hpProposal(b,-dmg,'ironfront.attack',`unit:${a.id}`,{type:'attack',source:a.id,target:b.id,damage:dmg});const ok=transaction(p,`${a.name} โจมตี ${b.name} -${dmg} HP`,'ATTACK',{attacker:a.id,target:b.id,damage:dmg});if(ok&&consume){setState(a,{acted:true});selected=null}if(ok)cleanDead();return ok}
function useSkill(a,b){if(!alive(a)||a.core||hasStatus(a,'stun')||stateFor(a).acted||!b)return false;pushFrame(`${a.name} skill`);let p,label,statusAfter=null;if(a.cls==='Support'){if(b.team!==a.team||dist(a,b)>2){actionFrames.pop();return false}const heal=Math.min(32,b.hp-world.hp[b.id]);if(heal<=0){actionFrames.pop();return false}p=hpProposal(b,heal,'ironfront.skill.heal',`unit:${a.id}`,{type:'heal',source:a.id,target:b.id,amount:heal});label=`${a.name} ใช้ Field Heal → ${b.name} +${heal} HP`;statusAfter=()=>addStatus(b,'def',1,6,a.id)}else{if(b.team===a.team){actionFrames.pop();return false}const isRanger=a.cls==='Ranger',range=isRanger?5:a.range;if(dist(a,b)>range){actionFrames.pop();return false}const bonus=a.cls==='Vanguard'?14:a.cls==='Assault'?24:18,dmg=damageValue(a,b,bonus,isRanger);p=hpProposal(b,-dmg,'ironfront.skill.attack',`unit:${a.id}`,{type:'skill',skill:a.skill,source:a.id,target:b.id,damage:dmg});label=`${a.name} ใช้ ${a.skill} ใส่ ${b.name} -${dmg} HP`;if(a.cls==='Vanguard')statusAfter=()=>addStatus(b,'stun',1,0,a.id);if(a.cls==='Assault')statusAfter=()=>addStatus(b,'burn',2,8,a.id)}const ok=transaction(p,label,'SKILL',{skill:a.skill});if(ok){setState(a,{acted:true});selected=null;statusAfter?.();cleanDead()}else actionFrames.pop();return ok}
function guardSelected(){if(!selected||stateFor(selected).acted||hasStatus(selected,'stun'))return;pushFrame(`${selected.name} guard`);addStatus(selected,'guard',1,10,selected.id);setState(selected,{acted:true});record('GUARD',`${selected.name} ตั้งรับ +10 DEF`,'player');selected=null;draw()}
function aiScoreAttack(a,b){const dmg=damageValue(a,b);return dmg+(world.hp[b.id]<=dmg?120:0)+(tile(ux(a),uy(a))==='high'?10:0)-(tile(ux(b),uy(b))==='forest'?6:0)}
function bestMove(u,target){let best=null,score=-Infinity;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(ux(u)-x)+Math.abs(uy(u)-y);if(d<1||d>u.mov||!canStand(x,y))continue;const toTarget=Math.abs(x-ux(target))+Math.abs(y-uy(target));let s=-toTarget*10;if(tile(x,y)==='forest')s+=16;if(tile(x,y)==='high')s+=20;if(tile(x,y)==='fire')s-=25;if(toTarget<=u.range)s+=30;if(s>score){score=s;best=[x,y]}}return best}
function processEnvironment(){pushFrame('environment');const targets=units.filter(alive),writes=[],events=[],s=snapshot(world);for(const u of targets){for(const x of st(u)){if(x.type==='burn'){writes.push({entity:u.id,field:'hp',op:'add',value:-x.amount,expectedVersion:s.version[u.id],expectedGeneration:s.generation[u.id]});events.push({type:'status-damage',status:'burn',target:u.id,damage:x.amount})}}}if(writes.length){const p=makeProposal({snapshot:s,systemId:'ironfront.environment',source:'environment',priority:280,writes,events,meta:{authority:true}});transaction(p,`Environment Phase: Burn ${writes.length} เป้าหมาย`,'ENV')}else record('ENV','Environment Phase: ไม่มี damage','ok');for(const u of units){statuses.set(u.id,st(u).map(x=>({...x,turns:x.turns-1})).filter(x=>x.turns>0))}cleanDead()}
function enemyPhase(){phase='ENEMY';selected=null;turnState=new Map();draw();setTimeout(()=>{for(const u of units.filter(x=>alive(x)&&x.team===1&&!x.core)){if(hasStatus(u,'stun')){record('STUN',`${u.name} ติด Stun ข้ามเทิร์น`,'warn');setState(u,{moved:true,acted:true});continue}let targets=units.filter(x=>alive(x)&&x.team===0);if(!targets.length)break;targets.sort((a,b)=>aiScoreAttack(u,b)-aiScoreAttack(u,a)||dist(u,a)-dist(u,b)||a.id-b.id);let t=targets[0];if(dist(u,t)<=u.range){attackUnit(u,t,{consume:true,frame:true});continue}const m=bestMove(u,t);if(m)moveUnit(u,m[0],m[1],{consume:true,frame:true});targets=units.filter(x=>alive(x)&&x.team===0&&dist(u,x)<=u.range).sort((a,b)=>aiScoreAttack(u,b)-aiScoreAttack(u,a)||a.id-b.id);if(targets[0])attackUnit(u,targets[0],{consume:true,frame:true})}if(checkEnd())return;phase='ENV';draw();processEnvironment();if(checkEnd())return;turn++;if(turn>12){phase='DEFEAT';record('MISSION','หมดเวลา 12 Turns — Mission Failed','enemy');draw();return}phase='PLAYER';turnState=new Map();selected=null;mode='move';record('TURN',`Turn ${turn} — Player Phase`,'ok');draw()},220)}
function core(){return units.find(u=>u.core)}
function checkEnd(){const players=units.some(u=>alive(u)&&u.team===0),c=core();if(!alive(c)){phase='VICTORY';record('MISSION',`MISSION COMPLETE • Core ถูกทำลาย • ${playerLosses===0?'Secondary สำเร็จ':'เสียยูนิต '+playerLosses}`,'ok');draw();return true}if(!players){phase='DEFEAT';record('MISSION','MISSION FAILED — ทีมถูกกำจัด','enemy');draw();return true}return false}
function rewindOne(){if(phase!=='PLAYER'||chrono<=0||!actionFrames.length)return;const f=actionFrames.pop(),steps=Math.max(0,world.deltaLog.length-f.deltaLen);if(steps)rollback(world,steps);restoreFrame(f);chrono=Math.max(0,chrono-1);selected=null;record('REWIND',`⏪ ย้อน ${f.label} • ${steps} commit`,'ok');draw()}
function canvasPos(ev){const r=board.getBoundingClientRect();return[Math.floor((ev.clientX-r.left)*board.width/r.width/cell()),Math.floor((ev.clientY-r.top)*board.height/r.height/cell())]}
function handleBoard(ev){if(phase!=='PLAYER')return;const [x,y]=canvasPos(ev),u=unitAt(x,y);if(selected){if(mode==='attack'&&u&&u.team!==selected.team){attackUnit(selected,u);checkEnd();draw();return}if(mode==='skill'&&u){useSkill(selected,u);checkEnd();draw();return}if(mode==='move'&&!u){moveUnit(selected,x,y);draw();return}}if(u&&u.team===0&&!stateFor(u).acted){selected=u;mode=stateFor(u).moved?'attack':'move';draw()}}
function renderTimeline(){const list=timeline.slice(-28).reverse();$('timeline').innerHTML=list.map(x=>`<div class="entry ${x.cls||''}"><b>${x.type}</b> • ${x.text}<small>T${x.turn} ${x.phase} • v${x.worldVersion} • ${String(x.hash).slice(0,10)}</small></div>`).join('')}
function renderUnitCard(){if(!selected){$('unitCard').innerHTML='ยังไม่ได้เลือก';return}const hp=Math.max(0,world.hp[selected.id]),pct=Math.max(0,Math.min(100,hp/selected.hp*100)),t=tile(ux(selected),uy(selected)),tags=st(selected).map(s=>`<span class="status ${s.type==='atk'?'atk':s.type==='def'?'def':s.type}">${s.type.toUpperCase()} ${s.turns}</span>`).join('')||'<span class="muted">ไม่มีสถานะ</span>';$('unitCard').innerHTML=`<b>${selected.name}</b><div class="muted">${selected.cls} • ATK ${selected.atk}+${atkBonus(selected)} • DEF ${selected.def}+${defBonus(selected)} • MOV ${selected.mov} • RANGE ${selected.range}</div><div>HP ${Math.round(hp)} / ${selected.hp}</div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div style="margin-top:6px">Skill: <b>${selected.skill||'—'}</b></div><div class="muted">Terrain: ${t}${t==='forest'?' • Cover +8 DEF':t==='high'?' • High Ground +8 ATK':t==='fire'?' • Burn':''}</div><div>${tags}</div><div class="muted">Moved ${stateFor(selected).moved?'✓':'—'} • Acted ${stateFor(selected).acted?'✓':'—'} • Mode ${mode.toUpperCase()}</div>`}
function draw(){const cs=cell();ctx.clearRect(0,0,board.width,board.height);for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const t=tile(x,y);ctx.fillStyle=t==='wall'?'#28394c':t==='forest'?'#395f46':t==='high'?'#6b5633':t==='fire'?'#7f2d28':((x+y)%2?'#102338':'#0d1e31');ctx.fillRect(x*cs,y*cs,cs,cs);ctx.strokeStyle='#294863';ctx.strokeRect(x*cs,y*cs,cs,cs);ctx.textAlign='center';if(t==='forest'){ctx.fillStyle='#8ccf78';ctx.font=`${cs*.24}px system-ui`;ctx.fillText('♣',x*cs+cs/2,y*cs+cs*.62)}if(t==='high'){ctx.fillStyle='#e0b96b';ctx.font=`${cs*.22}px system-ui`;ctx.fillText('▲',x*cs+cs/2,y*cs+cs*.62)}if(t==='fire'){ctx.fillStyle='#ffb15c';ctx.font=`${cs*.22}px system-ui`;ctx.fillText('🔥',x*cs+cs/2,y*cs+cs*.62)}}if(selected&&phase==='PLAYER'){const sx=ux(selected),sy=uy(selected),range=mode==='skill'?(selected.cls==='Ranger'?5:selected.cls==='Support'?2:selected.range):selected.range;for(let y=0;y<SIZE;y++)for(let x=0;x<SIZE;x++){const d=Math.abs(x-sx)+Math.abs(y-sy);if(mode==='move'&&!stateFor(selected).moved&&d>0&&d<=selected.mov&&canStand(x,y)){ctx.fillStyle='#2c9d6b55';ctx.fillRect(x*cs,y*cs,cs,cs)}if((mode==='attack'||mode==='skill')&&d>0&&d<=range){ctx.fillStyle=mode==='skill'?'#8a5cf055':'#d34b4b55';ctx.fillRect(x*cs,y*cs,cs,cs)}}}for(const u of units){if(!alive(u))continue;const x=ux(u),y=uy(u),cx=x*cs+cs/2,cy=y*cs+cs/2;ctx.beginPath();if(u.core){ctx.rect(cx-cs*.28,cy-cs*.28,cs*.56,cs*.56);ctx.fillStyle='#b548a9'}else{ctx.arc(cx,cy,cs*.27,0,Math.PI*2);ctx.fillStyle=u.team===0?'#54c7ff':'#ff6b6b'}ctx.fill();if(selected?.id===u.id){ctx.lineWidth=6;ctx.strokeStyle='#ffd166';ctx.stroke()}ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(16,cs*.16)}px system-ui`;ctx.textAlign='center';ctx.fillText(u.core?'CORE':u.id,cx,cy+5);const hp=Math.max(0,world.hp[u.id])/u.hp;ctx.fillStyle='#1a2e3f';ctx.fillRect(x*cs+cs*.12,y*cs+cs*.78,cs*.76,7);ctx.fillStyle=u.team===0?'#5ce2a2':'#ff9a76';ctx.fillRect(x*cs+cs*.12,y*cs+cs*.78,cs*.76*hp,7);if(st(u).length){ctx.fillStyle='#ffd166';ctx.font=`${cs*.14}px system-ui`;ctx.fillText(st(u).map(s=>s.type[0].toUpperCase()).join(''),cx,cy-cs*.3)}}const pa=units.filter(u=>alive(u)&&u.team===0).length,ea=units.filter(u=>alive(u)&&u.team===1&&!u.core).length,c=core();$('turn').textContent=turn;$('phase').textContent=phase;$('chrono').textContent=chrono;$('alive').textContent=`${pa} / ${ea}`;$('objective').textContent=`CORE ${Math.max(0,Math.round(world.hp[c.id]))}`;$('objectiveText').textContent=`ทำลาย Enemy Command Core ภายใน 12 Turns • Secondary: ห้ามเสียยูนิต • ศัตรูทั่วไปเหลือ ${ea}`;$('hint').textContent=phase==='PLAYER'?(selected?`${selected.name}: ${mode==='move'?'แตะช่องสีเขียวเพื่อเดิน':mode==='attack'?'แตะศัตรูในพื้นที่สีแดง':'แตะเป้าหมายในพื้นที่สีม่วง'}`:'แตะยูนิตสีน้ำเงินเพื่อเลือก'):`${phase} กำลังทำงาน`;renderUnitCard();renderTimeline()}
board.addEventListener('pointerdown',handleBoard,{passive:true});
$('move').onclick=()=>{if(selected&&!stateFor(selected).moved){mode='move';draw()}};
$('attack').onclick=()=>{if(selected&&!stateFor(selected).acted){mode='attack';draw()}};
$('skill').onclick=()=>{if(selected&&!stateFor(selected).acted){mode='skill';draw()}};
$('end').onclick=()=>{if(phase==='PLAYER')enemyPhase()};
$('rewind').onclick=rewindOne;
$('reset').onclick=reset;
$('clear').onclick=()=>{selected=null;draw()};
reset();