import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';

const $=id=>document.getElementById(id), canvas=$('battle'), ctx=canvas.getContext('2d');
const TICK_MS=100,SEED=4242,SQUAD_SIZE=10,PLATOON_SIZE=30,COMPANY_SIZE=90,BATTALION_SIZE=270,SPATIAL_CELL=.06;
const HILL={x:.58,y:0,r:.18};
const ROLE={RIFLE:0,LEADER:1,MG:2,MEDIC:3,MARKSMAN:4,SCOUT:5,GRENADIER:6,ENGINEER:7};
const STATE={ADVANCE:0,SEEK_COVER:1,AIM:2,FIRE:3,SUPPRESS:4,RELOAD:5,FALL_BACK:6,PINNED:7,ROUT:8};
const SQ={ADVANCE:0,ENGAGE:1,SUPPRESS:2,FLANK:3,DEFEND:4,FALLBACK:5,RESERVE:6,ASSAULT:7};
const PL={ADVANCE:0,FIRE_BASE:1,MANEUVER:2,ASSAULT:3,RESERVE:4,DEFEND:5,COUNTER:6,FALLBACK:7};
const WEAPON={0:{range:.15,optimal:.105,damage:8,accuracy:.72,cadence:3,supp:6,ammo:90},1:{range:.15,optimal:.105,damage:7,accuracy:.74,cadence:3,supp:6,ammo:90},2:{range:.19,optimal:.14,damage:5,accuracy:.64,cadence:2,supp:17,ammo:180},3:{range:.12,optimal:.08,damage:4,accuracy:.60,cadence:5,supp:3,ammo:45},4:{range:.23,optimal:.18,damage:18,accuracy:.86,cadence:6,supp:5,ammo:50},5:{range:.18,optimal:.13,damage:6,accuracy:.78,cadence:4,supp:4,ammo:70},6:{range:.16,optimal:.11,damage:7,accuracy:.70,cadence:4,supp:8,ammo:70},7:{range:.14,optimal:.10,damage:7.5,accuracy:.68,cadence:3,supp:6,ammo:80}};
const TERRAIN=[{x:-.18,y:-.42,r:.16,cover:.18,name:'FOREST'},{x:-.10,y:.40,r:.17,cover:.20,name:'FOREST'},{x:.34,y:-.28,r:.13,cover:.22,name:'FORWARD TRENCH'},{x:.36,y:.28,r:.13,cover:.22,name:'FORWARD TRENCH'},{x:.55,y:-.14,r:.14,cover:.34,name:'HILL TRENCH'},{x:.57,y:.16,r:.14,cover:.34,name:'HILL TRENCH'},{x:.72,y:0,r:.12,cover:.27,name:'RESERVE'}];

let world,count=1200,running=true,speed=1,last=performance.now(),acc=0,benchRunning=false,battleOver=false,winner='',doctrine='BALANCED';
let morale,suppression,cohesion,role,squadId,platoonId,companyId,battalionId,cooldown,ammo,targetId,combatState,aimTicks,healCooldown;
let hierarchy={battalions:[],companies:[],platoons:[],squads:[]},log=[],combatFx=[],deathFx=[];
let battlePhase='DEPLOY',hillHoldBlue=0,weakPoint={y:0,score:0,active:false};
let activity={shots:0,hits:0,damage:0,engaged:0,kills:0};
let profiler={snap:0,spatial:0,move:0,combat:0,commit:0,writes:0,conflicts:0,last:0,cells:0,maxCell:0,queries:0,candidates:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function hash01(a,b,c,d=0){let x=(SEED^(a*374761393)^(b*668265263)^(c*2246822519)^(d*3266489917))>>>0;x^=x>>>13;x=Math.imul(x,1274126177)>>>0;x^=x>>>16;return x/4294967296}
function alive(i){return i>=0&&i<count&&world.active[i]&&world.hp[i]>0}
function roleForSlot(s){return s===0?ROLE.LEADER:s===1?ROLE.MEDIC:s===2?ROLE.MG:s===3?ROLE.GRENADIER:s===4?ROLE.SCOUT:s===5?ROLE.MARKSMAN:s===6?ROLE.ENGINEER:ROLE.RIFLE}
function pushLog(type,text){log.push({tick:world?.tick||0,type,text});if(log.length>120)log.shift();$('log').innerHTML=log.slice(-18).reverse().map(x=>`<div class="entry"><b>${x.type}</b> • ${x.text}<div class="muted">tick ${x.tick}</div></div>`).join('')}
function coverAt(x,y,team){let c=0;for(const t of TERRAIN)if(Math.hypot(x-t.x,y-t.y)<t.r)c=Math.max(c,t.cover);if(team===1&&x>.30&&x<.76&&Math.abs(y)<.50)c=Math.max(c,.08);return c}

function init(n=count){count=n;world=createWorld({seed:SEED,count,density:.15,speed:0});morale=new Float32Array(count);suppression=new Float32Array(count);cohesion=new Float32Array(count);role=new Uint8Array(count);combatState=new Uint8Array(count);aimTicks=new Uint8Array(count);squadId=new Uint32Array(count);platoonId=new Uint32Array(count);companyId=new Uint32Array(count);battalionId=new Uint32Array(count);cooldown=new Uint8Array(count);ammo=new Uint16Array(count);targetId=new Int32Array(count);targetId.fill(-1);healCooldown=new Uint8Array(count);hierarchy={battalions:[],companies:[],platoons:[],squads:[]};log=[];combatFx=[];deathFx=[];hillHoldBlue=0;battlePhase='DEPLOY';battleOver=false;winner='';weakPoint={y:0,score:0,active:false};const half=count>>1;buildHierarchy(0,0,half);buildHierarchy(1,half,count);for(let i=0;i<count;i++){const sq=hierarchy.squads[squadId[i]],team=i<half?0:1,slot=i-sq.start,row=Math.floor(slot/5),col=slot%5,side=team===0?-1:1;role[i]=roleForSlot(slot%10);world.team[i]=team;world.active[i]=1;world.hp[i]=100;world.radius[i]=.0042;world.mass[i]=1;morale[i]=100;cohesion[i]=100;ammo[i]=WEAPON[role[i]].ammo;world.x[i]=sq.anchorX+side*col*.008;world.y[i]=sq.anchorY+(row-.5)*.014}world.tick=0;world.worldVersion=0;world.deltaLog.length=0;world.eventLog.length=0;pushLog('SYSTEM',`Total Front P6 • Platoon Coordination • ${count.toLocaleString()} entities`);pushLog('AI','Platoon แบ่งบทบาท FIRE BASE / MANEUVER / ASSAULT / RESERVE อัตโนมัติ');draw();updateHUD()}

function buildHierarchy(team,start,end){const side=team===0?-1:1,total=end-start,bnCount=Math.max(1,Math.ceil(total/BATTALION_SIZE));for(let b=0;b<bnCount;b++){const bnId=hierarchy.battalions.length,bs=start+b*BATTALION_SIZE,be=Math.min(end,bs+BATTALION_SIZE),lane=bnCount===1?0:-.68+b*(1.36/(bnCount-1));hierarchy.battalions.push({id:bnId,team,start:bs,end:be,homeX:side*.72,homeY:lane,targetX:team===0?-.48:HILL.x,targetY:lane,order:team===0?'ASSEMBLE':'DEFEND'});for(let c=0,cs=bs;cs<be;c++,cs+=COMPANY_SIZE){const ce=Math.min(be,cs+COMPANY_SIZE),coId=hierarchy.companies.length,coY=(c-1)*.08;hierarchy.companies.push({id:coId,team,battalionId:bnId,start:cs,end:ce,targetX:side*.58,targetY:lane+coY});for(let p=0,ps=cs;ps<ce;p++,ps+=PLATOON_SIZE){const pe=Math.min(ce,ps+PLATOON_SIZE),plId=hierarchy.platoons.length;hierarchy.platoons.push({id:plId,team,battalionId:bnId,companyId:coId,start:ps,end:pe,state:team===0?PL.ADVANCE:PL.DEFEND,targetX:side*.58,targetY:lane+coY+(p-1)*.05,contact:0});for(let q=0,qs=ps;qs<pe;q++,qs+=SQUAD_SIZE){const qe=Math.min(pe,qs+SQUAD_SIZE),sqId=hierarchy.squads.length,anchorY=lane+coY+(p-1)*.05+(q-1)*.022;hierarchy.squads.push({id:sqId,team,battalionId:bnId,companyId:coId,platoonId:plId,start:qs,end:qe,anchorX:side*.72+side*(c*.025+q*.012),anchorY,targetX:side*.58,targetY:anchorY,state:team===0?SQ.ADVANCE:SQ.DEFEND});for(let i=qs;i<qe;i++){squadId[i]=sqId;platoonId[i]=plId;companyId[i]=coId;battalionId[i]=bnId}}}}}}
function buildSpatial(){const t0=performance.now(),g=new Map();let maxCell=0;for(let i=0;i<count;i++)if(alive(i)){const cx=Math.floor(world.x[i]/SPATIAL_CELL),cy=Math.floor(world.y[i]/SPATIAL_CELL),k=cx+','+cy;let a=g.get(k);if(!a){a=[];g.set(k,a)}a.push(i);maxCell=Math.max(maxCell,a.length)}profiler.spatial=performance.now()-t0;profiler.cells=g.size;profiler.maxCell=maxCell;profiler.queries=0;profiler.candidates=0;return{g,cell:SPATIAL_CELL}}
function neighbors(i,sp,rings=1){const cx=Math.floor(world.x[i]/sp.cell),cy=Math.floor(world.y[i]/sp.cell),out=[];profiler.queries++;for(let ox=-rings;ox<=rings;ox++)for(let oy=-rings;oy<=rings;oy++){const a=sp.g.get((cx+ox)+','+(cy+oy));if(a){profiler.candidates+=a.length;out.push(...a)}}return out}
function unitStats(u){let n=0,m=0,s=0,x=0,y=0;for(let i=u.start;i<u.end;i++)if(alive(i)){n++;m+=morale[i];s+=suppression[i];x+=world.x[i];y+=world.y[i]}return{alive:n,morale:n?m/n:0,supp:n?s/n:0,x:n?x/n:u.targetX,y:n?y/n:u.targetY,strength:n/Math.max(1,u.end-u.start)}}
function teamNearHill(team){let n=0;for(let i=0;i<count;i++)if(alive(i)&&world.team[i]===team&&Math.hypot(world.x[i]-HILL.x,world.y[i])<HILL.r)n++;return n}
function analyzeFront(){let best={y:0,score:-1};for(let k=0;k<9;k++){const y=-.64+k*.16;let blue=0,red=0,redSupp=0,redMorale=0;for(let i=0;i<count;i++)if(alive(i)&&Math.abs(world.y[i]-y)<.09&&world.x[i]>.20){if(world.team[i]===0)blue++;else{red++;redSupp+=suppression[i];redMorale+=morale[i]}}const avgS=red?redSupp/red:0,avgM=red?redMorale/red:100,score=(100-avgM)*.35+avgS*.35+(blue/(red+5))*22-red*.08;if(score>best.score)best={y,score}}weakPoint={...best,active:best.score>40}}
function strategicAI(){analyzeFront();const tick=world.tick;if(tick<20)battlePhase='DEPLOY';else if(weakPoint.active)battlePhase='BREAKTHROUGH';else battlePhase='ENGAGEMENT';for(const bn of hierarchy.battalions){const st=unitStats(bn);if(bn.team===0){if(st.strength<.28||st.morale<20){bn.order='RETREAT';bn.targetX=-.72;bn.targetY=bn.homeY}else{bn.order=weakPoint.active?'BREAKTHROUGH':'ATTACK';bn.targetX=HILL.x-.02;bn.targetY=weakPoint.active?weakPoint.y:bn.homeY*.25}}else{if(st.strength<.28||st.morale<18){bn.order='FALLBACK';bn.targetX=.82;bn.targetY=bn.homeY}else{bn.order=weakPoint.active?'BLOCK':'DEFEND';bn.targetX=HILL.x;bn.targetY=weakPoint.active?weakPoint.y:bn.homeY*.30}}}}
function platoonAI(){for(const co of hierarchy.companies){const pls=hierarchy.platoons.filter(p=>p.companyId===co.id),stats=pls.map(unitStats);if(!pls.length)continue;for(let i=0;i<pls.length;i++){const p=pls[i],s=stats[i],bn=hierarchy.battalions[p.battalionId];if(bn.order==='RETREAT'||bn.order==='FALLBACK'||s.morale<22){p.state=PL.FALLBACK;p.targetX=bn.homeX;p.targetY=bn.homeY+(i-1)*.06;continue}if(p.team===0){if(weakPoint.active){p.state=i===0?PL.FIRE_BASE:i===1?PL.MANEUVER:PL.ASSAULT;p.targetX=i===0?HILL.x-.18:i===1?HILL.x-.04:HILL.x+.06;p.targetY=weakPoint.y+(i-1)*.06}else{p.state=i===0?PL.FIRE_BASE:i===1?PL.MANEUVER:PL.RESERVE;p.targetX=i===0?HILL.x-.20:i===1?HILL.x-.06:HILL.x-.26;p.targetY=bn.targetY+(i-1)*.08}}else{if(weakPoint.active&&Math.abs(p.targetY-weakPoint.y)<.30){p.state=i===2?PL.COUNTER:PL.DEFEND;p.targetX=i===2?HILL.x-.03:HILL.x+.02;p.targetY=weakPoint.y+(i-1)*.05}else{p.state=i===2?PL.RESERVE:PL.DEFEND;p.targetX=i===2?HILL.x+.15:HILL.x;p.targetY=bn.targetY+(i-1)*.08}}}}
function squadAI(){for(const sq of hierarchy.squads){const p=hierarchy.platoons[sq.platoonId],local=Math.floor((sq.start-p.start)/SQUAD_SIZE);sq.targetX=p.targetX+(sq.team===0?-1:1)*local*.012;sq.targetY=p.targetY+(local-1)*.024;if(p.state===PL.FIRE_BASE)sq.state=local===0?SQ.SUPPRESS:SQ.ENGAGE;else if(p.state===PL.MANEUVER)sq.state=local===0?SQ.SUPPRESS:SQ.FLANK;else if(p.state===PL.ASSAULT)sq.state=local===0?SQ.SUPPRESS:SQ.ASSAULT;else if(p.state===PL.RESERVE)sq.state=SQ.RESERVE;else if(p.state===PL.DEFEND||p.state===PL.COUNTER)sq.state=SQ.DEFEND;else if(p.state===PL.FALLBACK)sq.state=SQ.FALLBACK;else sq.state=SQ.ADVANCE}}
function acquireTarget(i,sp,range){let best=-1,bestD=999;for(const j of neighbors(i,sp,Math.max(1,Math.ceil(range/sp.cell)))){if(j===i||!alive(j)||world.team[j]===world.team[i])continue;const d=Math.hypot(world.x[j]-world.x[i],world.y[j]-world.y[i]);if(d<bestD&&d<=range){best=j;bestD=d}}targetId[i]=best;return{entity:best,distance:bestD}}
function chooseState(i,hasTarget,dist){const sq=hierarchy.squads[squadId[i]],wp=WEAPON[role[i]];if(sq.state===SQ.FALLBACK||morale[i]<12)return STATE.ROUT;if(morale[i]<25)return STATE.FALL_BACK;if(suppression[i]>80)return STATE.PINNED;if(suppression[i]>52)return STATE.SEEK_COVER;if(ammo[i]===0)return STATE.RELOAD;if(!hasTarget)return STATE.ADVANCE;if(role[i]===ROLE.MG&&(sq.state===SQ.SUPPRESS||sq.state===SQ.DEFEND))return STATE.SUPPRESS;if(dist>wp.optimal*1.08)return STATE.ADVANCE;if(aimTicks[i]<1)return STATE.AIM;return STATE.FIRE}
function movementProposal(s,sp){const t0=performance.now();if(world.tick%5===0){strategicAI();platoonAI()}squadAI();const writes=[],step=.0095;let engaged=0;for(let i=0;i<count;i++)if(alive(i)){const sq=hierarchy.squads[squadId[i]],p=hierarchy.platoons[platoonId[i]],slot=i-sq.start,row=Math.floor(slot/5),col=slot%5,side=world.team[i]===0?-1:1,r=role[i],wp=WEAPON[r],ac=acquireTarget(i,sp,wp.range*1.08),has=ac.entity>=0;if(has)engaged++;combatState[i]=chooseState(i,has,ac.distance);let tx=sq.targetX+side*col*.007,ty=sq.targetY+(row-.5)*.012;if(r===ROLE.SCOUT)tx-=side*.025;if(r===ROLE.MG||r===ROLE.MEDIC||r===ROLE.MARKSMAN)tx+=side*.018;if(combatState[i]===STATE.SEEK_COVER){let best={x:tx,y:ty,score:-1e9};for(let k=0;k<8;k++){const a=k*Math.PI/4,cx=world.x[i]+Math.cos(a)*.035,cy=world.y[i]+Math.sin(a)*.035,score=coverAt(cx,cy,world.team[i])*100-Math.hypot(cx-sq.targetX,cy-sq.targetY)*30;if(score>best.score)best={x:cx,y:cy,score}}tx=best.x;ty=best.y}let mul=1;if([STATE.FIRE,STATE.AIM,STATE.SUPPRESS].includes(combatState[i]))mul=.04;else if(combatState[i]===STATE.PINNED)mul=.01;else if(combatState[i]===STATE.FALL_BACK||combatState[i]===STATE.ROUT)mul=1.25;if(p.state===PL.FIRE_BASE)mul*=.55;if(p.state===PL.RESERVE)mul*=.45;if(p.state===PL.ASSAULT)mul*=1.18;const dx=tx-world.x[i],dy=ty-world.y[i],d=Math.hypot(dx,dy);if(d<.0025)continue;const m=Math.min(step*mul*(.4+.6*morale[i]/100)*(1-Math.min(.82,suppression[i]/130)),d)/d;if(m>0)writes.push({entity:i,field:'x',value:clamp(world.x[i]+dx*m,-.98,.98),expectedVersion:s.version[i],expectedGeneration:s.generation[i]},{entity:i,field:'y',value:clamp(world.y[i]+dy*m,-.98,.98),expectedVersion:s.version[i],expectedGeneration:s.generation[i]})}activity.engaged=engaged;profiler.move=performance.now()-t0;return makeProposal({snapshot:s,systemId:'totalfront.p6-move',source:'platoon-ai',priority:120,writes,events:[],meta:{authority:true}})}
function combatProposal(s,sp){const t0=performance.now(),writes=[],events=[];activity={shots:0,hits:0,damage:0,engaged:activity.engaged,kills:0};combatFx=[];const addHP=(target,value,source,type)=>{writes.push({entity:target,field:'hp',op:'add',value,expectedVersion:s.version[target],expectedGeneration:s.generation[target]});events.push({type,source,target,value})};for(let i=0;i<count;i++)if(alive(i)){const r=role[i],wp=WEAPON[r],st=combatState[i];if(cooldown[i]>0)cooldown[i]--;if(healCooldown[i]>0)healCooldown[i]--;if(st===STATE.RELOAD&&ammo[i]===0){ammo[i]=Math.floor(wp.ammo*.35);cooldown[i]=8;continue}if(r===ROLE.MEDIC&&healCooldown[i]===0&&world.tick%5===0){let best=-1,bhp=101;for(const j of neighbors(i,sp,1))if(j!==i&&alive(j)&&world.team[j]===world.team[i]&&world.hp[j]<bhp&&world.hp[j]<60){best=j;bhp=world.hp[j]}if(best>=0){addHP(best,1.5,i,'medic');healCooldown[i]=15;continue}}if([STATE.PINNED,STATE.ROUT,STATE.FALL_BACK,STATE.SEEK_COVER].includes(st)||cooldown[i]>0||ammo[i]===0)continue;if(st===STATE.AIM){aimTicks[i]=1;continue}if(st!==STATE.FIRE&&st!==STATE.SUPPRESS)continue;const ac=acquireTarget(i,sp,wp.range);if(ac.entity<0)continue;const target=ac.entity,d=ac.distance;cooldown[i]=wp.cadence;ammo[i]--;activity.shots++;const cover=coverAt(world.x[target],world.y[target],world.team[target]),chance=clamp(wp.accuracy*(1-d/wp.range*.5)*(1-cover)*(1-Math.min(.7,suppression[i]/145)),.08,.94),hit=hash01(world.tick,i,target,ammo[i])<chance;aimTicks[i]=0;if(combatFx.length<180)combatFx.push({x1:world.x[i],y1:world.y[i],x2:world.x[target],y2:world.y[target],hit,mg:r===ROLE.MG});suppression[target]=Math.min(100,suppression[target]+wp.supp*(st===STATE.SUPPRESS?1.5:1)*(hit?1:.5));if(!hit)continue;activity.hits++;let dmg=wp.damage*(.9+.2*hash01(i,target,world.tick,1))*(1-cover*.65);if(st===STATE.SUPPRESS)dmg*=.78;addHP(target,-dmg,i,'fire');activity.damage+=dmg;morale[target]=Math.max(0,morale[target]-dmg*.08)}for(let i=0;i<count;i++)if(alive(i)){suppression[i]=Math.max(0,suppression[i]-.5);if(suppression[i]<18)morale[i]=Math.min(100,morale[i]+.018)}profiler.combat=performance.now()-t0;return makeProposal({snapshot:s,systemId:'totalfront.p6-combat',source:'role-ai',priority:220,writes,events,meta:{authority:true}})}
function updateHill(){const b=teamNearHill(0),r=teamNearHill(1);if(b>r*1.2&&b>8)hillHoldBlue++;else hillHoldBlue=Math.max(0,hillHoldBlue-1)}
function hillState(){const b=teamNearHill(0),r=teamNearHill(1);return b>r*1.35&&b>6?'BLUE CONTROL':r>b*1.35&&r>6?'RED CONTROL':'CONTESTED'}
function teamStats(team){let a=0,m=0,s=0,c=0;for(let i=0;i<count;i++)if(world.team[i]===team&&alive(i)){a++;m+=morale[i];s+=suppression[i];c+=cohesion[i]}return{alive:a,morale:a?m/a:0,supp:a?s/a:0,cohesion:a?c/a:0}}
function checkVictory(){if(battleOver)return;const b=teamStats(0),r=teamStats(1),half=count/2;if(hillHoldBlue>=100){winner='BLUE';battleOver=true}else if(b.alive<half*.12){winner='RED';battleOver=true}else if(r.alive<half*.12){winner='BLUE';battleOver=true}if(battleOver){running=false;battlePhase='COMPLETE';pushLog('VICTORY',`${winner} ชนะที่ tick ${world.tick}`)}}
function oneTick(){if(battleOver)return;const t0=performance.now(),s0=performance.now(),s=snapshot(world);profiler.snap=performance.now()-s0;const sp=buildSpatial(),move=movementProposal(s,sp),combat=combatProposal(s,sp),k0=performance.now(),resolved=resolveConflicts([move,combat]),v=verify(world,resolved,{critical:false});if(!v.ok){pushLog('ERROR',v.errors.slice(0,2).join(', '));running=false;return}commit(world,resolved,{verifierResult:v});profiler.commit=performance.now()-k0;profiler.writes=resolved.writes.length;profiler.conflicts=resolved.conflicts.length;profiler.last=performance.now()-t0;const deaths=[];for(let i=0;i<count;i++)if(world.hp[i]<=0&&world.active[i]){world.active[i]=0;deathFx.push({x:world.x[i],y:world.y[i],ttl:15});deaths.push(i)}activity.kills=deaths.length;updateHill();checkVictory();if(world.tick%25===0){const ps=new Array(8).fill(0);for(const p of hierarchy.platoons)ps[p.state]++;pushLog('P6 AI',`FB ${ps[PL.FIRE_BASE]} • MAN ${ps[PL.MANEUVER]} • ASSAULT ${ps[PL.ASSAULT]} • RSV ${ps[PL.RESERVE]} • COUNTER ${ps[PL.COUNTER]}`)}updateHUD()}
function roleCounts(){const out=new Array(8).fill(0);for(let i=0;i<count;i++)if(alive(i))out[role[i]]++;return out}
function updateHUD(){if(!world)return;const b=teamStats(0),r=teamStats(1),half=count/2,rc=roleCounts(),ps=new Array(8).fill(0);for(const p of hierarchy.platoons)ps[p.state]++;$('tick').textContent=world.tick.toLocaleString();$('entities').textContent=count.toLocaleString();$('alive').textContent=`${b.alive} / ${r.alive}`;$('tickMs').textContent=profiler.last.toFixed(2)+' ms';$('battlePhase').textContent=battlePhase;$('hash').textContent=String(stateHash(world)).slice(0,10);$('blueStrength').textContent=b.alive.toLocaleString();$('redStrength').textContent=r.alive.toLocaleString();$('blueBar').style.width=b.alive/half*100+'%';$('redBar').style.width=r.alive/half*100+'%';$('morale').textContent=`${b.morale.toFixed(1)} / ${r.morale.toFixed(1)}`;$('suppression').textContent=`${b.supp.toFixed(1)} / ${r.supp.toFixed(1)}`;$('cohesion').textContent=`${b.cohesion.toFixed(1)} / ${r.cohesion.toFixed(1)}`;$('hierarchy').textContent=`${hierarchy.battalions.length} BN • ${hierarchy.companies.length} CO • ${hierarchy.platoons.length} PL • ${hierarchy.squads.length} SQ`;$('hillControl').textContent=battleOver?`${winner} VICTORY`:hillState();$('rRifle').textContent=rc[0];$('rLeader').textContent=rc[1];$('rMG').textContent=rc[2];$('rMedic').textContent=rc[3];$('rMarksman').textContent=rc[4];$('rScout').textContent=rc[5];$('rGrenadier').textContent=rc[6];$('rEngineer').textContent=rc[7];$('roleActivity').textContent=`Shots ${activity.shots} • Hit ${activity.hits} • Dmg ${activity.damage.toFixed(0)} • WP ${weakPoint.active?weakPoint.score.toFixed(0):'-'} • PL FB ${ps[PL.FIRE_BASE]} / MAN ${ps[PL.MANEUVER]} / ASSAULT ${ps[PL.ASSAULT]} / COUNTER ${ps[PL.COUNTER]}`;$('pSnap').textContent=profiler.snap.toFixed(2);$('pSpatial').textContent=profiler.spatial.toFixed(2);$('pMove').textContent=profiler.move.toFixed(2);$('pCombat').textContent=profiler.combat.toFixed(2);$('pCommit').textContent=profiler.commit.toFixed(2);$('cells').textContent=profiler.cells;$('maxCell').textContent=profiler.maxCell;$('queries').textContent=profiler.queries.toLocaleString();$('candidates').textContent=profiler.candidates.toLocaleString();$('writes').textContent=profiler.writes.toLocaleString();$('conflicts').textContent=profiler.conflicts.toLocaleString()}
function draw(){if(!world)return;const w=canvas.width,h=canvas.height,sx=x=>(x+1)*.5*w,sy=y=>(y+1)*.5*h;ctx.clearRect(0,0,w,h);ctx.fillStyle='#0b1925';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1e3447';for(let x=0;x<=10;x++){ctx.beginPath();ctx.moveTo(x*w/10,0);ctx.lineTo(x*w/10,h);ctx.stroke()}for(let y=0;y<=8;y++){ctx.beginPath();ctx.moveTo(0,y*h/8);ctx.lineTo(w,y*h/8);ctx.stroke()}for(const t of TERRAIN){ctx.fillStyle=t.name.includes('FOREST')?'#294b36':'#5b4932';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(sx(t.x),sy(t.y),t.r*.5*w,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#c9d8c5';ctx.font='11px system-ui';ctx.fillText(t.name,sx(t.x),sy(t.y))}if(weakPoint.active){ctx.strokeStyle='#ffd166';ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(sx(.25),sy(weakPoint.y));ctx.lineTo(sx(.82),sy(weakPoint.y));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffd166';ctx.fillText(`WEAK POINT ${weakPoint.score.toFixed(0)}`,sx(.48),sy(weakPoint.y)-8)}ctx.fillStyle='#6c5934';ctx.beginPath();ctx.arc(sx(HILL.x),sy(0),HILL.r*.5*w,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e4c677';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText('▲ HILL 42',sx(HILL.x),sy(0)+6);for(const p of hierarchy.platoons){const st=unitStats(p);if(!st.alive)continue;ctx.strokeStyle=p.team===0?'#52bfff44':'#ff6b6b44';ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(sx(st.x),sy(st.y));ctx.lineTo(sx(p.targetX),sy(p.targetY));ctx.stroke();ctx.setLineDash([])}const stride=count>=10000?14:count>=5000?8:count>=2400?5:2;for(let i=0;i<count;i+=stride)if(alive(i)){ctx.fillStyle=combatState[i]===STATE.PINNED?'#ffd166':world.team[i]===0?'#52bfff':'#ff6b6b';ctx.fillRect(sx(world.x[i])-2,sy(world.y[i])-2,4,4)}for(const f of combatFx){ctx.strokeStyle=f.hit?(f.mg?'#ffb347':'#fff'):'#64727f55';ctx.beginPath();ctx.moveTo(sx(f.x1),sy(f.y1));ctx.lineTo(sx(f.x2),sy(f.y2));ctx.stroke()}deathFx=deathFx.filter(d=>--d.ttl>0);for(const d of deathFx){ctx.strokeStyle='#ffdd88aa';const x=sx(d.x),y=sy(d.y);ctx.beginPath();ctx.moveTo(x-4,y-4);ctx.lineTo(x+4,y+4);ctx.moveTo(x+4,y-4);ctx.lineTo(x-4,y+4);ctx.stroke()}if(battleOver){ctx.fillStyle='#02060bcc';ctx.fillRect(0,0,w,h);ctx.fillStyle=winner==='BLUE'?'#52bfff':'#ff6b6b';ctx.font='bold 42px system-ui';ctx.fillText(`${winner} VICTORY`,w/2,h/2)}}
function loop(now){const dt=now-last;last=now;if(running&&!benchRunning){acc+=dt*speed;let g=0;while(acc>=TICK_MS&&g<8){oneTick();acc-=TICK_MS;g++}}draw();requestAnimationFrame(loop)}
$('pause').onclick=()=>{running=!running&&!battleOver;$('pause').textContent=running?'⏸ PAUSE':'▶ RESUME'};$('speed').onclick=()=>{speed=speed===1?2:speed===2?4:speed===4?8:1;$('speed').textContent=`▶ ${speed}×`};$('reset').onclick=()=>{running=true;init(count)};$('scale').onclick=()=>{const sizes=[1200,2400,5000,10000],next=sizes[(sizes.indexOf(count)+1)%sizes.length];running=true;init(next);$('scale').textContent=`📈 ${sizes[(sizes.indexOf(next)+1)%sizes.length].toLocaleString()} ENTITIES`};$('doctrine').onclick=()=>{doctrine=doctrine==='BALANCED'?'AGGRESSIVE':doctrine==='AGGRESSIVE'?'CAUTIOUS':'BALANCED';$('doctrine').textContent=`🧠 Doctrine: ${doctrine}`};$('bench').onclick=async()=>{if(benchRunning)return;benchRunning=true;const was=running;running=false,start=performance.now(),startTick=world.tick;for(let i=0;i<300&&!battleOver;i++){oneTick();if(i%20===0)await new Promise(r=>setTimeout(r,0))}pushLog('BENCH',`${world.tick-startTick} ticks • ${((performance.now()-start)/Math.max(1,world.tick-startTick)).toFixed(2)} ms/tick`);running=was&&!battleOver;benchRunning=false};
init();requestAnimationFrame(loop);
