import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';
const $=id=>document.getElementById(id),canvas=$('battle'),ctx=canvas.getContext('2d');
const TICK_MS=100,SEED=4242,SQ_SIZE=10,PL_SIZE=30,CO_SIZE=90,BN_SIZE=270,CELL=.06;
const HILL={x:.58,y:0,r:.18},DEF={F:.35,M:.58,R:.75};
const ROLE={RIFLE:0,LEADER:1,MG:2,MEDIC:3,MARKSMAN:4,SCOUT:5,GRENADIER:6,ENGINEER:7};
const ST={ADV:0,COVER:1,AIM:2,FIRE:3,SUPPRESS:4,RELOAD:5,FALLBACK:6,PINNED:7,ROUT:8,WITHDRAW:9};
const SQ={ADV:0,ENGAGE:1,SUPPRESS:2,FLANK:3,DEFEND:4,FALLBACK:5,RESERVE:6,ASSAULT:7,WITHDRAW:8,SUPPORT:9};
const PL={ADV:0,FIREBASE:1,MANEUVER:2,ASSAULT:3,RESERVE:4,DEFEND:5,COUNTER:6,FALLBACK:7,WITHDRAW:8,REINFORCE:9,BLOCK:10,SUPPORT:11};
const W={0:{range:.15,opt:.105,dmg:8,acc:.72,cd:3,supp:6,ammo:90},1:{range:.15,opt:.105,dmg:7,acc:.74,cd:3,supp:6,ammo:90},2:{range:.19,opt:.14,dmg:5,acc:.64,cd:2,supp:17,ammo:180},3:{range:.12,opt:.08,dmg:4,acc:.60,cd:5,supp:3,ammo:45},4:{range:.23,opt:.18,dmg:18,acc:.86,cd:6,supp:5,ammo:50},5:{range:.18,opt:.13,dmg:6,acc:.78,cd:4,supp:4,ammo:70},6:{range:.16,opt:.11,dmg:7,acc:.70,cd:4,supp:8,ammo:70},7:{range:.14,opt:.10,dmg:7.5,acc:.68,cd:3,supp:6,ammo:80}};
const TERR=[{x:-.18,y:-.42,r:.16,c:.18,n:'FOREST'},{x:-.10,y:.40,r:.17,c:.20,n:'FOREST'},{x:.34,y:-.28,r:.13,c:.24,n:'FORWARD TRENCH'},{x:.36,y:.28,r:.13,c:.24,n:'FORWARD TRENCH'},{x:.55,y:-.14,r:.14,c:.36,n:'MAIN TRENCH'},{x:.57,y:.16,r:.14,c:.36,n:'MAIN TRENCH'},{x:.75,y:0,r:.13,c:.28,n:'RESERVE LINE'}];
let world,count=1200,running=true,speed=1,last=performance.now(),acc=0,bench=false,battleOver=false,winner='',doctrine='BALANCED';
let morale,supp,cohesion,role,squadId,platoonId,companyId,battalionId,cooldown,ammo,targetId,state,aim,healCd;
let h={battalions:[],companies:[],platoons:[],squads:[]},log=[],fx=[],deathFx=[],teamLinks=[];
let phase='DEPLOY',hillHold=0,weak={y:0,score:0,active:false},depth={forward:'HOLD',main:'HOLD',reserve:'READY'};
let act={shots:0,hits:0,damage:0,engaged:0,kills:0,supportMoves:0,focusFire:0,assists:0};
let prof={snap:0,spatial:0,move:0,combat:0,commit:0,writes:0,conflicts:0,last:0,cells:0,maxCell:0,queries:0,candidates:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rnd(a,b,c,d=0){let x=(SEED^(a*374761393)^(b*668265263)^(c*2246822519)^(d*3266489917))>>>0;x^=x>>>13;x=Math.imul(x,1274126177)>>>0;x^=x>>>16;return x/4294967296}
function alive(i){return i>=0&&i<count&&world.active[i]&&world.hp[i]>0}
function roleSlot(s){return s===0?ROLE.LEADER:s===1?ROLE.MEDIC:s===2?ROLE.MG:s===3?ROLE.GRENADIER:s===4?ROLE.SCOUT:s===5?ROLE.MARKSMAN:s===6?ROLE.ENGINEER:ROLE.RIFLE}
function push(type,text){log.push({tick:world?.tick||0,type,text});if(log.length>140)log.shift();$('log').innerHTML=log.slice(-18).reverse().map(x=>`<div class="entry"><b>${x.type}</b> • ${x.text}<div class="muted">tick ${x.tick}</div></div>`).join('')}
function cover(x,y,team){let c=0;for(const t of TERR)if(Math.hypot(x-t.x,y-t.y)<t.r)c=Math.max(c,t.c);if(team===1&&x>.30&&x<.80&&Math.abs(y)<.52)c=Math.max(c,.08);return c}
function init(n=count){count=n;world=createWorld({seed:SEED,count,density:.15,speed:0});morale=new Float32Array(n);supp=new Float32Array(n);cohesion=new Float32Array(n);role=new Uint8Array(n);state=new Uint8Array(n);aim=new Uint8Array(n);squadId=new Uint32Array(n);platoonId=new Uint32Array(n);companyId=new Uint32Array(n);battalionId=new Uint32Array(n);cooldown=new Uint8Array(n);ammo=new Uint16Array(n);targetId=new Int32Array(n);targetId.fill(-1);healCd=new Uint8Array(n);h={battalions:[],companies:[],platoons:[],squads:[]};log=[];fx=[];deathFx=[];teamLinks=[];hillHold=0;phase='DEPLOY';battleOver=false;winner='';weak={y:0,score:0,active:false};depth={forward:'HOLD',main:'HOLD',reserve:'READY'};const half=n>>1;build(0,0,half);build(1,half,n);for(let i=0;i<n;i++){const sq=h.squads[squadId[i]],team=i<half?0:1,slot=i-sq.start,row=Math.floor(slot/5),col=slot%5,side=team===0?-1:1;role[i]=roleSlot(slot%10);world.team[i]=team;world.active[i]=1;world.hp[i]=100;world.radius[i]=.0042;world.mass[i]=1;morale[i]=100;cohesion[i]=100;ammo[i]=W[role[i]].ammo;world.x[i]=sq.ax+side*col*.008;world.y[i]=sq.ay+(row-.5)*.014}world.tick=0;world.worldVersion=0;world.deltaLog.length=0;world.eventLog.length=0;push('SYSTEM',`Total Front P7.5 • Teamwork AI • ${n.toLocaleString()} entities`);push('TEAMWORK','เพิ่ม Shared Target / Buddy Support / Distress Response / Suppress-and-Move / Cross Support');draw();hud()}
function build(team,start,end){const side=team===0?-1:1,bnCount=Math.max(1,Math.ceil((end-start)/BN_SIZE));for(let b=0;b<bnCount;b++){const id=h.battalions.length,bs=start+b*BN_SIZE,be=Math.min(end,bs+BN_SIZE),lane=bnCount===1?0:-.68+b*(1.36/(bnCount-1));h.battalions.push({id,team,start:bs,end:be,homeX:side*.72,homeY:lane,targetX:team===0?-.48:HILL.x,targetY:lane,order:team===0?'ASSEMBLE':'DEFEND'});for(let c=0,cs=bs;cs<be;c++,cs+=CO_SIZE){const ce=Math.min(be,cs+CO_SIZE),cid=h.companies.length,cy=(c-1)*.08;h.companies.push({id:cid,team,battalionId:id,start:cs,end:ce,targetX:side*.58,targetY:lane+cy,distress:0});for(let p=0,ps=cs;ps<ce;p++,ps+=PL_SIZE){const pe=Math.min(ce,ps+PL_SIZE),pid=h.platoons.length,layer=team===1?(p===0?0:p===1?1:2):-1,px=team===0?side*.58:(layer===0?DEF.F:layer===1?DEF.M:DEF.R);h.platoons.push({id:pid,team,battalionId:id,companyId:cid,start:ps,end:pe,state:team===0?PL.ADV:(layer===2?PL.RESERVE:PL.DEFEND),layer,withdrawn:false,targetX:px,targetY:lane+cy+(p-1)*.05,sharedTarget:-1,distress:0,supporter:-1});for(let q=0,qs=ps;qs<pe;q++,qs+=SQ_SIZE){const qe=Math.min(pe,qs+SQ_SIZE),sid=h.squads.length,ay=lane+cy+(p-1)*.05+(q-1)*.022;h.squads.push({id:sid,team,battalionId:id,companyId:cid,platoonId:pid,start:qs,end:qe,ax:team===0?side*.72:px,ay,targetX:px,targetY:ay,state:team===0?SQ.ADV:(layer===2?SQ.RESERVE:SQ.DEFEND),sharedTarget:-1,distress:0});for(let i=qs;i<qe;i++){squadId[i]=sid;platoonId[i]=pid;companyId[i]=cid;battalionId[i]=id}}}}}}
function spatial(){const t=performance.now(),g=new Map();let mx=0;for(let i=0;i<count;i++)if(alive(i)){const cx=Math.floor(world.x[i]/CELL),cy=Math.floor(world.y[i]/CELL),k=cx+','+cy;let a=g.get(k);if(!a){a=[];g.set(k,a)}a.push(i);mx=Math.max(mx,a.length)}prof.spatial=performance.now()-t;prof.cells=g.size;prof.maxCell=mx;prof.queries=0;prof.candidates=0;return{g,cell:CELL}}
function near(i,sp,r=1){const cx=Math.floor(world.x[i]/sp.cell),cy=Math.floor(world.y[i]/sp.cell),o=[];prof.queries++;for(let x=-r;x<=r;x++)for(let y=-r;y<=r;y++){const a=sp.g.get((cx+x)+','+(cy+y));if(a){prof.candidates+=a.length;o.push(...a)}}return o}
function stats(u){let n=0,m=0,s=0,c=0,x=0,y=0;for(let i=u.start;i<u.end;i++)if(alive(i)){n++;m+=morale[i];s+=supp[i];c+=cohesion[i];x+=world.x[i];y+=world.y[i]}return{alive:n,morale:n?m/n:0,supp:n?s/n:0,cohesion:n?c/n:0,x:n?x/n:u.targetX,y:n?y/n:u.targetY,strength:n/Math.max(1,u.end-u.start)}}
function nearHill(team){let n=0;for(let i=0;i<count;i++)if(alive(i)&&world.team[i]===team&&Math.hypot(world.x[i]-HILL.x,world.y[i])<HILL.r)n++;return n}
function front(){let best={y:0,score:-1};for(let k=0;k<9;k++){const y=-.64+k*.16;let b=0,r=0,rs=0,rm=0;for(let i=0;i<count;i++)if(alive(i)&&Math.abs(world.y[i]-y)<.09&&world.x[i]>.20){if(world.team[i]===0)b++;else{r++;rs+=supp[i];rm+=morale[i]}}const score=(100-(r?rm/r:100))*.35+(r?rs/r:0)*.35+(b/(r+5))*22-r*.08;if(score>best.score)best={y,score}}weak={...best,active:best.score>40}}
function layerStats(layer){const ps=h.platoons.filter(p=>p.team===1&&p.layer===layer&&!p.withdrawn);if(!ps.length)return{strength:0,morale:0,supp:100,cohesion:0,count:0};let a=0,m=0,s=0,c=0;for(const p of ps){const q=stats(p);a+=q.strength;m+=q.morale;s+=q.supp;c+=q.cohesion}return{strength:a/ps.length,morale:m/ps.length,supp:s/ps.length,cohesion:c/ps.length,count:ps.length}}
function depthAI(){const f=layerStats(0),m=layerStats(1),fb=f.count&&(f.strength<.58||f.morale<46||f.supp>58||f.cohesion<45),mb=m.count&&(m.strength<.48||m.morale<36||m.supp>68||m.cohesion<35);depth.forward=fb?'WITHDRAW':'HOLD';depth.main=mb?'WITHDRAW':'HOLD';depth.reserve=weak.active?'BLOCK':(fb||mb?'REINFORCE':'READY');for(const p of h.platoons.filter(p=>p.team===1)){const st=stats(p);if(p.layer===0&&fb&&!p.withdrawn){p.state=PL.WITHDRAW;p.targetX=DEF.M+.015;p.withdrawn=true}else if(p.layer===1&&mb&&!p.withdrawn){p.state=PL.WITHDRAW;p.targetX=DEF.R-.015;p.withdrawn=true}else if(p.layer===2){if(weak.active){p.state=PL.BLOCK;p.targetX=HILL.x+.015;p.targetY=weak.y}else if(fb&&!mb){p.state=PL.REINFORCE;p.targetX=DEF.M+.03}else if(mb&&st.strength>.55&&st.morale>45){p.state=PL.COUNTER;p.targetX=HILL.x-.04}else{p.state=PL.RESERVE;p.targetX=DEF.R}}}}
function strategy(){front();const t=world.tick;if(t<20)phase='DEPLOY';else if(depth.main==='WITHDRAW')phase='DEFENSE COLLAPSE';else if(depth.forward==='WITHDRAW')phase='FIGHTING WITHDRAWAL';else if(weak.active)phase='BREAKTHROUGH';else phase='ENGAGEMENT';for(const bn of h.battalions){const s=stats(bn);if(bn.team===0){bn.order=s.strength<.28||s.morale<20?'RETREAT':(weak.active?'BREAKTHROUGH':'ATTACK');bn.targetX=bn.order==='RETREAT'?-.72:HILL.x-.02;bn.targetY=weak.active?weak.y:bn.homeY*.25}else{bn.order=s.strength<.22||s.morale<15?'FALLBACK':(weak.active?'BLOCK':'DEFEND');bn.targetX=bn.order==='FALLBACK'?.86:HILL.x;bn.targetY=weak.active?weak.y:bn.homeY*.30}}}
function attackerAI(){for(const co of h.companies.filter(c=>c.team===0)){const ps=h.platoons.filter(p=>p.companyId===co.id),ss=ps.map(stats);for(let i=0;i<ps.length;i++){const p=ps[i],s=ss[i],bn=h.battalions[p.battalionId];if(bn.order==='RETREAT'||s.morale<22){p.state=PL.FALLBACK;p.targetX=bn.homeX;p.targetY=bn.homeY+(i-1)*.06;continue}if(weak.active){p.state=i===0?PL.FIREBASE:i===1?PL.MANEUVER:PL.ASSAULT;p.targetX=i===0?HILL.x-.18:i===1?HILL.x-.04:HILL.x+.06;p.targetY=weak.y+(i-1)*.06}else{p.state=i===0?PL.FIREBASE:i===1?PL.MANEUVER:PL.RESERVE;p.targetX=i===0?HILL.x-.20:i===1?HILL.x-.06:HILL.x-.26;p.targetY=bn.targetY+(i-1)*.08}}}}
function teamworkAI(){teamLinks=[];for(const sq of h.squads){const s=stats(sq);sq.distress=clamp((100-s.morale)*.35+s.supp*.45+(1-s.strength)*45+(100-s.cohesion)*.18,0,100)}for(const p of h.platoons){const sqs=h.squads.filter(s=>s.platoonId===p.id),ps=stats(p);p.distress=clamp((100-ps.morale)*.30+ps.supp*.45+(1-ps.strength)*50+(100-ps.cohesion)*.16,0,100);let bestTarget=-1,bestVotes=-1;const votes=new Map();for(const sq of sqs){for(let i=sq.start;i<sq.end;i++){const t=targetId[i];if(t>=0&&alive(t)){votes.set(t,(votes.get(t)||0)+1)}}}for(const [t,v] of votes)if(v>bestVotes){bestVotes=v;bestTarget=t}p.sharedTarget=bestTarget;for(const sq of sqs)sq.sharedTarget=bestTarget}
 for(const co of h.companies){const ps=h.platoons.filter(p=>p.companyId===co.id);for(const needy of ps){if(needy.distress<48)continue;let helper=null,score=1e9;const ns=stats(needy);for(const cand of ps){if(cand.id===needy.id)continue;const cs=stats(cand);if(cand.distress>35||cs.strength<.55||cs.morale<45)continue;const d=Math.hypot(cs.x-ns.x,cs.y-ns.y);if(d<score){score=d;helper=cand}}if(helper&&helper.state!==PL.WITHDRAW&&helper.state!==PL.FALLBACK){helper.state=PL.SUPPORT;helper.supporter=needy.id;helper.targetX=ns.x+(helper.team===0?-.035:.035);helper.targetY=ns.y;act.supportMoves++;if(teamLinks.length<24)teamLinks.push({x1:stats(helper).x,y1:stats(helper).y,x2:ns.x,y2:ns.y,team:helper.team})}}
 }
}
function squadAI(){for(const sq of h.squads){const p=h.platoons[sq.platoonId],local=Math.floor((sq.start-p.start)/SQ_SIZE);sq.targetX=p.targetX+(sq.team===0?-1:1)*local*.012;sq.targetY=p.targetY+(local-1)*.024;if(p.state===PL.FIREBASE)sq.state=local===0?SQ.SUPPRESS:SQ.ENGAGE;else if(p.state===PL.MANEUVER)sq.state=local===0?SQ.SUPPRESS:SQ.FLANK;else if(p.state===PL.ASSAULT)sq.state=local===0?SQ.SUPPRESS:SQ.ASSAULT;else if(p.state===PL.RESERVE)sq.state=SQ.RESERVE;else if(p.state===PL.WITHDRAW)sq.state=SQ.WITHDRAW;else if(p.state===PL.SUPPORT)sq.state=local===0?SQ.SUPPRESS:SQ.SUPPORT;else if([PL.DEFEND,PL.COUNTER,PL.REINFORCE,PL.BLOCK].includes(p.state))sq.state=SQ.DEFEND;else if(p.state===PL.FALLBACK)sq.state=SQ.FALLBACK;else sq.state=SQ.ADV}}
function acquire(i,sp,range){const sq=h.squads[squadId[i]],p=h.platoons[platoonId[i]],shared=sq.sharedTarget>=0?sq.sharedTarget:p.sharedTarget;if(shared>=0&&alive(shared)&&world.team[shared]!==world.team[i]){const d=Math.hypot(world.x[shared]-world.x[i],world.y[shared]-world.y[i]);if(d<=range){targetId[i]=shared;act.focusFire++;return{entity:shared,distance:d}}}let best=-1,bd=999;for(const j of near(i,sp,Math.max(1,Math.ceil(range/sp.cell)))){if(j===i||!alive(j)||world.team[j]===world.team[i])continue;const d=Math.hypot(world.x[j]-world.x[i],world.y[j]-world.y[i]);if(d<bd&&d<=range){best=j;bd=d}}targetId[i]=best;return{entity:best,distance:bd}}
function localSupport(i,sp){let allies=0,leaders=0;for(const j of near(i,sp,1)){if(j===i||!alive(j)||world.team[j]!==world.team[i])continue;if(Math.hypot(world.x[j]-world.x[i],world.y[j]-world.y[i])<.075){allies++;if(role[j]===ROLE.LEADER)leaders++}}return{allies,leaders,isolated:allies<2}}
function choose(i,has,d,sp){const sq=h.squads[squadId[i]],wp=W[role[i]],ls=localSupport(i,sp);if(sq.state===SQ.FALLBACK||morale[i]<12)return ST.ROUT;if(sq.state===SQ.WITHDRAW&&morale[i]>=25)return ST.WITHDRAW;if(morale[i]<25)return ST.FALLBACK;if(supp[i]>80)return ST.PINNED;if(supp[i]>52)return ST.COVER;if(ammo[i]===0)return ST.RELOAD;if(!has)return ST.ADV;if(role[i]===ROLE.MG&&(sq.state===SQ.SUPPRESS||sq.state===SQ.DEFEND||sq.state===SQ.SUPPORT))return ST.SUPPRESS;if((sq.state===SQ.FLANK||sq.state===SQ.ASSAULT)&&ls.allies<3&&d<wp.range*.9)return ST.COVER;if(d>wp.opt*1.08)return ST.ADV;if(aim[i]<1)return ST.AIM;return ST.FIRE}
function moveProposal(s,sp){const t=performance.now();if(world.tick%5===0){strategy();depthAI();attackerAI();teamworkAI()}squadAI();const writes=[],step=.0095;let engaged=0;for(let i=0;i<count;i++)if(alive(i)){const sq=h.squads[squadId[i]],p=h.platoons[platoonId[i]],slot=i-sq.start,row=Math.floor(slot/5),col=slot%5,side=world.team[i]===0?-1:1,r=role[i],wp=W[r],ac=acquire(i,sp,wp.range*1.08),has=ac.entity>=0;if(has)engaged++;state[i]=choose(i,has,ac.distance,sp);let tx=sq.targetX+side*col*.007,ty=sq.targetY+(row-.5)*.012;if(r===ROLE.SCOUT)tx-=side*.025;if(r===ROLE.MG||r===ROLE.MEDIC||r===ROLE.MARKSMAN)tx+=side*.018;if(state[i]===ST.COVER){let best={x:tx,y:ty,score:-1e9};for(let k=0;k<8;k++){const a=k*Math.PI/4,cx=world.x[i]+Math.cos(a)*.035,cy=world.y[i]+Math.sin(a)*.035,score=cover(cx,cy,world.team[i])*100-Math.hypot(cx-sq.targetX,cy-sq.targetY)*30;if(score>best.score)best={x:cx,y:cy,score}}tx=best.x;ty=best.y}let mul=1;if([ST.FIRE,ST.AIM,ST.SUPPRESS].includes(state[i]))mul=.04;else if(state[i]===ST.PINNED)mul=.01;else if(state[i]===ST.WITHDRAW)mul=.88;else if(state[i]===ST.FALLBACK||state[i]===ST.ROUT)mul=1.25;if(p.state===PL.FIREBASE)mul*=.55;if(p.state===PL.RESERVE)mul*=.45;if(p.state===PL.ASSAULT)mul*=1.18;if([PL.REINFORCE,PL.BLOCK,PL.SUPPORT].includes(p.state))mul*=1.10;const dx=tx-world.x[i],dy=ty-world.y[i],d=Math.hypot(dx,dy);if(d<.0025)continue;const m=Math.min(step*mul*(.4+.6*morale[i]/100)*(1-Math.min(.82,supp[i]/130)),d)/d;if(m>0)writes.push({entity:i,field:'x',value:clamp(world.x[i]+dx*m,-.98,.98),expectedVersion:s.version[i],expectedGeneration:s.generation[i]},{entity:i,field:'y',value:clamp(world.y[i]+dy*m,-.98,.98),expectedVersion:s.version[i],expectedGeneration:s.generation[i]})}act.engaged=engaged;prof.move=performance.now()-t;return makeProposal({snapshot:s,systemId:'totalfront.team-move',source:'teamwork-ai',priority:120,writes,events:[],meta:{authority:true}})}
function combatProposal(s,sp){const t=performance.now(),writes=[],events=[];act={...act,shots:0,hits:0,damage:0,kills:0,focusFire:0,assists:0};fx=[];const hp=(target,value,source,type)=>{writes.push({entity:target,field:'hp',op:'add',value,expectedVersion:s.version[target],expectedGeneration:s.generation[target]});events.push({type,source,target,value})};for(let i=0;i<count;i++)if(alive(i)){const r=role[i],wp=W[r],st=state[i],support=localSupport(i,sp);if(cooldown[i]>0)cooldown[i]--;if(healCd[i]>0)healCd[i]--;if(st===ST.RELOAD&&ammo[i]===0){ammo[i]=Math.floor(wp.ammo*.35);cooldown[i]=8;continue}if(r===ROLE.LEADER&&world.tick%5===0){const sq=h.squads[squadId[i]];for(let j=sq.start;j<sq.end;j++)if(alive(j)){morale[j]=Math.min(100,morale[j]+.18);cohesion[j]=Math.min(100,cohesion[j]+.22)}}if(r===ROLE.MEDIC&&healCd[i]===0&&world.tick%5===0){let best=-1,bhp=101;const sq=h.squads[squadId[i]];for(let j=sq.start;j<sq.end;j++)if(alive(j)&&world.hp[j]<bhp&&world.hp[j]<70){best=j;bhp=world.hp[j]}if(best<0)for(const j of near(i,sp,1))if(j!==i&&alive(j)&&world.team[j]===world.team[i]&&world.hp[j]<bhp&&world.hp[j]<55){best=j;bhp=world.hp[j]}if(best>=0){hp(best,1.8,i,'medic');healCd[i]=12;act.assists++;continue}}if([ST.PINNED,ST.ROUT,ST.FALLBACK,ST.COVER,ST.WITHDRAW].includes(st)||cooldown[i]>0||ammo[i]===0)continue;if(st===ST.AIM){aim[i]=1;continue}if(st!==ST.FIRE&&st!==ST.SUPPRESS)continue;const ac=acquire(i,sp,wp.range);if(ac.entity<0)continue;const target=ac.entity,d=ac.distance;cooldown[i]=wp.cd;ammo[i]--;act.shots++;const cv=cover(world.x[target],world.y[target],world.team[target]),teamBonus=clamp(1+Math.min(.12,support.allies*.012)+support.leaders*.03,1,1.18),isolation=support.isolated?.88:1,chance=clamp(wp.acc*(1-d/wp.range*.5)*(1-cv)*(1-Math.min(.7,supp[i]/145))*teamBonus*isolation,.08,.94),hit=rnd(world.tick,i,target,ammo[i])<chance;aim[i]=0;if(fx.length<180)fx.push({x1:world.x[i],y1:world.y[i],x2:world.x[target],y2:world.y[target],hit,mg:r===ROLE.MG});supp[target]=Math.min(100,supp[target]+wp.supp*(st===ST.SUPPRESS?1.5:1)*(hit?1:.5));if(!hit)continue;act.hits++;let dmg=wp.dmg*(.9+.2*rnd(i,target,world.tick,1))*(1-cv*.65)*(support.allies>=4?1.05:1);if(st===ST.SUPPRESS)dmg*=.78;hp(target,-dmg,i,'fire');act.damage+=dmg;morale[target]=Math.max(0,morale[target]-dmg*.08);cohesion[target]=Math.max(0,cohesion[target]-dmg*.025)}for(let i=0;i<count;i++)if(alive(i)){const ls=localSupport(i,sp);supp[i]=Math.max(0,supp[i]-(ls.allies>=3?.62:.48));if(supp[i]<18){morale[i]=Math.min(100,morale[i]+(ls.allies>=3?.045:.018));cohesion[i]=Math.min(100,cohesion[i]+(ls.allies>=3?.06:.025))}if(ls.isolated){morale[i]=Math.max(0,morale[i]-.015);cohesion[i]=Math.max(0,cohesion[i]-.02)}}prof.combat=performance.now()-t;return makeProposal({snapshot:s,systemId:'totalfront.team-combat',source:'cooperative-combat',priority:220,writes,events,meta:{authority:true}})}
function updateHill(){const b=nearHill(0),r=nearHill(1);if(b>r*1.2&&b>8)hillHold++;else hillHold=Math.max(0,hillHold-1)}
function hillState(){const b=nearHill(0),r=nearHill(1);return b>r*1.35&&b>6?'BLUE CONTROL':r>b*1.35&&r>6?'RED CONTROL':'CONTESTED'}
function teamStats(team){let a=0,m=0,s=0,c=0;for(let i=0;i<count;i++)if(world.team[i]===team&&alive(i)){a++;m+=morale[i];s+=supp[i];c+=cohesion[i]}return{alive:a,morale:a?m/a:0,supp:a?s/a:0,cohesion:a?c/a:0}}
function victory(){if(battleOver)return;const b=teamStats(0),r=teamStats(1),half=count/2;if(hillHold>=100){winner='BLUE';battleOver=true}else if(b.alive<half*.12){winner='RED';battleOver=true}else if(r.alive<half*.12){winner='BLUE';battleOver=true}if(battleOver){running=false;phase='COMPLETE';push('VICTORY',`${winner} ชนะที่ tick ${world.tick}`)}}
function tick(){if(battleOver)return;const t=performance.now(),s0=performance.now(),s=snapshot(world);prof.snap=performance.now()-s0;const sp=spatial(),mv=moveProposal(s,sp),cb=combatProposal(s,sp),k=performance.now(),res=resolveConflicts([mv,cb]),v=verify(world,res,{critical:false});if(!v.ok){push('ERROR',v.errors.slice(0,2).join(', '));running=false;return}commit(world,res,{verifierResult:v});prof.commit=performance.now()-k;prof.writes=res.writes.length;prof.conflicts=res.conflicts.length;prof.last=performance.now()-t;const dead=[];for(let i=0;i<count;i++)if(world.hp[i]<=0&&world.active[i]){world.active[i]=0;deathFx.push({x:world.x[i],y:world.y[i],ttl:15});dead.push(i)}act.kills=dead.length;updateHill();victory();if(world.tick%25===0){let sup=0,iso=0;for(const p of h.platoons)if(p.state===PL.SUPPORT)sup++;for(let i=0;i<count;i++)if(alive(i)){let n=0;const sq=h.squads[squadId[i]];for(let j=sq.start;j<sq.end;j++)if(j!==i&&alive(j))n++;if(n<2)iso++}push('TEAMWORK',`Support platoons ${sup} • shared-focus ${act.focusFire} • support moves ${act.supportMoves} • isolated ${iso}`)}hud()}
function roles(){const o=new Array(8).fill(0);for(let i=0;i<count;i++)if(alive(i))o[role[i]]++;return o}
function hud(){if(!world)return;const b=teamStats(0),r=teamStats(1),half=count/2,rc=roles(),supporters=h.platoons.filter(p=>p.state===PL.SUPPORT).length;$('tick').textContent=world.tick.toLocaleString();$('entities').textContent=count.toLocaleString();$('alive').textContent=`${b.alive} / ${r.alive}`;$('tickMs').textContent=prof.last.toFixed(2)+' ms';$('battlePhase').textContent=phase;$('hash').textContent=String(stateHash(world)).slice(0,10);$('blueStrength').textContent=b.alive.toLocaleString();$('redStrength').textContent=r.alive.toLocaleString();$('blueBar').style.width=b.alive/half*100+'%';$('redBar').style.width=r.alive/half*100+'%';$('morale').textContent=`${b.morale.toFixed(1)} / ${r.morale.toFixed(1)}`;$('suppression').textContent=`${b.supp.toFixed(1)} / ${r.supp.toFixed(1)}`;$('cohesion').textContent=`${b.cohesion.toFixed(1)} / ${r.cohesion.toFixed(1)}`;$('hierarchy').textContent=`${h.battalions.length} BN • ${h.companies.length} CO • ${h.platoons.length} PL • ${h.squads.length} SQ`;$('hillControl').textContent=battleOver?`${winner} VICTORY`:hillState();$('rRifle').textContent=rc[0];$('rLeader').textContent=rc[1];$('rMG').textContent=rc[2];$('rMedic').textContent=rc[3];$('rMarksman').textContent=rc[4];$('rScout').textContent=rc[5];$('rGrenadier').textContent=rc[6];$('rEngineer').textContent=rc[7];$('roleActivity').textContent=`Shots ${act.shots} • Hit ${act.hits} • Team focus ${act.focusFire} • Support PL ${supporters} • Med/Assist ${act.assists} • RED F:${depth.forward} M:${depth.main}`;$('pSnap').textContent=prof.snap.toFixed(2);$('pSpatial').textContent=prof.spatial.toFixed(2);$('pMove').textContent=prof.move.toFixed(2);$('pCombat').textContent=prof.combat.toFixed(2);$('pCommit').textContent=prof.commit.toFixed(2);$('cells').textContent=prof.cells;$('maxCell').textContent=prof.maxCell;$('queries').textContent=prof.queries.toLocaleString();$('candidates').textContent=prof.candidates.toLocaleString();$('writes').textContent=prof.writes.toLocaleString();$('conflicts').textContent=prof.conflicts.toLocaleString()}
function draw(){if(!world)return;const w=canvas.width,hg=canvas.height,sx=x=>(x+1)*.5*w,sy=y=>(y+1)*.5*hg;ctx.clearRect(0,0,w,hg);ctx.fillStyle='#0b1925';ctx.fillRect(0,0,w,hg);ctx.strokeStyle='#1e3447';for(let x=0;x<=10;x++){ctx.beginPath();ctx.moveTo(x*w/10,0);ctx.lineTo(x*w/10,hg);ctx.stroke()}for(let y=0;y<=8;y++){ctx.beginPath();ctx.moveTo(0,y*hg/8);ctx.lineTo(w,y*hg/8);ctx.stroke()}for(const [n,xv] of [['FORWARD',DEF.F],['MAIN',DEF.M],['RESERVE',DEF.R]]){ctx.strokeStyle=n==='MAIN'?'#ffb36a88':'#ff6b6b55';ctx.setLineDash([6,6]);ctx.beginPath();ctx.moveTo(sx(xv),sy(-.62));ctx.lineTo(sx(xv),sy(.62));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffb6b6';ctx.font='11px system-ui';ctx.fillText(n,sx(xv)+4,sy(-.58))}for(const t of TERR){ctx.fillStyle=t.n.includes('FOREST')?'#294b36':'#5b4932';ctx.globalAlpha=.65;ctx.beginPath();ctx.arc(sx(t.x),sy(t.y),t.r*.5*w,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#c9d8c5';ctx.fillText(t.n,sx(t.x),sy(t.y))}if(weak.active){ctx.strokeStyle='#ffd166';ctx.setLineDash([8,5]);ctx.beginPath();ctx.moveTo(sx(.25),sy(weak.y));ctx.lineTo(sx(.84),sy(weak.y));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#ffd166';ctx.fillText(`WEAK ${weak.score.toFixed(0)}`,sx(.48),sy(weak.y)-8)}ctx.fillStyle='#6c5934';ctx.beginPath();ctx.arc(sx(HILL.x),sy(0),HILL.r*.5*w,0,Math.PI*2);ctx.fill();ctx.fillStyle='#e4c677';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText('▲ HILL 42',sx(HILL.x),sy(0)+6);for(const l of teamLinks){ctx.strokeStyle=l.team===0?'#58dfa088':'#ff9f4388';ctx.lineWidth=2;ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(sx(l.x1),sy(l.y1));ctx.lineTo(sx(l.x2),sy(l.y2));ctx.stroke();ctx.setLineDash([])}for(const p of h.platoons){const stt=stats(p);if(!stt.alive)continue;ctx.strokeStyle=p.state===PL.SUPPORT?'#58dfa099':(p.team===0?'#52bfff44':'#ff6b6b44');ctx.setLineDash([3,4]);ctx.beginPath();ctx.moveTo(sx(stt.x),sy(stt.y));ctx.lineTo(sx(p.targetX),sy(p.targetY));ctx.stroke();ctx.setLineDash([])}const stride=count>=10000?14:count>=5000?8:count>=2400?5:2;for(let i=0;i<count;i+=stride)if(alive(i)){ctx.fillStyle=state[i]===ST.PINNED?'#ffd166':world.team[i]===0?'#52bfff':'#ff6b6b';ctx.fillRect(sx(world.x[i])-2,sy(world.y[i])-2,4,4)}for(const f of fx){ctx.strokeStyle=f.hit?(f.mg?'#ffb347':'#fff'):'#64727f55';ctx.beginPath();ctx.moveTo(sx(f.x1),sy(f.y1));ctx.lineTo(sx(f.x2),sy(f.y2));ctx.stroke()}deathFx=deathFx.filter(d=>--d.ttl>0);for(const d of deathFx){ctx.strokeStyle='#ffdd88aa';const x=sx(d.x),y=sy(d.y);ctx.beginPath();ctx.moveTo(x-4,y-4);ctx.lineTo(x+4,y+4);ctx.moveTo(x+4,y-4);ctx.lineTo(x-4,y+4);ctx.stroke()}if(battleOver){ctx.fillStyle='#02060bcc';ctx.fillRect(0,0,w,hg);ctx.fillStyle=winner==='BLUE'?'#52bfff':'#ff6b6b';ctx.font='bold 42px system-ui';ctx.fillText(`${winner} VICTORY`,w/2,hg/2)}}
function loop(now){const dt=now-last;last=now;if(running&&!bench){acc+=dt*speed;let g=0;while(acc>=TICK_MS&&g<8){tick();acc-=TICK_MS;g++}}draw();requestAnimationFrame(loop)}
$('pause').onclick=()=>{running=!running&&!battleOver;$('pause').textContent=running?'⏸ PAUSE':'▶ RESUME'};$('speed').onclick=()=>{speed=speed===1?2:speed===2?4:speed===4?8:1;$('speed').textContent=`▶ ${speed}×`};$('reset').onclick=()=>{running=true;init(count)};$('scale').onclick=()=>{const sizes=[1200,2400,5000,10000],next=sizes[(sizes.indexOf(count)+1)%sizes.length];running=true;init(next);$('scale').textContent=`📈 ${sizes[(sizes.indexOf(next)+1)%sizes.length].toLocaleString()} ENTITIES`};$('doctrine').onclick=()=>{doctrine=doctrine==='BALANCED'?'AGGRESSIVE':doctrine==='AGGRESSIVE'?'CAUTIOUS':'BALANCED';$('doctrine').textContent=`🧠 Doctrine: ${doctrine}`};$('bench').onclick=async()=>{if(bench)return;bench=true;const was=running;running=false,start=performance.now(),st=world.tick;for(let i=0;i<300&&!battleOver;i++){tick();if(i%20===0)await new Promise(r=>setTimeout(r,0))}push('BENCH',`${world.tick-st} ticks • ${((performance.now()-start)/Math.max(1,world.tick-st)).toFixed(2)} ms/tick`);running=was&&!battleOver;bench=false};
init();requestAnimationFrame(loop);