import {createWorld,snapshot,makeProposal,resolveConflicts,verify,commit,stateHash} from '../../src/twa-core.js';
const $=id=>document.getElementById(id),canvas=$('battle'),ctx=canvas.getContext('2d');
const TICK_MS=100,SEED=4242,SQUAD_SIZE=10,COMPANY_SIZE=100,BATTALION_SIZE=300,SPATIAL_CELL=.06;
const ROLE={RIFLE:0,LEADER:1,MG:2,MEDIC:3,MARKSMAN:4,SCOUT:5,GRENADIER:6,ENGINEER:7};
const STATE={ADVANCE:0,SEEK_COVER:1,AIM:2,FIRE:3,SUPPRESS:4,RELOAD:5,TREAT:6,FALL_BACK:7,PINNED:8,ROUT:9};
const SQUAD_STATE={ADVANCE:0,ENGAGE:1,SUPPRESS:2,FLANK:3,DEFEND:4,FALLBACK:5};
const WEAPON={0:{range:.15,optimal:.105,damage:8,accuracy:.72,cadence:3,supp:6,ammo:90},1:{range:.15,optimal:.105,damage:7,accuracy:.74,cadence:3,supp:6,ammo:90},2:{range:.19,optimal:.14,damage:5,accuracy:.64,cadence:2,supp:17,ammo:180},3:{range:.12,optimal:.08,damage:4,accuracy:.60,cadence:5,supp:3,ammo:45},4:{range:.23,optimal:.18,damage:18,accuracy:.86,cadence:6,supp:5,ammo:50},5:{range:.18,optimal:.13,damage:6,accuracy:.78,cadence:4,supp:4,ammo:70},6:{range:.16,optimal:.11,damage:7,accuracy:.70,cadence:4,supp:8,ammo:70},7:{range:.14,optimal:.10,damage:7.5,accuracy:.68,cadence:3,supp:6,ammo:80}};
const TERRAIN=[{x:-.18,y:-.42,r:.16,cover:.18,name:'FOREST'},{x:-.12,y:.38,r:.18,cover:.22,name:'FOREST'},{x:.12,y:-.12,r:.13,cover:.28,name:'TRENCH'},{x:.14,y:.25,r:.12,cover:.30,name:'TRENCH'}];
let world,count=1200,running=true,speed=1,last=performance.now(),acc=0,benchRunning=false,doctrine='BALANCED',battleOver=false,winner='';
let morale,suppression,cohesion,role,squadId,companyId,battalionId,cooldown,ammo,targetId,healCooldown,combatState,aimTicks;
let hierarchy={battalions:[],companies:[],squads:[]},log=[],combatFx=[],deathFx=[];let battlePhase='DEPLOY',hillHoldBlue=0,hillHoldRed=0;
let activity={shots:0,hits:0,misses:0,heals:0,grenades:0,mgBursts:0,engaged:0,kills:0,damage:0};let profiler={snap:0,spatial:0,move:0,combat:0,commit:0,writes:0,conflicts:0,last:0,cells:0,maxCell:0,queries:0,candidates:0};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));function hash01(a,b,c,d=0){let x=(SEED^(a*374761393)^(b*668265263)^(c*2246822519)^(d*3266489917))>>>0;x^=x>>>13;x=Math.imul(x,1274126177)>>>0;x^=x>>>16;return x/4294967296}function alive(i){return i>=0&&i<count&&world.active[i]&&world.hp[i]>0}function roleForSlot(s){return s===0?1:s===1?3:s===2?2:s===3?6:s===4?5:s===5?4:s===6?7:0}
function pushLog(type,text){log.push({tick:world?.tick||0,type,text});if(log.length>90)log.shift();$('log').innerHTML=log.slice(-16).reverse().map(x=>`<div class="entry"><b>${x.type==='CONTACT'?'⚔️ ':''}${x.type}</b> • ${x.text}<div class="muted">tick ${x.tick}</div></div>`).join('')}
function coverAt(x,y,team){let c=0;for(const t of TERRAIN)if(Math.hypot(x-t.x,y-t.y)<t.r)c=Math.max(c,t.cover);if(team===1&&x>.02&&Math.abs(y)<.55)c=Math.max(c,.10);return c}
function init(n=count){count=n;world=createWorld({seed:SEED,count,density:.15,speed:0});morale=new Float32Array(count);suppression=new Float32Array(count);cohesion=new Float32Array(count);role=new Uint8Array(count);combatState=new Uint8Array(count);aimTicks=new Uint8Array(count);squadId=new Uint32Array(count);companyId=new Uint32Array(count);battalionId=new Uint32Array(count);cooldown=new Uint8Array(count);ammo=new Uint16Array(count);targetId=new Int32Array(count);targetId.fill(-1);healCooldown=new Uint8Array(count);hierarchy={battalions:[],companies:[],squads:[]};log=[];combatFx=[];deathFx=[];hillHoldBlue=hillHoldRed=0;battlePhase='DEPLOY';battleOver=false;winner='';activity={shots:0,hits:0,misses:0,heals:0,grenades:0,mgBursts:0,engaged:0,kills:0,damage:0};const half=count>>1;buildHierarchy(0,0,half);buildHierarchy(1,half,count);for(let i=0;i<count;i++){const team=i<half?0:1,sq=hierarchy.squads[squadId[i]],slot=i-sq.start,row=Math.floor(slot/5),col=slot%5,side=team===0?-1:1;role[i]=roleForSlot(slot%10);world.team[i]=team;world.active[i]=1;world.hp[i]=100;world.radius[i]=.0042;world.mass[i]=1;world.type[i]=role[i]+1;morale[i]=100;cohesion[i]=100;ammo[i]=WEAPON[role[i]].ammo;world.x[i]=sq.anchorX+side*col*.008;world.y[i]=sq.anchorY+(row-.5)*.014+(((i*97)%101)/101-.5)*.002}world.tick=0;world.worldVersion=0;world.deltaLog.length=0;world.eventLog.length=0;profiler={snap:0,spatial:0,move:0,combat:0,commit:0,writes:0,conflicts:0,last:0,cells:0,maxCell:0,queries:0,candidates:0};pushLog('SYSTEM',`Total Front P3 • Infantry AI + Terrain + Objective • ${count.toLocaleString()} entities`);pushLog('MISSION','BLUE ต้องยึด Hill 42 และคุมพื้นที่ 10 วินาที • RED ต้องหยุดการบุก');draw();updateHUD()}
function buildHierarchy(team,start,end){const side=team===0?-1:1,total=end-start,bnCount=Math.max(1,Math.ceil(total/300));for(let b=0;b<bnCount;b++){const id=hierarchy.battalions.length,bs=start+b*300,be=Math.min(end,bs+300),lane=bnCount===1?0:-.68+b*(1.36/(bnCount-1));hierarchy.battalions.push({id,team,start:bs,end:be,homeX:side*.72,homeY:lane,targetX:team===0?-.5:.13,targetY:lane,order:team===0?'ASSEMBLE':'DEFEND',damageDone:0,losses:0});const coCount=Math.ceil((be-bs)/100);for(let c=0;c<coCount;c++){const coId=hierarchy.companies.length,cs=bs+c*100,ce=Math.min(be,cs+100),coY=(c-(coCount-1)/2)*.075;hierarchy.companies.push({id:coId,team,battalionId:id,start:cs,end:ce,offsetY:coY});for(let q=0;q<Math.ceil((ce-cs)/10);q++){const sqId=hierarchy.squads.length,qs=cs+q*10,qe=Math.min(ce,qs+10),qr=Math.floor(q/5),qc=q%5;hierarchy.squads.push({id:sqId,team,battalionId:id,companyId:coId,start:qs,end:qe,anchorX:side*.72+side*(c*.032+qc*.013),anchorY:lane+coY+(qr-.5)*.025,targetX:side*.58,targetY:lane,state:0,contact:-1});for(let i=qs;i<qe;i++){squadId[i]=sqId;companyId[i]=coId;battalionId[i]=id}}}}}
function buildSpatial(){const t0=performance.now(),g=new Map();let maxCell=0;for(let i=0;i<count;i++)if(alive(i)){const cx=Math.floor(world.x[i]/SPATIAL_CELL),cy=Math.floor(world.y[i]/SPATIAL_CELL),k=cx+','+cy;let b=g.get(k);if(!b){b=[];g.set(k,b)}b.push(i);maxCell=Math.max(maxCell,b.length)}profiler.spatial=performance.now()-t0;profiler.cells=g.size;profiler.maxCell=maxCell;profiler.queries=0;profiler.candidates=0;return{g,cell:SPATIAL_CELL}}
function neighbors(i,sp,rings=1){const cx=Math.floor(world.x[i]/sp.cell),cy=Math.floor(world.y[i]/sp.cell),out=[];profiler.queries++;for(let ox=-rings;ox<=rings;ox++)for(let oy=-rings;oy<=rings;oy++){const b=sp.g.get((cx+ox)+','+(cy+oy));if(b){profiler.candidates+=b.length;out.push(...b)}}return out}
function battalionStats(bn){let n=0,m=0,s=0,c=0,x=0,y=0;for(let i=bn.start;i<bn.end;i++)if(alive(i)){n++;m+=morale[i];s+=suppression[i];c+=cohesion[i];x+=world.x[i];y+=world.y[i]}return{alive:n,morale:n?m/n:0,supp:n?s/n:0,cohesion:n?c/n:0,x:n?x/n:bn.homeX,y:n?y/n:bn.homeY,strength:n/Math.max(1,bn.end-bn.start)}}function teamNearHill(team){let n=0;for(let i=0;i<count;i++)if(alive(i)&&world.team[i]===team&&Math.hypot(world.x[i],world.y[i])<.18)n++;return n}function modeOf(a){const m=new Map();for(const x of a)m.set(x,(m.get(x)||0)+1);return[...m].sort((a,b)=>b[1]-a[1])[0]?.[0]||'-'}
function autonomousCommand(){const tick=world.tick;if(tick<18)battlePhase='DEPLOY';else if(tick<55)battlePhase='ADVANCE';else battlePhase='ENGAGEMENT';const blueCount=hierarchy.battalions.filter(b=>b.team===0).length;for(const bn of hierarchy.battalions){const st=battalionStats(bn),local=bn.team===0?bn.id:bn.id-blueCount,laneBias=((local%3)-1)*.08;if(bn.team===0){if(st.strength<.30||st.morale<20){bn.order='RETREAT';bn.targetX=-.72;bn.targetY=bn.homeY}else if(tick<18){bn.order='ASSEMBLE';bn.targetX=-.50;bn.targetY=bn.homeY}else{bn.order=doctrine==='AGGRESSIVE'?'ASSAULT':doctrine==='CAUTIOUS'?'BOUND_ADVANCE':'ATTACK';bn.targetX=.025;bn.targetY=clamp(bn.homeY*.27+laneBias,-.58,.58)}}else{const pressure=teamNearHill(0)>12;if(st.strength<.27||st.morale<17){bn.order='FALLBACK';bn.targetX=.62;bn.targetY=bn.homeY}else if(pressure&&st.morale>50&&local%3===0){bn.order='COUNTER';bn.targetX=0;bn.targetY=bn.homeY*.18}else{bn.order='DEFEND';bn.targetX=.10+(local%2)*.025;bn.targetY=clamp(bn.homeY*.40,-.56,.56)}}}if(tick%50===0)pushLog('AI PLAN',`BLUE ${modeOf(hierarchy.battalions.filter(b=>b.team===0).map(b=>b.order))} • RED ${modeOf(hierarchy.battalions.filter(b=>b.team===1).map(b=>b.order))}`)}
function updateSquadTargets(){for(const sq of hierarchy.squads){const bn=hierarchy.battalions[sq.battalionId],co=hierarchy.companies[sq.companyId],side=sq.team===0?-1:1,local=Math.floor((sq.start-co.start)/10),row=Math.floor(local/5),col=local%5;sq.targetX=bn.targetX+side*col*.010;sq.targetY=bn.targetY+(row-.5)*.030+co.offsetY*.42}}
function targetScore(i,j,d){const r=role[i],jr=role[j],wp=WEAPON[r];let s=(1-d/wp.range)*45+(100-world.hp[j])*.08+suppression[j]*.03+(targetId[i]===j?18:0);if(r===4&&(jr===1||jr===2||jr===6))s+=28;if(r===6)s+=12;return s}
function acquireTarget(i,sp,range){let best=-1,bestScore=-1e9,bestD=999,current=targetId[i];if(current>=0&&alive(current)&&world.team[current]!==world.team[i]){const d=Math.hypot(world.x[current]-world.x[i],world.y[current]-world.y[i]);if(d<=range*1.08){best=current;bestD=d;bestScore=targetScore(i,current,d)+20}}for(const j of neighbors(i,sp,Math.max(1,Math.ceil(range/sp.cell)))){if(j===i||!alive(j)||world.team[j]===world.team[i])continue;const d=Math.hypot(world.x[j]-world.x[i],world.y[j]-world.y[i]);if(d>range)continue;const s=targetScore(i,j,d);if(s>bestScore){best=j;bestD=d;bestScore=s}}targetId[i]=best;return{entity:best,distance:bestD}}
function updateSquadAI(sp){for(const sq of hierarchy.squads){let n=0,m=0,s=0,contact=-1,closest=999;for(let i=sq.start;i<sq.end;i++)if(alive(i)){n++;m+=morale[i];s+=suppression[i];const q=acquireTarget(i,sp,WEAPON[role[i]].range*1.05);if(q.entity>=0&&q.distance<closest){closest=q.distance;contact=q.entity}}const bn=hierarchy.battalions[sq.battalionId],avgM=n?m/n:0,avgS=n?s/n:0;sq.contact=contact;if(!n||avgM<20||bn.order==='RETREAT'||bn.order==='FALLBACK')sq.state=5;else if(contact<0)sq.state=bn.team===1?4:0;else if(avgS>55)sq.state=2;else if(sq.id%4===1&&bn.team===0)sq.state=3;else sq.state=1}}
function chooseState(i,hasTarget,dist){const sq=hierarchy.squads[squadId[i]],bn=hierarchy.battalions[battalionId[i]],wp=WEAPON[role[i]];if(bn.order==='RETREAT'||bn.order==='FALLBACK'||morale[i]<12)return 9;if(morale[i]<25)return 7;if(suppression[i]>=80)return 8;if(suppression[i]>=52)return 1;if(ammo[i]===0)return 5;if(!hasTarget)return 0;if(role[i]===2&&sq.state===2)return 4;if(dist>wp.optimal*1.08)return 0;if(aimTicks[i]<1)return 2;return 3}
function movementProposal(s,sp){const t0=performance.now();if(world.tick%5===0)autonomousCommand();updateSquadTargets();updateSquadAI(sp);const writes=[],step=.0095;let